### ISSUE TITLE
Doesn't load native library on OS X Core CLR

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#101]
`dnvm install -u latest -r coreclr`

On CoreCLR for OS X, NativeLibraryLoader cannot import "api-ms-win-core-libraryloader-l1-1-0".

```
DllNotFoundException: Unable to load DLL 'api-ms-win-core-libraryloader-l1-1-0': The specified module could not be found.
```

**Comment by bricelam** [comment]
It's currently just [a workaround](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs#L30) since DNX doesn't support native artifacts yet. We should skip if `CallContextServiceLocator.Locator.ServiceProvider.GetRequiredService<IRuntimeEnvironment>().OperatingSystem != "Windows"`.

**Comment by natemcmaster** [comment]
This is going to be a bigger issue because CoreCLR doesn't currently to DllImport correctly on OS X. 
`DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found.` 

Opened an issue on CoreCLR https://github.com/dotnet/coreclr/issues/1244

**Comment by natemcmaster** [comment]
Since on CoreCLR the call must use "libsqlite3", not "sqlite3", we will need to do something [Kestrel's monkey patch](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Networking/PlatformApis.cs) to support native calls. Yes, a pain because we have ~30 native calls and will need to detect which platform we are running.

**Comment by bricelam** [comment]
What, we're not building on all the [great work of Mono](http://www.mono-project.com/docs/advanced/pinvoke/#library-names)?! This displeases me...

**Comment by natemcmaster** [comment]
:+1: It seems inverted that in this issue, mono works fine, and it is .NET that is causing the problem.

**Comment by natemcmaster** [comment]
Should be fixed when https://github.com/dotnet/coreclr/pull/1248 is merged

**Comment by natemcmaster** [comment]
Blocked on https://github.com/dotnet/corefx/issues/1745

**Comment by natemcmaster** [comment]
Should be completely fixed once DNX updates to the latest CoreCLR (as of today, it still uses a version of CoreCLR pre-July 16. See https://github.com/dotnet/coreclr/pull/1248)
