### ISSUE TITLE
Upgrade travis.yml to newer, faster, better, etc

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#104]
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

We use old infrastructure because we need a newer version of SQLite than is available by default on Travis CI machines.

**Comment by natemcmaster** [comment]
Will need to request to add SQLIte > 3.7.15 to apt-whitelist.

https://github.com/travis-ci/apt-package-whitelist#package-approval-process

**Comment by BrennanConroy** [comment]
Can you install SQLite locally on the machine instead? We do it for Libuv for Kestrel

**Comment by natemcmaster** [comment]
That's what https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/.travis.yml currently does.

Running travis in container mode doesn't allow installing custom packages unless they are on the apt-package-whitelist.

**Comment by natemcmaster** [comment]
Someone already requested: https://github.com/travis-ci/apt-package-whitelist/issues/368

**Comment by BrennanConroy** [comment]
That installs it globally, see https://github.com/aspnet/KestrelHttpServer/blob/dev/.travis.yml, but if its already in the process of whitelist you can just wait

**Comment by natemcmaster** [comment]
https://github.com/travis-ci/apt-source-whitelist/issues/116
