### ISSUE TITLE
Create an async path for ExecuteReaderAsync

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#105]
With sqlite3_step_blocking now in use, we should create a better async path for executereader.
See [NativeMethods.cs:277](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs#L277)

**Comment by bricelam** [comment]
I don't think this is relevant anymore since we couldn't use `Thread.Sleep()`.
