### ISSUE TITLE
System.Threading.Thread not available on UWP

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#107]
Trying to install the latest package on UWP yields the following error.

> System.Threading.Thread 4.0.0-beta-23019 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time 
assembly compatible with win10

**Comment by bricelam** [comment]
When DNX supports it, we can add the following to our `project.json` to safeguard against this in the future.
```JSON
{
  "supports": {
    "net46.app": { },
    "uwp.10.0.app": { },
    "dnxcore50.app": { }
  }
}
```

**Comment by rowanmiller** [comment]
@natemcmaster need to sort this one out before beta7

**Comment by natemcmaster** [comment]
So does this mean UWP doesn't implement .NET Core fully? 

I'll try Task.Delay instead.

**Comment by bricelam** [comment]
@ajcvickers mentioned that, if it's never locked for long, we could probably get away with not waiting at all, just retry, retry, retry.
