### ISSUE TITLE
encoding error when using Chinese characters

### ISSUE THREAD

**Issue by John0King** [aspnet/Microsoft.Data.Sqlite#110]
I'm learning ASP.NET 5, and  i use "EntityFromework.SqlLite" .
then this happend
Add “标题内容”  became "标�"
Add "添加内容" became "添�"

Add “添加  内容”  became "添加"   notice there are two space
Add "神奇的事情发生了" became "神奇�"
Add "神奇的事 情发生了" beame "神奇的"

**Comment by rowanmiller** [comment]
Already fixed in https://github.com/aspnet/Microsoft.Data.Sqlite/pull/127
