### ISSUE TITLE
Specified cast is not valid: GetFieldValue<string>

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#111]
When retrieving a string from a NULL string column, `GetFieldValue<string>` should return null. Instead it throws.

>    System.InvalidCastException : Specified cast is not valid.
	at Microsoft.Data.Sqlite.SqliteDataReader.GetString(Int32 ordinal)
	at Microsoft.Data.Sqlite.SqliteDataReader.GetFieldValue[T](Int32 ordinal)

**Comment by bricelam** [comment]
I actually think it's current behavior is "correct" (i.e. to spec). `NULL`s in the database map to `DBNull` instances in ADO.NET, so you're asking it to cast from `DBNull` to `string` which results in a cast exception. You should always call and check `IsDBNull()` before retrieving a value from a `DbDataReader`.

**Comment by natemcmaster** [comment]
Let's match the ADO contract. So we should throw a [SqlNullException instead](https://msdn.microsoft.com/en-us/library/hh485652(v=vs.110).aspx) of InvalidCastException, right?

IMO returning "null" should be a valid return if the value is empty.

**Comment by divega** [comment]
`SqlNullException` is a SQL Server specific type AFAIK, so I don't think we can assume the ADO.NET contract prescribes an exception type, but I wonder what SqlClient throws on CoreCLR.

> IMO returning "null" should be a valid return if the value is empty.

I kind of agree that it would make it a more usable API, but not sure we should special case strings or even reference types.

**Comment by natemcmaster** [comment]
If we are trying to adhere to ADO.NET (i.e. require IsDbNull check first), then let's not modify the current behavior.
