### ISSUE TITLE
Cannot bind to parameters in pragma statement

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#112]
```c#
var indexInfo = connection.CreateCommand();
 indexInfo.CommandText = "PRAGMA index_info(@p0);";
 indexInfo.Parameters.AddWithValue("@p0", index.Name);
```
>    Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'near "@p0": syntax error'
	at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
	at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
	at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()

**Comment by bricelam** [comment]
Isn't this a SQLite limitation? Parameters are only allowed in certain parts of a statement.

**Comment by natemcmaster** [comment]
What does SqlClient do?

**Comment by bricelam** [comment]
It has the same limitations. You can basically only use parameters where you can use literals (not identifiers or other tokens)

**Comment by natemcmaster** [comment]
Ok.
