### ISSUE TITLE
Fix bug in ShouldSerialize on Mono

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#117]
![image](https://cloud.githubusercontent.com/assets/2696087/9365191/1193b888-4665-11e5-8dbd-c2b271ed25dd.png)

The build is failing on Mono, reporting 2 tests. Can't tell which tests failed.

~~Blocked on https://github.com/xunit/xunit/issues/525~~

**Comment by natemcmaster** [comment]
Something changed beneath our feet.
![image](https://cloud.githubusercontent.com/assets/2696087/9446953/8471c7c2-4a49-11e5-8880-e38b5e68fd93.png)

**Comment by natemcmaster** [comment]
This is a regression in Mono 4.0.3.

**Comment by akoeplinger** [comment]
Btw. I think [this commit](https://github.com/mono/mono/commit/8d29aafd1c6d6e4edd5b2dd99411b97bc9ce8ea8) is why you're running into the problems on 4.0.3. I'm reaching out to see why it was reverted.

**Comment by natemcmaster** [comment]
@akoeplinger thanks for identifying this!
