### ISSUE TITLE
PCL build?

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/Microsoft.Data.Sqlite#122]
I was able to build System.Data.Common and Microsoft.Data.Sqlite against PCL Profile 151, with very few changes (https://github.com/AlekseyMartynov/Microsoft.Data.Sqlite/commits/pcl). And it worked well together with WinRT SDKs available from https://www.sqlite.org/download.html.

Not sure whether it's of any use. Do you consider targeting PCL profiles or focus entirely on the future of .NET Core?

**Comment by natemcmaster** [comment]
We have considered PCL (see https://github.com/aspnet/Microsoft.Data.Sqlite/issues/21). We may leverage PCL, but for now this package is still focused on supporting .NET Core.

**Comment by AlekseyMartynov** [comment]
Thank you for the clarification
