### ISSUE TITLE
SQLite under IIS Express requires Administrator privileges

### ISSUE THREAD

**Issue by jwdavidson** [aspnet/Microsoft.Data.Sqlite#132]
An attempt to run an application accessing an Sqlite db in VS2015 Community as a regular user with IIS Express fails with an error 14: "unable to open database."

The error does not occur if VS2015 Community was opened with Administrator privileges.

The error also does not occur if the same application is run using WebListener as a regular user.

This is more informational than a bug report, as it took me a while to determine what the error really was (need a Windows 10 capable SysInternals).

**Comment by natemcmaster** [comment]
Could be a file permissions error. 

Also, I've seen this error with high load web applications producing a deadlock on opening the file.

**Comment by jwdavidson** [comment]
The only load I had was to create the Identity tables, add one role, one user and one user/role. Not much of a load. This was on an i7 Windows 10 box with 8 GB ram. I was using VS2015 Community

**Comment by natemcmaster** [comment]
@jwdavidson and what about file permissions?

**Comment by jwdavidson** [comment]
There are 3 accounts that have permission on the db file and all 3 have Full Control. The accounts are System, my login and Administrators. The permissions are default.

**Comment by natemcmaster** [comment]
This is likely related to #55. SQLite uses `Environment.CurrentDirectory`

**Comment by natemcmaster** [comment]
To ensure the db file is in your application directory, make sure to set the path.
```c#
    public class Startup
    {
        private IApplicationEnvironment _appEnv;

        public Startup(IApplicationEnvironment appEnv)
        {
            _appEnv = appEnv;
        }
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddEntityFramework()
                .AddSqlite()
                .AddDbContext<MyContext>(
                    options => { options.UseSqlite($"Data Source={_appEnv.ApplicationBasePath}/test.db"); });
        }
}
```

**Comment by jwdavidson** [comment]
That tip on how SQLite sets CurrentDirectory above explains where the database went initially. After I couldn't find it used a FullPath to set the path. That may have caused the requirement for admin rights.

I decided to use SQL Server for the savings in development time and will return to using SQLite probably with beta8 release. This should leave some hints for those who follow and want to keep trying SQLite for now.
