### ISSUE TITLE
Use 64-bit sqlite3.dll for win-x64

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#138]
Currently we only support x86 on Windows.

**Comment by natemcmaster** [comment]
cc @bricelam

**Comment by bricelam** [comment]
Hmm, that's a mixed-mode assembly... It's also released under a different license than the rest of SQLite. I would advise not to.

At one point I heard that the SQLite team would produce a v3 NuGet package that contained the native library for various platforms. Once they do, we'll depend on that and get out of the business of redistributing sqlite3.dll.

**Comment by natemcmaster** [comment]
I thought only the "bundle" packages were mixed-mode, which is not the package I linked to above.

If for legal reasons we can't redistribute this, what about using https://www.nuget.org/packages/System.Data.SQLite.Core/? This package includes the same DLLs.

**Comment by natemcmaster** [comment]
Discussed with @bricelam. We are trying to avoid redistributing sqlite3.dll at all and will defer solving this until we are unblocked by other teams.

In the meantime, there is a very simple workaround for those who need win-x64. 

## Workaround

Manually add a 64-bit version of `sqlite3.dll`.

1. Find the package install location. This could be `%USERPROFILE%\.dnx\packages\Microsoft.Data.Sqlite\(version)\` or `(your project)\packages\Microsoft.Data.Sqlite\`.
1. Create a 2 new folders in the package install location: `(package)\runtimes\win\native\x64\` and `(package)\runtimes\win-x64\native\`.
2. Download https://www.nuget.org/api/v2/package/System.Data.SQLite.Core/1.0.98.1/ and unzip. (Rename *.nupkg => *.zip).
3. From the unzipped *.nupkg, copy `(nupkg)\build\net451\x64\SQLite.Interop.dll` into both new folders from step 2 and rename to `sqlite3.dll`

**Comment by natemcmaster** [comment]
Still waiting on https://github.com/aspnet/dnx/issues/402 (bumped from beta8 to rc1)

**Comment by bricelam** [comment]
@natemcmaster I don't think we're actually waiting on aspnet/dnx#402 for anything here. We have custom code to find the right library on DNX

**Comment by natemcmaster** [comment]
Yup. Can close this with #152.
