### ISSUE TITLE
User-defined functions

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#14]
SQLite allows you to [create or redefine SQL functions](http://sqlite.org/c3ref/create_function.html). We want to enable this by using calls like the following.

```C#
connection.CreateFunction(
    "random",
    new Random(),
    r => r.Next());

connection.CreateFunction(
    "length",
    (string s) => s.Length);

connection.CreateFunction<long, long, long>(
    "max",
    Math.Max);

connection.CreateAggregate(
    "count",
    0,
    (long count, object[] args) => count++);

connection.CreateAggregate(
    "sum",
    (long sum, long i) => sum + i);
```

If you specify a parameter of type `object`, it will only ever be one of SQLite's primitive types: `long`, `double`, `string`, or `byte[]`.

If you specify a parameter of a type other than `object`, we will attempt to coerce the value into that type before passing it to you using the same semantics as `SqliteDataReader.GetFiledValue<T>()`.

The result will be coerced based on its type using the same semantics as `SqliteParameter.Value`.

If you specify a single parameter of type `object[]`, the function can take a variable number of arguments.

The definitions for the API would look like this. Methods with a type argument T1..N will be expanded into N overloads. We should generate the overloads using a `*.tt` file.

```C#
public class SqliteConnection
{
        public virtual void CreateFunction<TResult>(
            string name,
            Func<TResult> function);

        public virtual void CreateFunction<T1..16, TResult>(
            string name,
            Func<T1..16, TResult> function);

        public virtual void CreateFunction<TState, TResult>(
            string name,
            TState state,
            Func<TState, TResult> function);

        public virtual void CreateFunction<TState, T1..15, TResult>(
            string name,
            TState state,
            Func<TState, T1..15, TResult> function);

        public virtual TContext CreateAggregate<TContext>(
            string name,
            Func<TContext, TContext> func);

        public virtual TContext CreateAggregate<TContext, T1..15>(
            string name,
            Func<TContext, T1..15, TContext> func);

        public virtual TContext CreateAggregate<TContext>(
            string name,
            TContext seed,
            Func<TContext, TContext> func);

        public virtual TContext CreateAggregate<TContext, T1..15>(
            string name,
            TContext seed,
            Func<TContext, T1..15, TContext> func);

        public virtual TResult CreateAggregate<TContext, TResult>(
            string name,
            TContext seed,
            Func<TContext, TContext> func,
            Func<TContext, TResult> resultSelector);

        public virtual TResult CreateAggregate<TContext, T1..15, TResult>(
            string name,
            TContext seed,
            Func<TContext, T1..15, TContext> func,
            Func<TContext, TResult> resultSelector);
}
```

**Comment by AlexanderTaeschner** [comment]
There are two types of UDFs in SQLite: functions or aggregates. I would suggest to tackle functions (like 'Cos(x)') first and aggregates somewhat later, since they are much more complex (need two functions step and final). Using SQLitePCL.raw functions can be defined via sqlite3_create_function which needs four parameters: the database handle, the name, an object passed to the function, and the function of type delegate_function_scalar with the following signature: `public delegate void delegate_function_scalar(sqlite3_context ctx, object user_data, sqlite3_value[] args);`. The function arguments are passed via the args array, where the sqlite3_value are only pointers and the user has to use one of the sqlite3_value_* functions (like `raw.sqlite3_value_double`) to actually access the value. The function result has to be set by using one of the sqlite3_result_* functions (like `sqlite3_result_int64`). 
My proposal would be to add the following function to `SqliteConnection`:
`public void CreateFunction(string name, int numberOfArguments, Func<SqliteValue[], SqliteValue> function)`
The arguments would be passed into the user function as array of a new wrapper class `SqliteValue` which provides a property `Value` to access the value. This function would return the result as SqliteValue. Setting this value would than happen in an anonymous method created by the call to `CreateFunction`. Since only the four Sqlite data types INTEGER, FLOAT, TEXT and BLOB are allowed as result I would propose to add four constructors to `SqliteValue` for `long`, `double`, `string`, and `byte[]` and store these value in `Value` and the Sqlite type in an internal field, which is read out for using the correct sqlite3_result_ function.
From the user point of view the declaration of a ceil function could look like this than:
```
        public void CreateFunction_works()  
        {  
            using (var connection = new SqliteConnection("Data Source=:memory:"))  
            {  
                connection.Open();  
                connection.CreateFunction("Ceiling", 1, MyCeilingFunction);  
  
                Assert.Equal(2L, connection.ExecuteScalar<long>("SELECT Ceiling(1.1);"));  
            }  
        }  
  
        private SqliteValue MyCeilingFunction(SqliteValue[] arguments)  
        {  
            var arg = (double)arguments[0].Value;  
            return new SqliteValue((long)Math.Ceiling(arg));  
        }
```

**Comment by bricelam** [comment]
As additional input into the design, System.Data.SQLite does it like this.
```C#
connection.BindFunction(
    new SQLiteFunctionAttribute("Ceiling", 1, FunctionType.Scalar),
    (Func<object[], object>)((object[] args) => MyCeilingFunction((object[])args[1])),
    null);
```
```C#
object MyCeilingFunction(object[] args)
{
    var arg = (double)args[0];
    return Math.Ceiling(arg);
}
```
The `BindFunction` is atrocious when used like this, but it was designed before lambdas and this isn't the primary way to do it. They also scan the assembly (something we try to avoid) for types with the `[SQLiteFunction]` attribute:
```C#
[SQLiteFunction("Ceiling", 1, FunctionType.Scalar)]
class MyCeilingFunction : SQLiteFunction
{
    public override object Invoke(object[] args)
    {
        var arg = (double)args[0];
        return Math.Ceiling(arg);
    }
}
```

The `FunctionType` enum lets you register scalar, aggregate, and collation functions the same way (by overloading the delegates' semantics or overriding different methods on `SQLiteFunction`).

The *only* thing I like about their implementation is that you work directly with primitive CLR types without having to worry about any SQLite-specific constructs.

**Comment by bricelam** [comment]
Ideally, I want to just have to do this:

```C#
connection.CreateFunction("Celing", Math.Ceiling);
```

The argument binding and return value would all be handled for me.

For aggregates, I would want overloads (or a separate methods like `CreateAggregate`) that took parameters similar to [Enumerable.Aggregate](https://msdn.microsoft.com/en-us/library/system.linq.enumerable.aggregate.aspx).

**Comment by bricelam** [comment]
In other words: Let's make it feel as .NET/C# as possible and hide any SQLite implementation details from the user.

**Comment by AlexanderTaeschner** [comment]
Using SQLitePCL.raw to implement the three types of user defined functions, we have three different functions with the following signatures:
```
public static int sqlite3_create_collation(sqlite3 db, string name, object v, delegate_collation f);
public static int sqlite3_create_function(sqlite3 db, string name, int nArg, object v, delegate_function_scalar func);
public static int sqlite3_create_function(sqlite3 db, string name, int nArg, object v, delegate_function_aggregate_step func_step, delegate_function_aggregate_final func_final);
```
For me, these three can be divided into two categories which I would address in different ways:

1.) Collations (#14):
`int delegate_collation(object v, string s1, string s2)` is simply an enhanced `int Comparison<string>(string x, string y)` delegate, where the `object v` is initialized with the registration of the collation. Since this can be also achieved by a closure, I would suggest to limit the user defined collations to delegates of type `Comparison<string>` with the following method for registration:
```
public partial class SqliteConnection : DbConnection
{
    public void CreateCollation(string name, Comparison<string> comparison);
}
```

2.) Scalar functions and aggregates(#19):

The three delegates `delegate_function_scalar`, `delegate_function_aggregate_step` and `delegate_function_aggregate_final` are much less intuitive to use. All three do not return a value, although they are used to implement functions. Special functions have to be called to set the result values and even getting the input values is not trivial (see above). This should be encapsulated as good as possible although the limitation to the four value types (INTEGER, FLOAT, TEXT, and BLOB) have to be made clear to the user.
Looking at the three delegates:
```
public delegate void delegate_function_scalar(sqlite3_context ctx, object user_data, sqlite3_value[] args);
public delegate void delegate_function_aggregate_step(sqlite3_context ctx, object user_data, sqlite3_value[] args);
public delegate void delegate_function_aggregate_final(sqlite3_context ctx, object user_data);
```
I would propose the following method for registration of these kind of UDFs:
```
public partial class SqliteConnection : DbConnection
{
    public void CreateScalarFunction(string name, int numberOfArguments, Func<SqliteValue[], SqliteValue> scalarFunction);
    public void CreateAggregateFunction(string name, int numberOfArguments, Func<SqliteValue[], SqliteValue> aggregateStepFunction, Func<SqliteValue> aggregateResultFunction);
}
```
with the following wrapper class for the values:
```
public class SqliteValue
{
    public SqliteValue(double value);
    public SqliteValue(long value);
    public SqliteValue(string value);
    public SqliteValue(byte[] value);
    public double ToFloat(); // throws if stored value is BLOB, tries parsing TEXT, converts INTEGER
    public long ToLong(); // throws if stored value is BLOB, tries parsing TEXT, converts FLOAT
    public string ToString(); // throws if stored value is BLOB, converts INTEGER, converts FLOAT
    public byte[] ToBytes(); // throws if stored value is not BLOB
}
```

**Comment by bricelam** [comment]
I'm still not sure if having a public type to represent `sqlite3_value` is necessary. On `SqliteDataReader`, `GetFieldValue<T>()` seems to be sufficient. If you don't know the type, you ask for an `object` and test the type. I think Microsoft.Data.Sqlite can do a lot of heavy lifting in this area to hide the implementation details of SQLite from applications.

**Comment by bricelam** [comment]
Some open questions:
* How do we allow deleting functions?
  * Just pass `null`
* How do we support variable arguments?
* How do we support dynamicly-typed arguments?
* Should we support any of these more obscure functions?
  * sqlite3_aggregate_context
  * sqlite3_context_db_handle
  * sqlite3_get_auxdata
  * sqlite3_result_subtype
  * sqlite3_set_auxdata
  * sqlite3_user_data
  * sqlite3_value_dup
  * sqlite3_value_free
  * sqlite3_value_subtype

**Comment by bricelam** [comment]
@AlexanderTaeschner I'll try to put together some notes and proposals and bring this up at Thursday's design meeting.

**Comment by AlexanderTaeschner** [comment]
> I'm still not sure if having a public type to represent  sqlite3_value  is necessary.

The main advantage for the public type is for me, that the restriction to the strictly typed constructors enable the API user to know which CLR types are supported as values, so that he does not get an exception at runtime. For getting the current value there are many possibilities: the proposed strict converters, a GetValue<T> function or a simple property Value returning an object (as presented in my first comment).

**Comment by bricelam** [comment]
My counter argument is that we've hidden the limited number of types by transparently coercing values in both SqliteDataReader and SqliteParameter, so it may be more consistent to do the same here. Although, I also see some benefits to exposing sqlite3_value. I'll bring up both possibilities when discussing with the team

**Comment by bricelam** [comment]
Both options could also coexist.

**Comment by bricelam** [comment]
I think I'm landing on something like this:
```C#
connection.CreateFunction(
    "length",
    1,
    args => args[0].GetString().Length);

// With additional overloads like Enumerable.Aggregate
connection.CreateFunction(
    "count",
    -1,
    0,
    (aggregate, args) => aggregate++);
```

Sugar APIs could be added over the top to handle the value coercion and infer argument count.
-----
```C#
connection.CreateFunction(
    "length",
    (string s) => s.Length);

connection.CreateFunction(
    "count",
    0,
    (int count, object[] args) => count++);
```

**Comment by bricelam** [comment]
Here are some examples of how to do those in SQLitePCL.raw
```C#
SQLitePCL.raw.sqlite3_create_function(
    db,
    "length",
    1,
    null,
    (ctx, user_data, args) => SQLitePCL.raw.sqlite3_result_int64(
        ctx,
        SQLitePCL.raw.sqlite3_value_text(args[0]).Length));
    
SQLitePCL.raw.sqlite3_create_function(
    db,
    "count",
    -1,
    null,
    (ctx, user_data, args) => ctx.state = (ctx.state is int i ? i : 0) + 1,
    (ctx, user_data) => SQLitePCL.raw.sqlite3_result_int64(ctx, ctx.state is int i ? i : 0));
```

**Comment by bricelam** [comment]
I've update the issue description with the design we landed on. It took a different direction than I was anticipating. We opted for the most idiomatic C# design.

**Comment by AlexanderTaeschner** [comment]
I started a new implementation of the new API spec at https://github.com/AlexanderTaeschner/Microsoft.Data.Sqlite/tree/Issue14V2. I will see what I can do next week (haven't used T4 before).

**Comment by bricelam** [comment]
Don't fear T4. It's a very trivial tempting language. Here's [the documentation](https://msdn.microsoft.com/en-us/library/bb126478.aspx).

```
<#@ assembly name="System.Core" #>
<#@ import namespace="System.Linq" #>
<#
    for (var i = 1; i <= 16; i++)
    {
        var typeArgs = Enumerable.Range(1, i).Select(j => "T" + j).ToList();
#>
        public virtual void CreateFunction<<#= string.Join(", ", typeArgs) #>, TResult>(
            string name,
            Func<<#= string.Join(", ", typeArgs) #>, TResult> function);
<#
    }
#>
```

**Comment by AlexanderTaeschner** [comment]
I have a problem with the aggregate functions, e.g.
```
public virtual TContext CreateAggregate<TContext>(
            string name,
            Func<TContext, TContext> func);
```
What should be the result of this function (at registration time we do not have access to the context!)?

**Comment by bricelam** [comment]
That one is a little non-obvious. See the remarks on the corresponding `Enumerable.Aggregate` [overload](https://msdn.microsoft.com/en-us/library/bb548651.aspx).  Basically context is initialized with the first row, and whatever its value is after the last row is the result.

**Comment by bricelam** [comment]
Ah, that overload in particular since it doesn't take a value... Can you register an aggregate that doesn't take a value? Maybe none of those overloads make sense.

**Comment by bricelam** [comment]
Oh, it looks like you can. `SELECT count() FROM MyTable` works. In that case, context should be initialized to `null`, and the result is whatever `context` is after all the rows finish. So you could do this.

```C#
connection.CreateAggregate(
    "count",
    ctx =>
    {
        if (ctx == null)
           ctx = 0;

        return (int)ctx + 1;
    });
```

**Comment by AlexanderTaeschner** [comment]
I think we do not speak about the same: With my implementation you can, e.g. create
`connection.CreateAggregate("mycount", (long count) => ++count);` which calls the overload above, or
`connection.CreateAggregate("mycount", -4L, (long count) => ++count); ` which would call the overload `public virtual TContext CreateAggregate<TContext>(string name, TContext seed, Func<TContext, TContext> func);`. In the first case the context state is initialized with 0 in the second with -4. My question is: if I call the functions above with:
```
var res1 = connection.CreateAggregate("mycount", (long count) => ++count);
var res2 = connection.CreateAggregate("mycount", (long count) => ++count);
```
what is the desired content of res1 and res2? In my implementation it is 0 and -4, but that was only a guess to get started.

**Comment by bricelam** [comment]
The result should be zero for both calls. The context for aggregates should reset for every aggregate. In SQLitePCL.raw words, use `sqlite3_context.state`, not `user_data`.

**Comment by bricelam** [comment]
With the proposed design, there is no way to use `user_data` with aggregate functions.

**Comment by AlexanderTaeschner** [comment]
Arg, I messed up the two calls, it should have been:
```csharp
var res1 = connection.CreateAggregate("mycount", (long count) => ++count);
var res2 = connection.CreateAggregate("mycount", -4L, (long count) => ++count);
```
wherein the two different overloads are called.
Please take a look to the proposed implementation in #355. I use sqlite3_context.state to store the current state and either initialize it with `default(TContext)` or with the `seed` depending on the overload. The sqlite3_context.state is only accessible within the step (and final) delegate (where this initialization is happening), but not at the stage when I register these two delegates in the CreateAggregate function. Therefore my question is what the result value of the function calls should be?

**Comment by bricelam** [comment]
Yes, `0` and `-4` then.

**Comment by AlexanderTaeschner** [comment]
Fine, this is implemented in #355 :)

**Comment by bricelam** [comment]
I agree it's a little silly with those examples, but C# doesn't let you do `(ref long count) => ++count` so it's the best we can do.

**Comment by bricelam** [comment]
Technically, we *could* provide a delegate with a `ref`, but it's overkill and doesn't mirror `Enumerable.Aggregate`.

**Comment by bricelam** [comment]
Oh funny, but you can do `delegate (ref long count) { ++count; }`

**Comment by Globalcaching** [comment]
Are there plans to implement the CreateFunction on the connection? And if so, is it high or low on the priority? I am asking this, because I am using the library in an upcomming web application, but I am missing this feature that I really need.

**Comment by bricelam** [comment]
@Globalcaching, PR #355 has a working implementation. Unfortunately, we won't have time to get it into version 2.0.0. However, we intend to merge it before releasing version 2.1.0-preview1-final.

**Comment by Globalcaching** [comment]
@bricelam thank you for the update.
I appreciate all the work you do for this project. This library is vital for a lot of applications.

**Comment by bricelam** [comment]
Hmm, our design is a little crippled by dotnet/csharplang#129.

Instead of being able to specify this...
```csharp
connection.CreateFunction("func1", MyFunctions.Func1);
```
...you'll always have to use a lambda.
```csharp
connection.CreateFunction("func1", (int i) => MyFunctions.Func1(i));
```

**Comment by bricelam** [comment]
Note it's not as bad as `ModelBuilder.HasDbFunction()` since all we need is a delegate to invoke, not the `MethodInfo` to translate.

**Comment by evil-shrike** [comment]
Excuse me, the issue is closed, so it's implemented, right? But I can't see any `CreateFunction` method in `SqliteConnection`...

**Comment by evil-shrike** [comment]
Ok, noticed the tag "2.1.0". Is hasn't released yet. Do you have time plans for 2.1? It's more than 3 months passed since 2.0. At least a beta/preview would be highly desirable.

**Comment by bricelam** [comment]
See [the roadmap](https://github.com/aspnet/Home/wiki/Roadmap). Try [the nightly builds](dotnet.myget.org/gallery/aspnetcore-dev).

**Comment by evil-shrike** [comment]
Aaah, it's part of the whole aspnetcore. I see, sorry, thanks for links. But don't you consider to allow the provider to have its own release cycle?

**Comment by bricelam** [comment]
We share all our internal build infrastructure with .NET Core, ASP.NET Core, Entity Framework Core, et al., so while it's possible to release out-of-band, it's just easier to just let it happen alongside the rest of the stack.
