### ISSUE TITLE
Support CommandBehavior.CloseConnection to ExecuteReader

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#142]
Currently we only support `CommandBehavior.Default` and `CommandBehavior.SequentialAccess`.

Add support for `CommandBehavior.CloseConnection` to `SqliteDataReader.ExecuteReader(CommandBehavior behavior)`

**Comment by divega** [comment]
:+1: dupe of #114?

**Comment by divega** [comment]
Ah, I guessed you created this new bug because you already submitted a fix for the SequentiaAccess of #114 and you plan to close that bug.

**Comment by divega** [comment]
I don't think this is lower priority so cleared up the milestone to bring it back to triage.
