### ISSUE TITLE
Leverage sqlite3_unlock_notify when possible

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#143]
Currently we support command timeouts by looping when locked on `sqlite3_step`. For those using a library compiled with SQLITE_ENABLE_UNLOCK_NOTIFY, we can instead use `sqlite3_unlock_notify()` for better performance.

see https://www.sqlite.org/unlock_notify.html

**Comment by natemcmaster** [comment]
Initial progress https://github.com/natemcmaster/Microsoft.Data.Sqlite/blob/blocking/src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs#L287

**Comment by natemcmaster** [comment]
Will be more important when https://github.com/aspnet/Microsoft.Data.Sqlite/issues/148#issuecomment-146277153 is done.

**Comment by bricelam** [comment]
Closing as won't fix. We've moved to SQLitePCL.raw which doesn't expose `sqlite3_unlock_notify`, and this is too low priority to request it be added there.
