### ISSUE TITLE
Unable to load sqlite3 dll in rc1-15643

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Microsoft.Data.Sqlite#147]
![image](https://cloud.githubusercontent.com/assets/2216750/10210642/0cba726a-681c-11e5-9233-52c69c9e986c.png)

**Comment by Kagamine** [comment]
The problem not appear to "EntityFramework.Sqlite": "7.0.0-rc1-15855" 
this is  "EntityFramework.Sqlite": "7.0.0-rc1-15865"

**Comment by natemcmaster** [comment]
Are you using 64bit?

**Comment by Kagamine** [comment]
yes it is dnx451 x64

**Comment by natemcmaster** [comment]
Unfortunately, x64 is not supported yet on windows....we are working on it. In the meantime, this is the best workaround I can offer if you need x64. (see https://github.com/aspnet/Microsoft.Data.Sqlite/issues/138#issuecomment-140823192) Otherwise use x86.
