### ISSUE TITLE
Allow using an external version of sqlite3.dll

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Microsoft.Data.Sqlite#148]
We ship a version in the NuGet package, but we should provide a way to use a version that is obtained from elsewhere.

**Comment by Eilon** [comment]
There might be some NuGet 3 features that could help with this, such as using Runtime IDs (`rid`s). Should discuss with some NuGet experts because this *might* be super easy.

**Comment by natemcmaster** [comment]
Related: we can start falling back to `C:\Windows\System32\winsqlite3.dll` (which is ships in Win10 installations) if we are unable to load a nuget sqlite3.dll

**Comment by Eilon** [comment]
Is that copy of SQLite meant for public consumption, or is it a private copy for Windows?

**Comment by natemcmaster** [comment]
AFAIK yes. On my machine, it is SQLite 3.8.8.3, x64. It works with all of the tests in this project.

**Comment by natemcmaster** [comment]
(as in yes, meant for public consumption)

**Comment by Eilon** [comment]
Do you know if there's any official-looking statement of this? Or if not, can we contact the owners? I want to make sure if we allow it that there's some level of guarantee around it.

**Comment by natemcmaster** [comment]
I couldn't find anything. I supposed its existence implied it's available for general use. I haven't tested against many versions of Windows, which is why I suggested only as a fallback. The fallback may not be necessary if we can get a good SQLite nuget package.

**Comment by davidfowl** [comment]
I think we should just change this package to use DllImport. The runtime should set the system up in such a way that it will get the right one (architecture wise). For csproj based projects that copy to output would need to preserve the folder structure in the bin folder so that this works. CoreCLR based runtimes can read the project.lock.json and do the right thing.

Assuming that part was figured out, the user could just update to the latest SQLite package package and get the latest bits. DllImport will also search the default search paths so I'm not sure you'd need to do anything else.

**Comment by bricelam** [comment]
@davidfowl This issue is more about the user creating a custom build of SQLite, not just updating to the latest official release.

**Comment by davidfowl** [comment]
Custom build of SQLite.... ok :smile:

**Comment by bricelam** [comment]
lol, yeah... It's a common and supported scenario; see [Compilation Options For SQLite](http://sqlite.org/compile.html) for all the buttons and knobs.

**Comment by Eilon** [comment]
@natemcmaster I definitely wouldn't recommend assuming that existence implies availability for general use. It has to be a documented feature to be available for general use. If we know what component drops it there we can contact that team and find out their usage policy.

**Comment by rowanmiller** [comment]
@Eilon the Windows team has been working to have a local copy of SQLite available for use (and they have been asking us to ensure EF can make use of it). @natemcmaster not sure if you have confirmed that is the one they want us to use? My understanding was there would be an API we call to find the assembly to load.

**Comment by natemcmaster** [comment]
@Eilon internal email powers FTW.
@rowanmiller  I wasn't aware of plans other than I heard (in a rumor type way) that a Windows team was making a NuGet package for sqlite3 native binaries.

**Comment by divega** [comment]
With the work we are doing in #237 we will depend on a package containing sqlite3 native libraries appropriate for a wider set of platforms which  should improve the default experience of using Microsoft.Data.Sqlite and Microsoft.EntityFrameworkCore.Sqlite. 

However this issue remains unaddressed. 

One possible way to address it would be to create "NoNative" variants of our packages. Possibly the "default" packages could become metapackages that depend on both the "NoNative" and the native distribution package.

We probably would need to address for RTM. As far as I understand we could refactor our packages in this way in the future without it being a breaking change.

**Comment by bricelam** [comment]
I'm starting to think that `Microsoft.Data.Sqlite` shouldn't depend on `sqlite`. Instead, we can throw a friendly error at runtime pointing users to the `sqlite` package as one possible way of acquiring the library. We could even try to loading `winsqlite3.dll` on UWP if `sqlite3.dll` wasn't found.

**Comment by bricelam** [comment]
The ASP.NET templates for that use SQLite could even include a reference to the package by default.

**Comment by bricelam** [comment]
BTW, falling back to `winsqlite3` would make UWP like every other platform where, if you don't include an app-local version of `sqlite3`, it will just use the system's. We could even consider removing `SqliteEngine.UseWinSqlite3()`.

**Comment by ali-hk** [comment]
Just wanted to clarify some things about winsqlite:
- It is officially sanctioned and intended to be used by UWPs as a means of reducing app package size. The following article outlines this: https://msdn.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases
- There is a major caveat to using winsqlite, which is the fact that it only exists in Windows 10 (10586) and above. This means Windows 10 RTM (10240) does NOT have winsqlite (you can confirm this by peeking in the system32 directory). As a result of this, it is not safe to fallback on winsqlite automatically as suggested by @bricelam. Using winsqlite should be an explicit opt-in by the developer. 
- Also, removing the option to opt-out of winsqlite precludes developers from using a custom, perhaps newer, build of sqlite if they so choose.

In my opinion @divega's approach is probably the best.

**Comment by bricelam** [comment]
To be clear, we'd always try for `sqlite3` *first* but if we can't find it, we'd fallback to `winsqlite3`. Hence, to opt out of using it, include a copy of `sqlite3` with your app.

**Comment by bricelam** [comment]
(But I understand your point that falling back may hide the fact that some users you deploy to may not actually have it.)

**Comment by natemcmaster** [comment]
What if we used NuGet magic to enable this? (names not concrete...just suggestions)
```
Microsoft.Data.Sqlite.Core (includes implementation of the ADO.NET contracts and takes in `ISqlite3`
Microsoft.Data.Sqlite.libsqlite3 (includes implementation of `ISqlite3` for "sqlite3" and brings in native assets)
    --depends on--> SQLite.Native 3.12.2
Microsoft.Data.Sqlite.winsqlite3 (includes an implementation of `ISqlite3` that p/invokes winsqlite3)
Microsoft.Data.Sqlite.sqlcipher (includes an implementation of `ISqlite3` that p/invokes sqlcipher)
```

We could still produce a default metapackage "Microsoft.Data.Sqlite".

**Comment by bricelam** [comment]
@rowanmiller @divega @natemcmaster and I discussed this and here is package structure we would like to have.

![image](https://cloud.githubusercontent.com/assets/1226749/15756579/be1ce0a0-28b6-11e6-942c-b0a9108a3a03.png)

To opt-out of distributing `sqlite3.dll`, simply add `.NoNative` to your top-level package using SQLite.

**Comment by divega** [comment]
FWIW, once we have that, additional flavor packages such as the ones @natemcmaster suggested at https://github.com/aspnet/Microsoft.Data.Sqlite/issues/148#issuecomment-223375106 should be closer to doable. I think we would need to look at what it would take to enable bringing your own `ISqlite3` implementation.

**Comment by bricelam** [comment]
Note to implementer: We should throw a firendly exception if the version of SQLite being used is less than our minimum required version (3.7.9ish)

**Comment by natemcmaster** [comment]
Discovered recently that NuGet supports an "exclude" feature. Instead of splitting our package, would adding this to project.json be sufficient for those who don't want the sqlite3.dll we provide?

```
{
	"dependencies": {
		"SQLite.Native": {         /* for any other type of project */
			"version": "3.12.2",
			"exclude": "native"
		},
		"SQLite.UWP.Native": {   /* for UWP */
			"version": "3.12.2",
			"exclude": "native"
		}
	}
}

**Comment by rowanmiller** [comment]
The `"exclude": "native"` means just exclude native binaries?

**Comment by natemcmaster** [comment]
Yes it prevents any "native" asset from being included in the lock file, and hence the build and publish output. There is also `"exclude": "all"`, but the SQLite.* packages don't have managed components so it's the same as `"exclude": "native"`.

**Comment by rowanmiller** [comment]
Yeah this looks like exactly what we want

**Comment by bricelam** [comment]
But it won't solve the problem for `packages.config`-based projects.

**Comment by natemcmaster** [comment]
For people in `packages.config`, could they just do 
`Install-Package Microsoft.Data.Sqlite -IgnoreDependencies` 

Or if it's already been installed, 
`Uninstall-Package SQLite -Force -RemoveDependencies`

**Comment by rowanmiller** [comment]
These solutions sound like they solve the issue to me. From my perspective I think we could document these and then close this issue out. Thoughts?

**Comment by natemcmaster** [comment]
👍 It solves it for me too. Anyone opposed?

**Comment by divega** [comment]
Would that help with creating an experience for using an alternative native version, e.g. winsqlite3.dll? Besides that I am not against postponing this issue (even indefinitely)  if folks think the workaround is reasonable. I personally think having to force uninstalling sqlite or excluding its native components (and having to know which one to do) goes beyond what most customers would want to ever deal with in NuGet, but I can certainly see the value of this as a workaround.

**Comment by rowanmiller** [comment]
From my perspective this isn't really a workaround, but a feature of NuGet that is designed to achieve the scenario in question ("I know your package says it needs this dependency, but trust me, I'm going to supply it myself"). 

I agree the feature isn't super easy to use, but this is a pretty advanced scenario so I think it is ok.

**Comment by natemcmaster** [comment]
New information to consider: I've learned that despite project.json allowing users to exclude sqlite3.dll from compile output, the .NET Native toolchain will still compile p/invoke delegates for "sqlite3.dll". These dangling p/invokes cause the app to crash on start, regardless of whether code is invoked or not. Lazy-loading native libraries is not currently available on .NET Native and may not be for some time.  If we do the package split, `Microsoft.Data.Sqlite.NoNative` library cannot contain the P/Invokes to "sqlite3".

Given that, the original design in https://github.com/aspnet/Microsoft.Data.Sqlite/issues/148#issuecomment-223383478 will need to change slightly.

**Comment by bricelam** [comment]
@natemcmaster #249 is also tracking that issue. I think @divega's design is the right answer here: expose an `ISqlite3` interface in the core assembly and have P/Invoke implementations of it in various native interop assemblies.

**Comment by divega** [comment]
That should in general work, although I think @natemcmaster is right that we would need something slightly different from what we had in the diagram in https://github.com/aspnet/Microsoft.Data.Sqlite/issues/148#issuecomment-223383478: the "sqlite3.dll" specific implementation of `ISqlite3` would need to live somwhere. It seems the best place is `Microsoft.Data.Sqlite`, so `Microsoft.EntityFrameworkCore.Sqlite` will have to depend on `Microsoft.Data.Sqlite` instead of depending on the `SQLite` package directly (so maybe we just got an arrow wrong :smile:).

FWIW, in conversations with the .NET Native folks it was also brough up that we could go low level with `LoadPackagedLibrary()` and `GetProcAddress()` instead of `[DllImport(...)]` to avoid the native compiler from hardcoding the native assembly import. Not sure if that could lead to a workable solution though.

**Comment by divega** [comment]
@bricelam are we still planning to do anything about this for 1.1.0-preview1 or are we going to rely on the switch to SQLitePCL.raw to take care of it at a later point?

**Comment by bricelam** [comment]
The current plan is to switch to SQLitePCL.raw in 1.2.0 where they've already solved this problem.

**Comment by bricelam** [comment]
We may need to adopt a similar packaging strategy as [discussed above](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/148#issuecomment-223383478). SQLitePCL.raw has a ton of packaging variations, but I think we can simplify it to two:
- SQLitePCLRaw.core--No native library included. The user picks sqlite3, sqlcipher, winsqlite3, etc.
- SQLitePCLRaw.bundle_green--Just works&#8482; everywhere

One thing I don't like about SQLitePCL.raw is that the user has to add something to their app's startup:
```C#
// For specific providers...
SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_winsqlite3());

// For bundles...
SQLitePCL.Batteries.Init();
```

We need to investigate if we can call this automatically or perhaps provider sugar APIs over...

**Comment by ericsink** [comment]
If you want to spare the user the Init call:

You should be able to just dep on bundle_whatever and call Batteries.Init()
in a static constructor.  That's what most other libs are doing.

If your lib is PCL-ish, the bundle also needs to get added to the platform
project so the proper version of Batteries.Init() gets used.  This is
usually done by telling the dev to add your lib to both their PCL-ish lib
and their platform project, which you made already need them to do for
other reasons.

I hope this makes sense.  I'm happy to help figure out the right way to go
on this.

--
E

**Comment by bricelam** [comment]
If our lib calls Batteries.Init(), but the user app doesn't use a bundle (because they pull in the version of our package that just depends on SQLitePCLRaw.core) will it throw or no-op?

I think our main goal is to make the default experience just work without having to initialize anything before opening a connection. If they have to do something special to use sqlcipher or winsqilte3, that's fine.

**Comment by bricelam** [comment]
(Or would we not be able call Batteries.Init() if we don't reference a bundle?)

**Comment by ericsink** [comment]
Batteries.Init() is only present in the bundles, so you would have to dependon/reference it.

**Comment by ericsink** [comment]
> I think our main goal is to make the default experience just work without having to initialize anything before opening a connection. 

Then you probably want to depend on bundle_whatever and call Batteries.Init().  As long as your pkg is added to a platform project, this should work.

And I'm assuming that if you do this, you don't actually a separate version of the pkg that depends on just SQLitePCLRaw.core?  Is that intended to support cases where somebody wants to swap out one bundle type for another?

**Comment by bricelam** [comment]
> Is that intended to support cases where somebody wants to swap out one bundle type for another?
Yes, eg. they want to use winsqlite3 or sqlcipher

**Comment by ericsink** [comment]
The problem with multiple versions of your package is that it forces other library packages to decide which one to take a dependency on.

And this is more or less how SQLitePCL.raw ended up in its current situation.  I used to have separate packages for regular-sqlite and system-sqlite and sqlcipher and so on.  But then library X would use SQLitePCL.raw, and it would have to choose just one of them, and then the users of X would ask me how to swap for a different one.

In your case, if I understand correctly, this problem would happen immediately.  Which Microsoft.Data.Sqlite nupkg does EF want to use?  Is it going to have two flavors of the package too?

FWIW, in part to create yet another option for dealing with these kinds of problems, I added Batteries_V2.Init().  It works the same way as Batteries.Init(), except that it lives in a different assembly name.

The assembly name for regular Batteries.Init() is different for every bundle pkg.

But Batteries_V2.Init() always lives in an assembly with the same name, regardless of the bundle.

This allows substituting one bundle type for another.  The full explanation of how to do this can be less-than-intuitive, so I'm not saying this is an ideal solution.  But it's another possibility.  I have some users who really, really hate initialization calls.

BTW if I had realized earlier, I would have done the name of the batteries assembly this way from the beginning.  But changing the name of that assembly would be a breaking change, so I just added a second version of the Init call.  There should be no downside for someone to use the V2 version, whether they want the ability to substitute bundles across types or not.

**Comment by bricelam** [comment]
> I have some users who really, really hate initialization calls.

I think we're one of 'em. 😄

I suspect the best way to call `Batteries_V2.Init()` is using reflection? This would allow users to continue using a provider directly if they wanted...

```C#
Assembly batteriesAssembly = null;
try
{
    batteriesAssembly = Assembly.Load(
        new AssemblyName(
            "SQLitePCLRaw.batteries_v2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8226ea5df37bcae9"));
}
catch
{
}

var batteriesType = batteriesAssembly?.GetType("SQLitePCL.Batteries_V2");
var initMethod = batteriesType?.GetTypeInfo().GetMethod("Init");

initMethod?.Invoke(null, null);
```

I think we'll continue with the plan of having convenient metapackages for a good default experience.

![image](https://cloud.githubusercontent.com/assets/1226749/21868618/7e69d34e-d808-11e6-8470-2f50564c8209.png)

Any libraries building on top of `Microsoft.Data.Sqlite` can choose what strategy they'd like to use: on version that depends directly on `Microsoft.Data.Sqlite.NoNative` (and the app brings in a bundle/provider) or have two versions.

**Comment by ericsink** [comment]
Re: Assembly.Load() -- IIRC, this is one of those things that doesn't work well on iOS.  And since UWP is also AOT, I would wonder if it might not work well there either?

**Comment by ericsink** [comment]
Re: the two-package solution:

Over the last few months, it looks like using bait-and-switch and calling Batteries_V2.Init() from a portable assembly is working out pretty well for other projects.  The benefit of that solution is that you spare your users the init call, but you can stay with one package instead of two.

That said, I'm just trying to inform, not argue.  :-)

**Comment by bricelam** [comment]
Reflection will work on .NET Native, but we'll certainly have to test it on Xamarin.iOS.

Personally, I'm all for a one-package, auto-initializing solution if we can get it to display a nice message during build or run-time when a bundle isn't installed. Something like: `A SQLitePCL.raw bundle isn't installed. Please install one (e.g. using the SQLitePCLRaw.bundle_green NuGet package) and try again.`

But we'll re-discuss as a team.

**Comment by ericsink** [comment]
Minor quibble, just in case it matters:  I wasn't broadly saying that reflection doesn't work on Xamarin.iOS.  It does.  I was specifically saying that I'm not sure Assembly.Load() works in all cases on Xamarin.iOS.

**Comment by ericsink** [comment]
"if we can get it to display a nice message"

I am happy to improve the error message and/or provide a way for packages to customize it.

**Comment by bricelam** [comment]
After #320, using SQLCipher is as easy as:
```ps1
Install-Package Microsoft.Data.Sqlite.Core
Install-Package SQLitePCLRaw.bundle_sqlcipher
```
