### ISSUE TITLE
Run tests on x64 during build

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#151]
KoreBuild currently only runs tests on x86, but since we have native interop, it would be good to run them on x64 too.

**Comment by dougbu** [comment]
This feature exists in KoreBuild already. Just use the `--test-dnxcore` "target" before whatever target you really want in any repo e.g. `./build.sh --quiet --test-dnxcore verify`. Add that to your Travis configuration and it'll be auto-magic.

**Comment by bricelam** [comment]
Hmm, it [looks like](https://github.com/aspnet/Universe/blob/dev/build/_k-test.shade#L63-L66) that only forces coreclr to run on LInux. (Nothing to do with with running on x64 architectures.)

**Comment by dougbu** [comment]
Sorry I misread the issue.

I don't own KoreBuild but would support you adding more branches to `_k-test.shade` and a config-changing target in `_k-standard-goals.shade` e.g. `--test-x64`. Don't think testing w/ x64 as the default makes sense, especially for regular local builds.

**Comment by CADbloke** [comment]
x-posted from  [an issue on the EF7 repo](https://github.com/aspnet/EntityFramework/issues/4254#issuecomment-169950907)...
>One thing I noticed with the Sqlite v 3.10.0 [download from sqlite.org](https://www.sqlite.org/download.html) - I compared the [x64](https://www.sqlite.org/2016/sqlite-dll-win64-x64-3100000.zip) & [x86](https://www.sqlite.org/2016/sqlite-dll-win32-x86-3100000.zip) `sqlite3.def` files and there were some differences.
x64 has `sqlite3_data_directory`, `sqlite3_fts5_may_be_corrupt`, `sqlite3_temp_directory` & `sqlite3_version` that the x86 version doesn't have. Nothing was missing from x64, I don't know if any of this is significant or not. 

Thought it might be of interest given the nature of this issue.
