### ISSUE TITLE
Unit tests fail on CoreCLR on Linux

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Microsoft.Data.Sqlite#155]
Most tests fail like shown below. libsqlite3 is installed on the machine. Tests pass on Mono.

This is related to https://github.com/aspnet/Universe/issues/304.

    Assert.Throws() Failure
          Expected: typeof(Microsoft.Data.Sqlite.SqliteException)
          Actual:   typeof(System.DllNotFoundException): Unable to load DLL 'sqlite3': The specified module could not be found.
           (Exception from HRESULT: 0x8007007E)
          Stack Trace:
               at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
               at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
               at Microsoft.Data.Sqlite.SqliteConnection.Open()
               at Microsoft.Data.Sqlite.SqliteConnectionTest.<>c__DisplayClass9_0.<Open_throws_when_error>b__0()
          System.DllNotFoundException : Unable to load DLL 'sqlite3': The specified module could not be found.
           (Exception from HRESULT: 0x8007007E)

**Comment by natemcmaster** [comment]
Is libsqlite3-dev installed?

**Comment by cesarbs** [comment]
After installing that package, I don't see the failures anymore.

But shouldn't the tests work having only the binaries installed? I don't see the same failures when running on Mono.

**Comment by cesarbs** [comment]
This affects https://github.com/aspnet/Universe/issues/304.

**Comment by natemcmaster** [comment]
The underlying issue is still being discussed. (See https://github.com/dotnet/coreclr/issues/930). [Mono's p/invoke interop](http://www.mono-project.com/docs/advanced/pinvoke/) works differently than CoreCLR. We can't compensate for this at the package level. Hence the requirement to [use libsqlite3-dev on ubuntu](https://github.com/aspnet/Microsoft.Data.Sqlite#ubuntu).

**Comment by muratg** [comment]
Should we manually install this on all agents until this is figured out?

**Comment by natemcmaster** [comment]
@muratg Yes. 

To be clear though, I believe the real problem is a quirk in Ubuntu's packaging of libsqlite3 vs libsqlite3-dev, not CoreCLR itself. Other version of Debian linux don't appear to have this issue.

**Comment by muratg** [comment]
@cesarbs Can we add this to the agents?

@victorhurdugaci FYI.  Do we have "steps to bring up a new agent" somewhere?  If so, this should probably go in as well.

**Comment by rowanmiller** [comment]
@natemcmaster is there anything we need to do on our side for this?

**Comment by natemcmaster** [comment]
@rowanmiller No, the issue is external to this project. Unless DNX adds something like https://github.com/aspnet/dnvm/issues/474 all we can do is explicitly list our native dependencies as we currently do in our README.

**Comment by cesarbs** [comment]
@davidfowl
