### ISSUE TITLE
Cleanup pass on TFMs and #ifs

### ISSUE THREAD

**Issue by divega** [aspnet/Microsoft.Data.Sqlite#158]
After DNX TFMs were removed to unblock the CI we are left with a few strange things such as ```#if NET451 || NET451``` :smile: 

Getting rid of those should be easy it seems we should do a general clean up pass to if anything else can go.

**Comment by natemcmaster** [comment]
Fixed with https://github.com/aspnet/Microsoft.Data.Sqlite/commit/1aaf4edf71dc677909d43fadd1f5fd83b4d2e86b
