### ISSUE TITLE
Concurrency issues on OSX 10.11.1

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#165]
The version of SQLite installed on OSX 10.11.1 (sqlite 3.8.10.2 2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4) causes the test failure included below.

```
Microsoft.Data.Sqlite.SqliteConcurrencyTest.Prevents_timeout_exception [FAIL]
      System.AggregateException : One or more errors occurred.
      ---- Microsoft.Data.Sqlite.SqliteException : SQLite Error 5: 'database is locked'
```

This does not appear on OSX 10.10, or local builds of sqlite 3.8.10.

**Comment by rowanmiller** [comment]
@natemcmaster how does resolution work... is it easy to use a different version that the one that is included?

**Comment by natemcmaster** [comment]
Resolution on OSX uses the [default behavior of `dlopen`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/dlopen.3.html) which means it will search `$LD_LIBRARY_PATH, $DYLD_LIBRARY_PATH, current working
     directory, $DYLD_FALLBACK_LIBRARY_PATH.` Using a different version means either changing the env variables (which is a bad idea) or symlinking to in the cwd a version of `sqlite3.dylib` that doesn't have this bug (easier, but also a little tricky for average users.)

**Comment by natemcmaster** [comment]
Investigated more. This bug is due to a deficiency in the version of libsqlite3 bundled in OSX, and we can't avoid these errors. To workaround, users can use the following steps:

1. Install homebrew http://brew.sh/
2. `brew install sqlite3`
3. When executing an app, set the `LD_LIBRARY_PATH` environment variable to include the homebrew library.
```
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Cellar/sqlite3/3.10.0/lib/
$ dnx run
```
