### ISSUE TITLE
Online backup

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#17]
See [Online Backup API](http://sqlite.org/c3ref/backup_finish.html).

**Comment by zsims** [comment]
I'm interested in looking at this in the near future, do you have any preferences for how the API would be exposed?

I'm thinking to extend `SqliteConnection` with:
```
void Backup(string sourceDatabaseName, SqliteConnection destination, string dedtinationDatabaseName);
```

Which would do the backup all pages. Progress or incremental page backups could come later if required. Thoughts?

**Comment by ErikEJ** [comment]
System.Data.SQLite already has BackupDatabase https://github.com/OpenDataSpace/System.Data.SQLite/blob/master/System.Data.SQLite/SQLiteConnection.cs#L792 (not official source code!)

**Comment by bricelam** [comment]
👍 In general, we've tried to keep our APIs compatible with System.Data.SQLite unless there is a compelling reason to change them

**Comment by bricelam** [comment]
lol well, maybe that statement isn't true... but it makes sense to do here. And we did it for `EnableExtensions`.

**Comment by HardRock88** [comment]
Any chance to get this feature working any time soon ?

**Comment by bricelam** [comment]
It would make a great contribution! Unfortunately, our team is currently focused on higher priority items and won't have the bandwidth to do this any time soon.

**Comment by AlexanderTaeschner** [comment]
System.Data.SQLite has the following interface:
```csharp
public void BackupDatabase( 
    SQLiteConnection destination, 
    string destinationName, 
    string sourceName, 
    int pages, 
    SQLiteBackupCallback callback, 
    int retryMilliseconds 
)
```
I have two questions:
- Do we need the callback hook (at the moment I see no real use case for it)?
- Should we add default values (eg. sourceName = "main", pages = -1 (full backup))?

**Comment by bricelam** [comment]
Hmm, that's pretty far removed from the native API. I'd like to investigate some alternative designs. Prehaps using some modern .NET async patterns...

**Comment by AlexanderTaeschner** [comment]
I would propose to add three overloads to SQLiteConnection:
```csharp
public virtual void BackupDatabase(SqliteConnection destination)
    => BackupDatabase(destination, "main", "main");
public virtual void BackupDatabase(SqliteConnection destination, string destinationName, string sourceName)
    => BackupDatabase(destination, destinationName, sourceName, -1);
public virtual void BackupDatabase(SqliteConnection destination, string destinationName, string sourceName, int pages)
```
This would enable the use of the complete API without any additions and the simplest form would be enough to do a complete backup to an open connection.
A sample implementation can be found here: https://github.com/AlexanderTaeschner/Microsoft.Data.Sqlite/tree/Issue17

The idea of an async method would be appealing, but the native backup API is completely synchronous.

**Comment by bricelam** [comment]
> the native backup API is completely synchronous

There may be an opportunity to `Task.Yield()` between `sqlite3_backup_step()` calls and `Task.Delay(150)` after `SQLITE_BUSY` or ` SQLITE_LOCKED`. Cancellation between steps would also be nice.

**Comment by bricelam** [comment]
The sync APIs should also retry (with a timeout) on `SQLITE_BUSY` or ` SQLITE_LOCKED`.

**Comment by bricelam** [comment]
I don't think we need `pages`. It's really just there to allow cancellation.

**Comment by bricelam** [comment]
Here's my pseudo code:
``` csharp
var backup = sqlite3_backup_init();
try
{
    while (true)
    {
        cancellationToken.ThrowIfCancellationRequested();
        
        var rc = sqlite3_backup_step(backup, 1);
        if (rc == SQLITE_DONE)
        {
            break;
        }
        if (rc == SQLITE_BUSY || SQLITE_LOCKED
            && ellapsedTime > timeout)
        {
            await Task.Delay(150);
        }
        else if (rc != SQLITE_OK)
        {
            SqliteException.ThrowExceptionForRC(rc);
        }
        
        await Task.Yield();
    }
}
finally
{
    sqlite3_backup_finish(backup);
}
```

**Comment by bricelam** [comment]
The sync version is the same but with `Thread.Sleep()` instead.

**Comment by AlexanderTaeschner** [comment]
Your proposal would make the sleeps async, but the heavy lifting (disk IO) is still done via a synchronous method (sqlite3_backup_step).
Why do you think its better to do the backup page by page instead of calling backup_step once with a negative number to make the backup in one complete sweep (and by this locking once for a longer time instead of trying to get a lock for each page)?

**Comment by bricelam** [comment]
True. My goal was mainly to yield during the backup. I don't have enough context on how this API gets used in the real world. Is to goal to back up the database in the background while the application is in use (e.g. processing web requests)? This might help achieve that goal.

I'm fine starting with the fully synchronous API that does it all at once and throws `SQLITE_BUSY` if you try and start it while another transaction is open. If we get feedback, we can always add the retries and yields later.

**Comment by bricelam** [comment]
Also, will most applications want to report on progress? How long does it typically take?

**Comment by bricelam** [comment]
(Again, that API can be added later)

**Comment by AlexanderTaeschner** [comment]
@bricelam How should we proceed? Should I file a PR with the three proposed functions?

**Comment by bricelam** [comment]
Let's start with just these two:

``` csharp
public virtual void BackupDatabase(SqliteConnection destination)
    => BackupDatabase(destination, "main", "main");
public virtual void BackupDatabase(SqliteConnection destination, string destinationName, string sourceName)
```

Specifying `pages` is useless if you can't call `sqlite3_backup_step`.
