### ISSUE TITLE
SQLite Error 19: 'FOREIGN KEY constraint failed'

### ISSUE THREAD

**Issue by leak** [aspnet/Microsoft.Data.Sqlite#174]
The error message "SQLite Error 19: 'FOREIGN KEY constraint failed'" does not bear any useful information other than something is wrong, providing a poor debug experience.

I would expect to see some more info which constraint failed or at least a table or entity name being involved.

Didn't dig deeper into this but the underlying driver should provide more information:

"Additional information about the failed constraint can be found by consulting the accompanying error message (returned via sqlite3_errmsg() or sqlite3_errmsg16()) or by looking at the extended error code."
https://www.sqlite.org/rescode.html

**Comment by bricelam** [comment]
IMHO, most SQLite errors don't bare any useful information... I'm afraid there's not much we can do about it in our codebase since the messages come from the native SQLite engine/driver.

**Comment by bricelam** [comment]
I suspect they're intentionally vague to try and protect information about you schema and data.

**Comment by ivanromakh** [comment]
I see such error when I didn`t set foregin key. I think they are required by default.
