### ISSUE TITLE
Support encyption

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Microsoft.Data.Sqlite#184]
This is to track the high level scenario of encryption. We've speculated that it may already be possible with a custom build of SQLite or using extensions - but we've not actually tested this or provided any guidance.

**Comment by bricelam** [comment]
It looks like [SQLCipher](https://github.com/sqlcipher/sqlcipher/blob/master/README.md) can be used by replacing `sqlite3.dll` and issuing `PRAGMA` statements.

**Comment by bricelam** [comment]
The same is true for [SEE](http://www.sqlite.org/see).

**Comment by bricelam** [comment]
This works. I've posted [Encryption in Microsoft.Data.Sqlite](http://www.bricelam.net/2016/06/13/sqlite-encryption.html) on my blog.

I don't think there's any additional work to do here. We could consider adding `SetPassword` and `ChangePassword` methods to `SqliteConnection` and allowing `Password` and `HexPassword` to be specified in the connection string, but these APIs would only work if you've included a copy of the native `sqlite3` library that supports them.

**Comment by bricelam** [comment]
Also, #148 will improve the overall experience of using encryption.

**Comment by rowanmiller** [comment]
Any thoughts on how possible this is when using EF? Guessing you have to supply your own connection externally?

**Comment by bricelam** [comment]
@rowanmiller Yes, until we have an OnConnectionOpened hook, that's the easiest way.

**Comment by natemcmaster** [comment]
>  an OnConnectionOpened hook

To be added to EF in https://github.com/aspnet/EntityFramework/issues/626? Or do you mean adding a hook in the ADO layer? I assume you mean EF as I don't know of another ADO implementations with this kind of hook.

**Comment by bricelam** [comment]
An EF hook, yes. ADO.NET already has a connection state changed event.

**Comment by rowanmiller** [comment]
Yeah in https://github.com/aspnet/EntityFramework/issues/5024 we discussed the idea of having some sort of "connection preamble" as there are lots of database provider specific features that would benefit from this (SQLite PRAGMA, SQL Server sharding, etc.).

**Comment by rowanmiller** [comment]
Closing this out, will add a page to the docs that references blog post by @bricelam and shows how to use it with EF.
