### ISSUE TITLE
Windows 8 support?

### ISSUE THREAD

**Issue by chinhodado** [aspnet/Microsoft.Data.Sqlite#185]
How ready is this to be used? Particularly can it be used in Windows RT apps? 

I tried to install the package at https://www.nuget.org/packages/Microsoft.Data.SQLite/ to my Windows 8 app project and the package failed to be installed, saying that no compatible target platform is found in the package.

**Comment by bricelam** [comment]
We currently support Windows 10 Universal Apps. I suspect with a few packaging changes we could easily support Windows 8.

But you are aware everyone gets a free upgrade, right? :trollface:

**Comment by chinhodado** [comment]
Unfortunately my environment is restricted to Windows 8 at the moment. I would love to see Windows 8 support added for this.

**Comment by bricelam** [comment]
lol, I was joking about upgrading.

It looks like `System.Data.Common` (one of our dependencies) will need to support it first. Would you mind filing a bug on [dotnet/corefx](http://github.com/dotnet/corefx) to add Windows 8 support to that package?

**Comment by bricelam** [comment]
I looked into this again. `System.Data.Common` now supports Windows 8.1. The one thing holding us up now is [our use of an environment variable](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/1d4cee7d6f12c19b4c601f2678fb2a41bd6874f1/src/Microsoft.Data.Sqlite/SqliteConnection.cs#L210).

**Comment by bricelam** [comment]
The unfinished changes are in [bricelam:win81](https://github.com/aspnet/Microsoft.Data.Sqlite/compare/dev...bricelam:win81).

**Comment by bricelam** [comment]
@TheBlueSky, you may find this useful... It's currently available on the [nightly feed](https://dotnet.myget.org/gallery/aspnetcore-ci-dev).
