### ISSUE TITLE
Relative path in connection string pointing to different locations

### ISSUE THREAD

**Issue by leak** [aspnet/Microsoft.Data.Sqlite#188]
I'm using a two project setup as described here https://github.com/aspnet/Microsoft.Data.Sqlite/issues/55#issuecomment-132480553

config.json
````
    "Data": {
        "DefaultConnection": {
            "ConnectionString": "Filename=database.db"
        }
    },
````

Startup.cs
````
[...]
            var builder = new ConfigurationBuilder()
                 .SetBasePath(appEnv.ApplicationBasePath)
                 .AddJsonFile("config.json");
[...]

            services.AddEntityFramework()
                .AddSqlite()
                .AddDbContext<MyAppDbContext>(
                    options => options.UseSqlite(_configuration["Data:DefaultConnection:ConnectionString"]));

[...]
````
I have a custom command defined in the Program.cs allowing me to reset and reseed the database.

````
    private static void ResetDatabase()
    {
        var dbContext = _services.GetService<MyAppDbContext>();

        dbContext.Database.EnsureDeleted();

        dbContext.Database.EnsureCreated();
        
        Console.WriteLine("Database reset successful.");
    }
````

When I run my application from IIS Express the database gets created in :
`D:\MyApp\src\MyApp\wwwroot`

When I run the custom command it appears in:
`D:\MyApp\src\MyApp\`

**Comment by bricelam** [comment]
@Tratcher Any thoughts? We root relative paths using `PlatformServices.Default.Application.ApplicationBasePath`.

**Comment by Tratcher** [comment]
Sounds like it's being resolved relative to CurrentDirectory. IIS/Express always points at wwwroot. Does EF resolve the relative path, or is it the sqllite SDK?

**Comment by bricelam** [comment]
sqlite3.dll (native) resolves them using current directory, so we (Microsoft.Data.Sqlite) fix them up before invoking the native code. My latest PR #192 may have fixed this. I'll try to repro on the latest bits. I just wanted to make sure it wasn't an expected Hosting behavior.

**Comment by bricelam** [comment]
Confirmed. My latest PR #192 will fix this.

**Comment by leak** [comment]
Great, thanks!
