### ISSUE TITLE
Consider publishing the symbols package

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#189]
Our build produces a package with debug symbols and source embedded, but we don't publish to nuget. 

**Workaround:** users can still build locally. The package is created in `<project>/artifacts/Microsoft.Data.Sqlite.<version>.symbols.nupkg`

**Comment by natemcmaster** [comment]
@pranavkm do we already publish symbols for our nuget packages?

**Comment by pranavkm** [comment]
Nope.
