### ISSUE TITLE
InvalidOperationException  from AdjustForRelativeDirectory

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Microsoft.Data.Sqlite#190]
**Copied from https://github.com/aspnet/EntityFramework/issues/3935. Per the comments, this is an exception from our reflection code in `Microsoft.Data.Sqlite.dll!Microsoft.Data.Sqlite.SqliteConnection.AdjustForRelativeDirectory(string path)`.**

<hr />

I have an issue similar to #2184. Context with simple model fails on any usage. On Database.Migrate(), trying to use DbSet, etc.

# Model

    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public bool Done { get; set; }
    }

    public class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public bool Done { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Book> Books { get; set; }
        public DbSet<Movie> Movies { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Filename=db.db");
        }
    }

# App.xaml.cs

It's almost empty!

    public sealed partial class App
    {
        public App()
        {
            InitializeComponent();

            using (var db = new Context())
            {
                db.Database.Migrate(); // exception occures here
            }
        }
    }

# Error

> System.InvalidOperationException occurred
  HResult=-2146233079
  Message=The API 'System.Reflection.MemberInfo.get_MetadataToken()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.
  Source=mscorlib
  StackTrace:
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by bricelam** [comment]
@llvk I'm not able to reproduce this error on RC1 using Visual Studio 2015 Update 1. Can you try again using the latest [Windows developer tools](https://dev.windows.com/en-us/downloads)?

**Comment by llvk** [comment]
@bricelam Seems like problem appears in app with Caliburn.Micro 3.0.0-beta1, I can not reproduce this in a clean project.

So the steps:
1. empty app
2. simple DbContext // works
3. use Caliburn.Micro CaliburnApplication // error occured

I don't see the relations between Microsoft.Data.Entity and Caliburn.Micro but this is the way to reproduce.

**Comment by ErikEJ** [comment]
@llvk Maybe you should try beta 2 on a clean project? https://www.nuget.org/packages/Caliburn.Micro/3.0.0-beta2 
https://github.com/Caliburn-Micro/Caliburn.Micro/commits/3.0.0

**Comment by danielgary** [comment]
I'm having this same issue on a PrismUnityApplication.

**Comment by danielgary** [comment]
So it looks like you can just try/catch around this and it works.  Not ideal :frowning:

**Comment by natemcmaster** [comment]
I can confirm the issue @bircelam. It appears to be an issue in how we dynamically try to resolve Windows.Storage.ApplicationData.

**Comment by bricelam** [comment]
@davidfowl @anurse Any way to reference `*.winmd` files from `project.json` when targeting `uap10.0`?

**Comment by MMalikKhan** [comment]
@bricelam @natemcmaster  i am stil having the above issue when i call migrate async or OpenConnectionAsync this has been reported recently on StackOverFlow [here](http://stackoverflow.com/questions/37061249/invalidoperationexception-get-metadatatoken-cannot-be-used-on-the-current-pla) can you please let me know in which build it is fixed? i am still on RC1 ? and latest VS 2015 update 2 , tooling 1.3.2, I usually dont get this, i have a app where multiple users can login and the db file is being created in specific folder for each user login. i have not seen this issue earlier. Any idea what might be causing this issue?

**Comment by natemcmaster** [comment]
@MMalikKhan this was fixed in in the "1.0.0-rc2-final" release https://www.nuget.org/packages/Microsoft.Data.SQLite/1.0.0-rc2-final
