### ISSUE TITLE
Support reading Guid values from TEXT columns

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Microsoft.Data.Sqlite#191]
Copied from https://github.com/aspnet/EntityFramework/issues/3950

Currently we assume GUID values are stored in BLOB columns, so you get an exception when we try to parse the value when it is stored as a STRING.

**Comment by RonFrick** [comment]
Thanks Rowan! Is this something that I should jump on with a pull request or will you be able to knock it out fairly quickly?

**Comment by rowanmiller** [comment]
Pull request would be great - we are swamped at the moment.

**Comment by RonFrick** [comment]
First pull request created. :) Although I think I might have picked the wrong stream to pull from, can we change it on the fly before I start working?

**Comment by ErikEJ** [comment]
Think you must start over. First fork, clone, branch

**Comment by bricelam** [comment]
My thoughts on this: If the bytes returned by `GetBlob` are larger than expected, convert them to text and try creating a `Guid` from them.

**Comment by RonFrick** [comment]
Anyone had time to look at this?

**Comment by RonFrick** [comment]
I have it working. I took your suggestion Brice and converted it to text to make sure the length was correct. Not sure if I did this correctly but I checked in my changes here. 

https://github.com/aspnet/Microsoft.Data.Sqlite/compare/dev...RonFrick:ron?expand=1

**Comment by ErikEJ** [comment]
I think you should call GetBlob first, like @bricelam suggests.

**Comment by RonFrick** [comment]
Here? public override Guid GetGuid(int ordinal) => new Guid(GetGuidBlob(ordinal));

This throws an exception…

public override Guid GetGuid(int ordinal) => new Guid(GetBlob(ordinal));

**Comment by RonFrick** [comment]
Is it just the naming that is a problem? We could still call it GetBlob and use an overload?

public override Guid GetGuid(int ordinal) => new Guid(GetBlob(ordinal,true));

private string GetBlob(int ordinal,bool isGuid)
        {
            if (IsDBNull(ordinal))
            {
                throw new InvalidCastException();
            }

            string blob = System.Text.Encoding.UTF8.GetString(NativeMethods.sqlite3_column_blob(_stmt, ordinal));
            if (isGuid && blob.Length > 36)
                return blob.Substring(0, 36);
            else
                return blob;
        }

**Comment by RonFrick** [comment]
This also works but it is not safe?

 public override Guid GetGuid(int ordinal) => new Guid(GetBlob(ordinal).ToString().Substring(0,36));

**Comment by roklenardic** [comment]
I am using EntityFrameworkCore1.0.0 and this seems it's still not working. Any update on it?

**Comment by rowanmiller** [comment]
This is on our backlog to enable in a future release. Currently, our SQLite provider requires that GUIDs be stored in binary. The workaround would be to map the column to a string property (which can be private) and then have an unmapped property that does the conversion to/from a GUID.

**Comment by RonFrick** [comment]
Until this is supported out of the box, I have a working version of Microsoft.Data.Sqlite that will allow you to use Guids as strings with EF. Let me know if you want it and I can post it somewhere for you.

**Comment by roklenardic** [comment]
@RonFrick I would love to give it a try, please let me know where I can download it? Thanks!
