### ISSUE TITLE
Configure winsqlite3 from connection string

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#194]
Ideally the setting (something like `UseWinsqlite3=True;`) could handle the "if windows 10 do this, else do that" for users so we wouldn't need different connection strings for Linux, Windows 7 and Windows 10.

This is an alternative to calling `SqliteEngine.UseWinSqlite3()`

**Comment by divega** [comment]
The way I understand this is working only makes it possible to choose the SQLite native assembly before you load it and once made loaded you cannot change it. 

The connection string on the other hand can easily be different per connection instance.
 
Don't you think then that the mismatch would make it confusing?

**Comment by natemcmaster** [comment]
> Don't you think then that the mismatch would make it confusing?

Could be, but they have different semantics. The SqliteEngine call currently means “Only use winsqlite3.dll”.
I’m suggesting we add a parameter that means “Use winsqlite3.dll when it exists otherwise use the packaged version”.

**Comment by rowanmiller** [comment]
We don't have any customer use cases where this would be wanted. If folks ask for it then we can reconsider in the future.
