### ISSUE TITLE
Extension loading test fails on OSX

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#196]
```
SqliteConnectionTest.EnableExtensions_works

System.EntryPointNotFoundException : Unable to find an entry point named 'sqlite3_enable_load_extension' in DLL 'sqlite3'.
```

OSX 10.10.5

**Comment by natemcmaster** [comment]
cc @bricelam it appears the version of `libsqlite3` on OSX 10.10.5 is compiled with `SQLITE_OMIT_LOAD_EXTENSION`. Can we add either (1) a runtime check of compiler options or (2) just skip this test on OSX 10.10?

**Comment by bricelam** [comment]
Ignore the test. Looking for `SQLITE_OMIT_LOAD_EXTENSION` in the test seems like overkill.
