### ISSUE TITLE
Infer ClrType from user-declared column type

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#202]
Example:
```sql
CREATE TABLE ceos ( Age INT, Salary BIGINT );
```

Calling `SqliteDataReader.GetValue()` will return `Int64` for both columns because we use `sqlite3_column_type`.

Instead, match the behavior in https://msdn.microsoft.com/en-us/library/yy6y35y8(v=vs.110).aspx. This would return `Int32` for "Age" and `Int64` for "Salary".

**Caveats:**
Column type in SQLite is arbitrary. => fallback to `sqlite3_column_type`

**Comment by bricelam** [comment]
This would reverse earlier design decisions we have made to never interpret column type names. Please bring to a design meeting so we can discuss ...again.

**Comment by natemcmaster** [comment]
Discussed with @bricelam. Based on previous choices in #68, we probably won't do this by default. 

For triage: let's consider adding simple mapping extensions.

**Comment by rowanmiller** [comment]
We don't have a compelling reason to spend time on this. If we find scenarios where it would be useful then we could implement it.
