### ISSUE TITLE
Reader.GetBytes is not supported yet, or will never be ? 

### ISSUE THREAD

**Issue by BeeDi** [aspnet/Microsoft.Data.Sqlite#206]
Hello, 
I am wondering if the GetBytes will be supported one day, or if there is another way to read a Byte array in the meantime ? 

Thanks

**Comment by natemcmaster** [comment]
GetBytes requires incremental blob I/O, which is a currently a backlog item (see https://github.com/aspnet/Microsoft.Data.Sqlite/issues/18.) You can workaround with `reader.GetFieldValue<byte[]>()`

Closing as a duplicate of #18

**Comment by BeeDi** [comment]
Thanks :)
