### ISSUE TITLE
Move to SQLitePCL.raw

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#21]
To get out of the business of handling the different ways of invoking native code on various platforms, we should consider building on top of ~~[Portable Class Library for SQLite](https://sqlitepcl.codeplex.com) or~~ [ericsink/SQLitePCL.raw](https://github.com/ericsink/SQLitePCL.raw).

**Comment by mstyura** [comment]
@ericsink, @bricelam, @rowanmiller I just want to vote for adding support of WP and Windows 8/10 portable profiles. As I understand from above discussion it is currently not possible to provide it for WP Silverlight execution environment. As I understand so far there are two libs for SQLite which provides ADO.NET like API. The official [System.Data.Sqlite](https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki) and [Mono.Data.Sqlite](https://github.com/mattleibow/Mono.Data.Sqlite). First one is for full featured .NET and is not suitable for mobile environment unfortunately :( . Second one is intended for mobiles, but it's not obvious how well this library is supported. So it would be nice to have [Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite/) which is suitable for mobile and universal apps also. Please, consider making it as much portable as possible.

Thanks in advance.

**Comment by bricelam** [comment]
We're primarily limited by the places System.Data or System.Data.Common are available.  Today, that means:
* .NET Framework/Mono
* .NET Core
    * Universal Windows Platform/.NET Native
    * DNX Core/Core CLR
* Xamarin
    * Xamarin.Android
    * Xamarin.iOS
    * Xamarin.iOS (Classic)

**Comment by mstyura** [comment]
@bricelam is the source code of [System.Data.Common](https://www.nuget.org/packages/System.Data.Common/) available in public? BTW, because the lack of `System.Data` in portable profiles, [Mono.Data.SQlite](https://github.com/mattleibow/Mono.Data.Sqlite/tree/master/System.Transactions) even introduces [System.Data.Portable](https://github.com/mattleibow/Mono.Data.Sqlite/tree/master/System.Data) and `System.Transactions.Portable` :|

**Comment by bricelam** [comment]
It's on [the list](https://github.com/dotnet/corefx-progress/blob/master/src-diff/README.md) to be open sourced as part of .NET Core.

**Comment by ericsink** [comment]
FWIW, SQLitePCL.raw 1.1.0 has been pushed to nuget.  This is the version that contains some fixes I did as a result of testing with Microsoft.Data.Sqlite and UWP/.NET Native.
