### ISSUE TITLE
SQLite version required

### ISSUE THREAD

**Issue by DavidKarlas** [aspnet/Microsoft.Data.Sqlite#215]
Readme file says "Requires SQLite >= 3.7.9" but I noticed that code is using sqlite3_close_v2 which was introduced in [3.7.14](http://www.sqlite.org/changes.html).

I hope you will work around this by using sqlite3_close if version is older then 3.7.14 and not by changing readme file since Android KitKat(36.1%) and Jelly Bean(25.7%) use 3.7.11.

Basically without this change Microsoft.Data.Sqlite is not usable on Android.

**Comment by DavidKarlas** [comment]
I just noticed that NuGet is out of sync with source code... I guess will need to wait for new NuGet or build from source...

**Comment by natemcmaster** [comment]
@DavidKarlas nuget.org will update when RC2 is released. Until then, you can get nightly builds from https://myget.org/gallery/aspnetvnext/
