### ISSUE TITLE
SQLite error 1: Table already exists

### ISSUE THREAD

**Issue by kscott5** [aspnet/Microsoft.Data.Sqlite#219]
I executed the same "dnx ef database update" command in both Windows and Centos. But the Centos throws the following error.

![capture](https://cloud.githubusercontent.com/assets/132991/12569221/79ea0a72-c392-11e5-8e61-44e6ecd6eb71.PNG)

Any suggestions as to what could be wrong or how to fix. (My Git Repo)[http://github.com/kscott5/GreenShelter]

**Comment by bricelam** [comment]
Is a call to `Database.EnsureCreated()` being made somewhere during initialization? (i.e. before Migrations are applied)

**Comment by kscott5** [comment]
@bricelam I'll check my code. I thought this method was design to create the database IIF it does not exist. Even if this occurs before or after the migration. Shouldn't they both check for the existence of tables and/or migration version? 

Help me understand the execution path of this method compared to Migration.

**Comment by bricelam** [comment]
`EnsureCreated` will bypass Migrations and create a database to store the current model. (It is typically used in testing.) `dnx ef database update` would then try to apply pending migrations, but the tables would already exist.

**Comment by kscott5** [comment]
I changed the ConnectionString located in the appsettings.json  and appsettings.development.json files 

from

"ConnectionString": "Data Source=.//production.db"
"ConnectionString": "Data Source=.//development.db"

to

"ConnectionString": "Data Source=./production.db"
"ConnectionString": "Data Source=./development.db"


I also had to dnu install EntityFramework.SQLIte.Design for both Windows and Linux (Centos) to eliminate and/or fix the Kestrel libuv entry point error.

No code changes was required. But based on my observation of how the commands works. It should matter.

Thanks anyway!!!

**Comment by NickSavin** [comment]
I have got the same issue in my .net application

![image](https://cloud.githubusercontent.com/assets/20172765/19111418/2a3b5d3a-8b08-11e6-8e5f-9df08f256e16.png)


Context is:

![image](https://cloud.githubusercontent.com/assets/20172765/19111403/080bda78-8b08-11e6-8541-d3fe6abbd58b.png)

**Comment by rowanmiller** [comment]
@NickSavin this issue is closed, so best to open a new one with the issue you are hitting. Did you already create the database without using migrations though (via `EnsureCreated()` or some other mechanism)? If you did, this is by design. Migrations must be used from initial creation and does not do any checking for existing schema etc.

**Comment by NickSavin** [comment]
@rowanmiller , Thanks for the answer!
I actually used EnsureCreated() for database creating first time. 

But, then I have used  "Add-Migration " and "Update-Database" for creating **another** database.
After changing my entity and executing  "Add-Migration " and "Update-Database" the issue repeats.

**Comment by rowanmiller** [comment]
@NickSavin please open a new issue and include a project or code to reproduce the issue. BTW you should open it in the Entity Framework repo https://github.com/aspnet/EntityFramework as this repo is for the SQLite System.Data.Common implementation.

**Comment by NickSavin** [comment]
Ok, big thanks for the answer
