### ISSUE TITLE
DbConnectionExtensions is defined as 'internal

### ISSUE THREAD

**Issue by ranjancse26** [aspnet/Microsoft.Data.Sqlite#226]

**Comment by ranjancse26** [comment]
May I know the reason why this class "DbConnectionExtensions" is defined as internal? How we can access the extension methods outside of the library assembly?

**Comment by bricelam** [comment]
They're just convenient sugar over to top of ADO.NET APIs that we use to write and test our provider. We don't want to be in the business of officially supporting or encouraging use of that code so we keep them as an internal implementation detail of our provider.

**Comment by bricelam** [comment]
If you want to use them in your own solution, feel free to add a copy of the *.cs file to your project.

**Comment by bricelam** [comment]
Oh, and you may want to update them to dispose the `DbCommand` objects as some ADO.NET providers require it.

**Comment by ranjancse26** [comment]
@bricelam Thanks for replying. Yes for now I have included and added few more extensions :) I see you have added those extensions as part of the Connection class. Now I got you. Yes, we generally do not execute a command directly through connection class. Hence we do not require as part of the official release.
