### ISSUE TITLE
allow to control thread safety

### ISSUE THREAD

**Issue by galich** [aspnet/Microsoft.Data.Sqlite#228]
based on http://sqlite.org/threadsafe.html SQLite can be instructed at compile, start and run time on what thread safety level to support.

Currently methods like ExecuteNonQueryAsync() in fact do no more than a blocking call to ExecuteNonQuery() and return result via Task.FromResult(). That blocks UI thread. It's ok to wrap database access code in Task.Run(), but that will require thread safety control.

Would be great to have support of SQLITE_OPEN_NOMUTEX and SQLITE_OPEN_FULLMUTEX

**Comment by bricelam** [comment]
The version of sqlite3.dll that we ship will use the default mode of serialized. If you want to change this during startup, you could call `sqlite3_config()` using P/Invoke. Given this, is there any reason to expose `SQLITE_OPEN_NOMUTEX` and `SQLITE_OPEN_FULLMUTEX`?

`System.Data.Sqlite.dll` also doesn't appear to expose it.

**Comment by galich** [comment]
@bricelam I guess you are right, I've tested it and default mode is serialized, which might just work. This issue came before I've realized that real trouble comes from PRAGMA temp_store_directory #229.

What do you think of adding such "one-time config" to SqliteEngine.UseWinSqlite3()?

**Comment by bricelam** [comment]
Yeah, if we expose any of the [configuration options](http://sqlite.org/c3ref/c_config_covering_index_scan.html), they should definitely hang off of `SqliteEngine`.

**Comment by rowanmiller** [comment]
Per discussion, we believe we are doing all the right things here already.
