### ISSUE TITLE
Do not use deprecated PRAGMA temp_store_directory

### ISSUE THREAD

**Issue by galich** [aspnet/Microsoft.Data.Sqlite#229]
[SqliteConnection.cs:187](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/SqliteConnection.cs#L187) uses `PRAGMA temp_store_directory` which is [deprecated from SQLite](http://sqlite.org/pragma.html#pragma_temp_store_directory)

Another potential issue with using that pragma is that it must be used only once and its not thread safe, quote from SQLite docs:

>  If the temp_store_directory is changed for one database connection while other database connections are open in the same process, then the behavior is undefined and probably undesirable...

> ...Changing the temp_store_directory setting is not threadsafe

It's causing crashes in our UWP project when SQLite is used from multiple threads.

**Comment by bricelam** [comment]
I wonder if the comments on `data_store_directory` apply to `temp_store_directory` as well...

> This facility is provided for WinRT which does not have an OS mechanism for reading or changing the current working directory. The use of this pragma in any other context is discouraged.

**Comment by galich** [comment]
I'm under impression that [SqliteConnection:166](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/SqliteConnection.cs#L166) always provide absolute path to sqlite3.dll and from `data_store_directory` it looks like it's supposed for relatively named database files

> ...windows operating-system interface backends use to determine where to store database files specified using a relative pathname.

**Comment by bricelam** [comment]
Ah, good catch. That PRAGMA can be removed.

I wonder what we can do about the temp directory. From [the sqlite3_open documentation](http://sqlite.org/c3ref/open.html):

> Note to Windows Runtime users: The temporary directory must be set prior to calling sqlite3_open() or sqlite3_open_v2(). Otherwise, various features that require the use of temporary files may fail.

Since it's global, I wonder if we could send the PRAGMA once (per AppDomain) against `:memory:` in a static constructor somewhere...

**Comment by bricelam** [comment]
I wish P/Invoke allowed setting global variables... :wink:

**Comment by bricelam** [comment]
@natemcmaster The work here is to...

1. Remove `PRAGMA data_store_directory`. It shouldn't be needed since we make paths absolute before calling `sqlite3_open_v2()`.
2. Ensure we set `sqlite3_temp_directory` in a way that's thread safe.

**Comment by natemcmaster** [comment]
> I wish P/Invoke allowed setting global variables

But since it doesn't, is the only way to do this via a GetProcAddress call? IIRC we used pragma statements deliberately because of this limitation of C#.

**Comment by bricelam** [comment]
Yep, I think I even tried going down that path, but couldn't get it working. I think it's fine to use the `PRAGMA`, we just need to make sure it doesn't fail when opening multiple connections on different threads at the same time.

**Comment by galich** [comment]
I guess the title should be changed to something like "use PRAGMA temp_store_directory only once prior to any other calls"
