### ISSUE TITLE
Cleanup NativeMethods initializer

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#240]
Cleanup how we execute code on the first time sqlite opens a connection. Cref https://github.com/aspnet/Microsoft.Data.Sqlite/pull/231#discussion_r56897668 and https://github.com/aspnet/Microsoft.Data.Sqlite/pull/231#discussion_r56897768

Try to set temp_store_directory with native calls. Try to get initialization to run inside the Load call.

**Comment by bricelam** [comment]
I tried to clean this up, but it resulted in something less readable than the current implementation. If it ain't broken, don't fix it.
