### ISSUE TITLE
Package does not work with latest dotnet-cli

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#241]
```
.NET Command Line Tools (1.0.0-beta-001897)

Product Information:
 Version:     1.0.0-beta-001897
 Commit Sha:  ca74a9b177

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

## Repro steps
1. `dotnet new`
1. Add this package to project json (see below). `dotnet restore`
2. `dotnet run`

```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": "1.0.0-rc2-23911",
    "Microsoft.Data.Sqlite": "1.0.0-*"
  },
  "frameworks": {
    "netstandard1.5": {
      "imports": [ "portable-net45+win8", "dnxcore50" ]
    }
  }
}
```

## Error

```
$ dotnet run
Compiling ConsoleApp for .NETStandard,Version=v1.5

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.5569106
 

Did not find fallback rids for package Microsoft.Data.Sqlite/1.0.0-rc2-20270 for the host rid osx.10.10-x64
Invalid .deps file
```

Repro project (including lock and deps file): 
[sqlitebug.zip](https://github.com/aspnet/Microsoft.Data.Sqlite/files/183272/sqlitebug.zip)

**Comment by bricelam** [comment]
Oh bummer. No more half-redistributing SQLite. It's all or nothing.

**Comment by davidfowl** [comment]
Not sure that's a SQLite bug. /cc @pakrym @anurse

**Comment by natemcmaster** [comment]
I think its this: https://github.com/dotnet/cli/issues/1905

**Comment by pakrym** [comment]
That's old corehost

**Comment by bricelam** [comment]
lol, you're saying `1718` is old? To be fair, it's newer than most of the packages on https://dotnet.myget.org/gallery/dotnet-cli

**Comment by pakrym** [comment]
My bad, there was a check that thrown this kind of error and it was removed, but other one was added into another place.

**Comment by schellap** [comment]
The above check is legitimate. `dotnet run` is using `corehost` and not the `dotnet` muxer. `corehost` has no idea of the framework.

**Comment by natemcmaster** [comment]
@schellap so there is no work to do for the pacakge? It is a corehost error?

**Comment by schellap** [comment]
CoreHost should not be used by CLI to activate an app. Your app is a portable app relying on the shared framework specified by runtimeconfig.json

```
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.0.0-rc2-23911"
    }
  }
}
```

corehost lives inside the CLI which has no idea about the shared framework `Microsoft.NetCore.App`

Instead, the root `dotnet` which resolves the shared fx underneath it, knows about this and is able to resolve it, hence it succeeds when you do `dotnet portableapp.dll`.

**Comment by natemcmaster** [comment]
@schellap so this is a duplicate of https://github.com/dotnet/cli/issues/1940 then? If so, we should add the blocking-partner label to it

**Comment by natemcmaster** [comment]
Appears to fixed with https://github.com/dotnet/cli/pull/1851. No changes needed to this repo.
