### ISSUE TITLE
Storing & Retrieving double.NaN causes NullReferenceException (Sqlite)

### ISSUE THREAD

**Issue by divega** [aspnet/Microsoft.Data.Sqlite#243]
_From @teo78 on April 8, 2016 6:44_

I'm testing EFCore RC1 using Sqlite, and encountered a problem when storing/retrieving double.NaN values.

I use TPH inheritance and when storing a double.NaN Sqlite stores this a Null value (see: http://system.data.sqlite.org/index.html/tktview?name=2b823bfe08). Then when loading that row EF Throws a NullReferenceException.

Could this be fixed in EFCore somehow so that Null values would be read in as double.NaN?
If not the only option as I see is to make sure that NaN is never stored which would be nasty solution.

Here is a minimal repro example:
```cs
class Program
    {
        static void Main(string[] args)
        {
            using (var db = new NumberContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();
                var number = new DoubleNumber() { Value = double.NaN };
                db.DoubleNumbers.Add(number);
                db.SaveChanges();
            }
            using (var db = new NumberContext())
            {
                // Throws NullReference exception on the following line due to NaN double value stored as Null in Sqlite
                var list = db.DoubleNumbers.ToList();
            }
        }
    }
    public class BaseNumber
    {
        public int Id { get; set; }
    }
    public class DoubleNumber : BaseNumber
    {
        public double Value { get; set; }
    }
    public class NumberContext : DbContext
    {
        public DbSet<BaseNumber> BaseNumbers { get; set; }
        public DbSet<DoubleNumber> DoubleNumbers { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite($"Filename=Test.db");
        }
    }
```

_Copied from original issue: aspnet/EntityFramework#5011_

**Comment by natemcmaster** [comment]
Confirmed bug. This reproduces in RC2. What should Microsoft.Data.Sqlite store for `double.NaN`? Right now it stores DBNull. If this is the correct behavior, then the actually issue is with EF not checking for IsDBNull.

**Comment by divega** [comment]
`Double` is a value type, so unless the type of the property is `double?` EF won't expect a `DBNull` to come out the column. Unless there is another out-of-band way we can serialize `double.NaN` to the column we may need to throw when trying to store it. Curious, how does this work with SQL Server?

**Comment by divega** [comment]
Or it may be possible to special case `decimal` to check for `DBNull` in the value readers for SQLlite,  but that would make it ambiguous what `DBNull` represents for a `double? `. Maybe that doesn't matter too much?

**Comment by bricelam** [comment]
We could store the string `NaN` and handle it in the ADO.NET layer. We probably need to do something similar for `NegativeInfinity` and `PositiveInfinity`.

**Comment by natemcmaster** [comment]
What about throwing instead? SqlClient throws this:
```
System.Data.SqlClient.SqlException: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 4 ("@p1"): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.
```

**Comment by bricelam** [comment]
I'm fine with throwing.

**Comment by divega** [comment]
I assume that exception is thrown when trying to save a `double.NaN`?

**Comment by divega** [comment]
Then, yes, I think it is ok to throw.

**Comment by natemcmaster** [comment]
Added pr #254 to throw when float.NaN or double.NaN is used as a parameter value.

**Comment by milasch** [comment]
What if one does want to save a double.NaN?

**Comment by bricelam** [comment]
@milasch, you could consider converting it to a string before storing it, or add an additional flag in the database.

**Comment by milasch** [comment]
@bricelam I guess there are no plans then to support it directly without the need to use a workaround like that. Wouldn't that be unfriendly to the user?

**Comment by bricelam** [comment]
I don't think there is a good way to handle this in the ADO.NET layer that wouldn't lead to other, more subtle problems later. Throwing early and letting the application decide on a strategy for handling `NaN` is, in my opinion, the friendliest thing we can do.
