### ISSUE TITLE
Support for nested transactions

### ISSUE THREAD

**Issue by Skrypt** [aspnet/Microsoft.Data.Sqlite#247]
Do you plan supporting nested transactions eventually ?

**Comment by natemcmaster** [comment]
@Skrypt I assume you mean adding API to support SAVEPOINT and RELEASE?

> Transactions created using BEGIN...COMMIT do not nest. For nested transactions, use the SAVEPOINT and RELEASE commands. https://www.sqlite.org/lang_transaction.html

Nested transactions could already be done by executing SqliteCommand with CommandText set to Savepoint/release.

The question we should consider is whether SqliteTransaction could/should handle this automatically. At the moment, the current behavior of SqliteConnection only allows one SqliteTransaction. Opening a second while one is already throws.

**Comment by Skrypt** [comment]
Exactly

**Comment by rowanmiller** [comment]
We think what we have is consistent with the ADO.NET contract. You can always send statements to use nested transactions.
