### ISSUE TITLE
Feature: Allow SqliteDataReader.GetOrdinal to be case insensitive

### ISSUE THREAD

**Issue by Xandroid4Net** [aspnet/Microsoft.Data.Sqlite#251]
I know that the parameter is case sensitive, however is there a way to allow for insensitive? The constructor is marked internal so I cannot extend the object and override the method. I am forced to loop through the column names twice right now. Once to do the case insensitive search and then then I use the reader["columnname"] this method will loop again. Or is there another way to accomplish this? The code I am using works fine with the sqlclient and the mono.data.sqlite implementation of the sqlitedatareader, but I would prefer to use this one if possible.

```
/// <remarks>The <paramref name="name" /> parameter is case sensitive.</remarks>
        public override int GetOrdinal(string name)
        {
            for (var i = 0; i < FieldCount; i++)
            {
                if (GetName(i) == name)
                {
                    return i;
                }
            }

            // NB: Message is provided by framework
            throw new ArgumentOutOfRangeException(nameof(name), name, message: null);
        }
```

**Comment by rowanmiller** [comment]
We aren't planning to do this as we're currently just exposing what SQLite does natively.

**Comment by bricelam** [comment]
Confirmed; SQLite is case-sensitive. Here is a query to demonstrate.
```SQL
SELECT
    1 AS a,
    2 AS A;
```
