### ISSUE TITLE
Consider easier alternatives to opt out of sqlite3 native library distribution

### ISSUE THREAD

**Issue by divega** [aspnet/Microsoft.Data.Sqlite#252]
The changes we are doing to depend on a sqlite native  package should improve the default experience of using Microsoft.Data.Sqlite and Microsoft.EntityFrameworkCore.Sqlite quite a bit. E.g. customers that just install those packages will get a standard version of sqlite3 for the platform they target and we should not encounter reports of missing libraries in the future. 

However it creates a cliff of complexity for users that legitimately don't want to use the version of sqlite3 we would distribute, either because they prefer to use  whatever version is already available in the platform (either sqlite3 or winsqlite3) or a custom build (e.g. with added encryption capabilities). 

One possible way to address this is to create "NoNative" variants of our packages. Possibly the "default" packages could become metapackages that depend on both the "NoNative" and the native distribution package. 

Note that I don't expect this to something we would need to address for RTM. As far as I understand we could refactor our packages in this way in the future without it being a breaking change.

**Comment by bricelam** [comment]
Dupe of #148?

**Comment by divega** [comment]
Yes. I should have searched :blush: Anyway, I will copy the proposal there.
