### ISSUE TITLE
Implement IDbColumnSchemaGenerator

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#253]
System.Data.Common 4.1.0 adds support for an interface that allows pulling metadata out of `DbDataReader`. https://github.com/dotnet/corefx/issues/5915

In short, this means implementing `System.Data.Common.IDbColumnSchemaGenerator` on `SqliteDataReader`

Cref https://github.com/dotnet/corefx/pull/8639.

**Comment by saurabh500** [comment]
@natemcmaster It is not necessary for you to implement `System.Data.Common.IDbColumnSchemaGenerator` on `SqliteDataReader`  unless you want to expose the schema from the `SqliteDataReader`

**Comment by divega** [comment]
Thanks @saurabh500. I think the point of this issue is that to consider doing it in the future.

**Comment by bricelam** [comment]
See also #16

**Comment by bricelam** [comment]
Note, in .NET Standard 2.0, it looks like `DbDataReader.GetColumnSchema()` delegates to `DbDataReader.GetSchemaTable()` if `IDbColumnSchemaGenerator` isn't implemented.

In other words, just implementing `DbConnection.GetSchema()` would be the best way to resolve this issue.

**Comment by tiandian** [comment]
Please implementing DbDataReader.GetSchemaTable.
My below code doesn't work because sqlite's DbDataReader.GetSchemaTable doesn't implement.

```
DataTable dt = new DataTable();
using (DbDataReader ddr = this.ExecuteReader(strSql))
 { dt.Load(ddr); }
```
Below is the error:
```
System.NotSupportedException occurred
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Data.Common.DbDataReader.GetSchemaTable()
   at System.Data.ProviderBase.SchemaMapping..ctor(DataAdapter adapter, DataSet dataset, DataTable datatable, DataReaderContainer dataReader, Boolean keyInfo, SchemaType schemaType, String sourceTableName, Boolean gettingData, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillMappingInternal(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillMapping(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
   at System.Data.DataTable.Load(IDataReader reader)
```

thanks.

**Comment by bricelam** [comment]
@tiandian This issue is currently on our backlog which means it may be a while before we get around to implementing it, but we would happily work with someone from the community on a pull request for it.

EF Core's [SqliteDatabaseModelFactory](https://github.com/aspnet/EntityFramework/blob/rel/2.0.0/src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs) would be a good place to look for reference.

**Comment by bricelam** [comment]
You may also want to file a separate issue about supporting `DataTable`. This specific error is likely only the tip of the iceberg. I believe we'd need to implement `DbCommandBuilder` too to support generating the appropriate queries.

**Comment by AlexanderTaeschner** [comment]
Looking at the large number of possible columns in the schema table for me the main question for an implementation would be, which of the columns are necessary and what is the expected content.
Using the sqlite3 API we have only access to a very restricted information (name, value, type) of a column in a query result, all further information has to be deduced by querying and interpreting the SQL of the table definition. System.Data.Sqlite has an implementation of  DbDataReader.GetSchemaTable which is, due to this problem, an extremely long and difficult to understand method.
Therefore I would really suggest to start with a minimum set of necessary columns (e.g. what would be necessary for DataTable.Load to work?).

**Comment by bricelam** [comment]
Here's an initial stab at it. The ones with null can probably be excluded entirely.

Column Name | Type | Source
--- | --- | ---
SchemaTableColumn.AllowDBNull | bool? | sqlite3_table_column_metadata()
SchemaTableOptionalColumn.BaseCatalogName | string | sqlite3_column_database_name()
SchemaTableColumn.BaseColumnName | string | sqlite3_column_origin_name()
SchemaTableColumn.BaseSchemaName | string | null
SchemaTableOptionalColumn.BaseServerName | string | SqliteConnection.DataSource
SchemaTableColumn.BaseTableName | string | sqlite3_column_table_name()
SchemaTableColumn.ColumnName | string | SqliteDataReader.GetName()
SchemaTableColumn.ColumnOrdinal | int? | SqliteDataReader.GetOrdinal()
SchemaTableColumn.ColumnSize | int? | null
SchemaTableColumn.IsAliased | bool? | sqlite3_column_origin_name() != SqliteDataReader.GetName()
SchemaTableOptionalColumn.IsAutoIncrement | bool? | sqlite3_table_column_metadata()
SchemaTableColumn.IsExpression | bool | sqlite3_column_origin_name() != null
SchemaTableOptionalColumn.IsHidden | bool? | false
"IsIdentity" | bool? | false
SchemaTableColumn.IsKey | bool? | sqlite3_table_column_metadata()
SchemaTableColumn.IsLong | bool? | SqliteDataReader.GetFieldType() == typeof(long)
SchemaTableOptionalColumn.IsReadOnly | bool? | null
SchemaTableColumn.IsUnique | bool? | SELECT COUNT(*) FROM pragma_index_list($table) i, pragma_index_info(i.name) c WHERE "unique" = 1 AND c.name = $column AND NOT EXISTS (SELECT * FROM pragma_index_info(i.name) c2 WHERE c2.name != c.name);
SchemaTableColumn.NumericPrecision | int? | null
SchemaTableColumn.NumericScale | int? | null
"UdtAssemblyQualifiedName" | string | null
SchemaTableColumn.DataType | Type | SqliteDataReader.GetFieldType()
"DataTypeName" | string | SqliteDataReader.GetDataTypeName()

**Comment by bricelam** [comment]
Additional notes:
* Not sure what `IsLong` is for...
* Could parse `ColumnSize`, `NumericPrecision`, and `NumericScale` from the type name.
* Not sure if `DataTypeName` should contain the size, percision, or scale.

**Comment by bricelam** [comment]
I have no idea what DataTable.Load uses. I tried digging through [the code](https://github.com/dotnet/corefx/blob/v2.0.0/src/System.Data.Common/src/System/Data/DataTable.cs#L4961) but got lost.

**Comment by bricelam** [comment]
Looks like `IsLong` means something else:

> Whether the column contains a BLOB that contains very long data.

We should just use `null`.

**Comment by bricelam** [comment]
@markrendle It's in! (or it will be when 2.1.0-preview1 ships) How goes the port of Simple.Data to .NET Standard?
