### ISSUE TITLE
SELECT load_extension

### ISSUE THREAD

**Issue by sports-jas** [aspnet/Microsoft.Data.Sqlite#256]
First up, is there any documentation where I can determine if this should be working or not and what features are/arent available?

If not, should this work on Windows? If so, where to I put the dlls. Specifically, I'm trying to execute:
SELECT load_extension('mod_spatialite');

The dlls are in the path and Ive tried putting them other locations.

Honestly, I don't know if this is a bug or a feature thats not implmented.

Thanks you

**Comment by bricelam** [comment]
Did you call `connection.EnableExtensions()` first?

**Comment by sports-jas** [comment]
No, and I don't know how I missed the method either. I've been developing using clr core (asp.net next) for over a year and have figured most things out. I don't know how I missed this - so simple!

Yes, it works fine using that.

Thank you

**Comment by bricelam** [comment]
Glad it works! I an odd API to begin with but SQLite requires it. I think the idea is that you should be explicit about which connections can load extensions because they introduce additional attack surface.

**Comment by sports-jas** [comment]
Good point. I hadn't considered it from that point of view.

**Comment by wejto** [comment]
Hi,

I have enabled extensions for my connection but still don't seem to load anything correctly, exception saying there is no such an extension/can't find it.

So I would like to join the original question - where do I put mentioned dll?

Using Microsoft.Data.Sqlite v 2.0.0 in .NET Core console application
SELECT load_extension('mod_spatialite');
