### ISSUE TITLE
Review allocations in string marshalling code 

### ISSUE THREAD

**Issue by divega** [aspnet/Microsoft.Data.Sqlite#259]
(Copied from https://github.com/aspnet/Microsoft.Data.Sqlite/issues/235#issuecomment-222218604)

@buybackoff  commented: 

Related issue is byte[] allocation for UTF8 in MarshalEx. Without prepared statements, any SQL command always allocates. This could be mitigated using a buffer pool, or the string marshalling logic could be changed to first call Encoding.GetNumberOfBytes and then to call GetBytes overload that writes directly to a pointer. In my tests that was one of the main garbage generators. (There is also string concatenation in param prefix check). I do not write strings columns now, but this could affect all cases with strings as well, not just SQL statements.

cc @bricelam

**Comment by bricelam** [comment]
Closing this since we've switched to using [SQLitePCL.raw](https://github.com/ericsink/SQLitePCL.raw).
