### ISSUE TITLE
Automatic inclusion of sqlite3.dll for UWPs defeats the purpose of WinSqlite.

### ISSUE THREAD

**Issue by ali-hk** [aspnet/Microsoft.Data.Sqlite#260]
Currently if the rc2 nuget package is referenced from a UWP, it automatically includes a copy of sqlite3.dll in the AppX package. This pretty much defeats one of the primary purposes of WinSqlite, which is to reduce app package size and reduce the number of times sqlite3.dll is present in various apps.
One potential solution to this is to check for an MSBuild property (say DisableIncludeSqlite) and check if that's set in the targets file, and if so don't include it. 

This would also enable developers to provide custom (perhaps newer) builds of sqlite3.dll if needed.

**Comment by bricelam** [comment]
We're discussing possible solutions to this in #148

**Comment by bricelam** [comment]
For now, you can remove it by adding the following to your `*.csproj` file.

```XML
<Target Name="RemoveSqlite" AfterTargets="ResolveNuGetPackageAssets">
  <ItemGroup>
    <ReferenceCopyLocalPaths Remove="%(ReferenceCopyLocalPaths.Identity)"
                             Condition="'%(Filename)%(Extension)' == 'sqlite3.dll' " />
  </ItemGroup>
</Target>
```

Unfortunately, .NET Native takes issue with this. (See #249)

**Comment by divega** [comment]
Closing as this is covered by #148 and #249.
