### ISSUE TITLE
Move SqliteEngine.UseWinSqlite3 to Internal for now

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#262]
Given the issues mentioned in #249, the whole point of using `winsqlite3.dll` is kind of moot. We should remove it for RTM and look at better ways of enabling it in the future.

**Comment by natemcmaster** [comment]
But the API works on desktop for Windows 10, right?

**Comment by bricelam** [comment]
It "works", but .NET Native still requires `sqlite3.dll` to be present and loads it, so there's no point in using the in-the-box version.

**Comment by bricelam** [comment]
Re-marking for triage. As @natemcmaster pointed out, this would also cut the feature for non-.NET Native, Windows 10 users. (E.g. Windows 10 IoT Core)

**Comment by divega** [comment]
@natemcmaster suggested in the PR that we could make the API internal for RTM, and I personally believe that may be an acceptable compromise as it means we can eventually remove it if we come up with something different.
