### ISSUE TITLE
Enable using winsqlite3.dll

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#263]
Newer versions of Windows ship with a version of SQLite in-the-box. At one point, we had `SqliteEngine.UseWinsqlite3()` to enable using it; however it was removed due to problems with .NET Native always requireing and loading `sqlite3.dll` anyway.

**Comment by natemcmaster** [comment]
This https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/SqliteEngine.cs#L10-L11 ?

**Comment by divega** [comment]
No longer needed because of https://github.com/aspnet/Microsoft.Data.Sqlite/issues/262.
