### ISSUE TITLE
Database file is locked after close connection

### ISSUE THREAD

**Issue by 303248153** [aspnet/Microsoft.Data.Sqlite#271]
First, create a new file and open it with Microsoft.Data.Sqlite.SqliteConnection
Then create tables and write records, and close the connection.
Finally try to delete the file, and it will fail.

This problem is not exists with System.Data.Sqlite.
OS is windows 8 64bit.

**Comment by bricelam** [comment]
Could you share your repro code?

**Comment by 303248153** [comment]
I try to reproduce this problem with a standalone project but it didn't happened.
The problem is releated to the other issue I opened about ReadCommited is unsupported, maybe I didn't close the connection when open transaction failed.
If I found the reason and if It need to be fix in Microsoft.Data.Sqlite I will reopen this issue.

**Comment by johnmurphy01** [comment]
I also have an issue with attempting to delete a sqlite database file after attempting to close the connection: https://github.com/aspnet/EntityFramework/issues/7021
