### ISSUE TITLE
Need to pass Encryption Key to database to open

### ISSUE THREAD

**Issue by gjohncock** [aspnet/Microsoft.Data.Sqlite#276]
SQlite allows a connection/database to be encrypted and the key usually passes as a parameter to the connection.  I checked the source and it doesnt appear to be catered for.  Can this be added?

**Comment by natemcmaster** [comment]
This question has been discussed before #184. Assuming you are using one of the more common encrypted SQLite libraries, you can do this by issuing the correct PRAGMA setting immediately after connection open. See http://www.bricelam.net/2016/06/13/sqlite-encryption.html
