### ISSUE TITLE
sqlite3.dll not found in ASP.NET 4 applications

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#278]
Repro

Create ASP.NET 4 web application
Add Microsoft.Data.Sqlite 1.0.0
Add code that calls `SqliteConnection.Open()`

Error
DllImportException "sqlite3.dll" not found

Reason
Despite the build appropriately places sqlite3.dll in to bin/x86 and bin/x64, ASP.NET sets `AppDomain.CurrentDomain.BaseDirectory` to the project root, but NativeLibraryLoader needs to use "$projectRoot/bin"

**Comment by VitaliyMF** [comment]
I've faced the same issue as @natemcmaster, bug can be reproduced when Microsoft.Data.Sqlite is used from .NET 4.5.1 ASP.NET application. The fix is rather trivial: https://github.com/aspnet/Microsoft.Data.Sqlite/pull/280
