### ISSUE TITLE
Relative paths in connection string fails on Xamarin.iOS/Android

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#279]
System.MissingMethodException: Method AppContext.get_BaseDirectory not found.

**Workaround**

Specify full path. e.g.
```c#
var filePath= Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "test.db");
var connection = new SqliteConnection("Data Source=" + filePath));
```

**Comment by divega** [comment]
@natemcmaster is this an issue you think we should try to address in our SQLite provider or is it here to track the fix in Xamarin?

**Comment by natemcmaster** [comment]
This is external. After filing this, I got confirmation that Xamarin will be adding support for this API soon.
