### ISSUE TITLE
SqliteConnection.Open fails when directory does not exist

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#284]
Repro:
Use a connection string to a directory that doesn't exist

Error
> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()

Problem
This error can be difficult to understand, especially when a relative path is used

Possible solutions
Keep current behavior, but add a better error message to indicate directory did not exist.
Call Directory.CreateDirectory()

**Comment by divega** [comment]
**Triage:** we would like to get more customer feedback before we do this. Closing for now.
