### ISSUE TITLE
Opt-in to using thread pool to make SQLite calls non-blocking

### ISSUE THREAD

**Issue by gulbanana** [aspnet/Microsoft.Data.Sqlite#291]
This is kind of a consequence of unfortunate design choices in DbCommand, but it's still a problem: Microsoft.Data.Sqlite uses the default implementations of methods like ExecuteReaderAsync, which actually perform the work synchronously and then return TaskFromResult. This causes unexpected problems for applications which are trying to use async correctly.

For example, I have a UWP application which needs to maintain UI responsiveness while data is being loaded. It calls "await Repository.GetObjects();" from the ui thread, which uses ExecuteReaderAsync() - this works fine as the application was written to use MS SQL Server. Now I'm trying to swap in SQLite, and the UI has started hanging instead of displaying a progress bar!

**Comment by bricelam** [comment]
The native SQLite APIs do not support async, so there is no good way to implement these methods. The SQLite team recommends using [Write-Ahead Logging](http://sqlite.org/wal.html) instead.

**Comment by gulbanana** [comment]
That's fine if I know I'm using SQLite, but what should we do in libraries which have received a DbConnection or DbCommand from an external source?

**Comment by StephenCleary** [comment]
An asynchronous (`Task`-returning) method is the proper signature for a method that *may* be asynchronous. Thus, it is up to the consumer to ensure that it actually is asynchronous if calling it from a UI thread.

ADO.NET (most notably SQLite) has approached this by making the methods blocking. So UI users have to wrap them in `Task.Run`.

`Stream` (most notably `MemoryStream`) has approached this by doing work on the thread pool (in `Task.Run`). So UI users don't have to wrap, but this is a less-than-efficient approach when used on ASP.NET.

On a side note, `HttpClient` has a funky mostly-asynchronous implementation by default, but depends on a synchronous DNS lookup first. So it's both synchronous and asynchronous, requiring some people to wrap it in `Task.Run` (most notably when behind certain corporate proxies).

What's the "right" answer? I have no idea. :)

**Comment by gulbanana** [comment]
Unfortunate. I'd go with just using the sync APIs and wrapping them myself to provide predictable behaviour, except that in the whole thing is actually a service being connected to by HttpClient - which as you mentions is async-*only*, sort of.  So it seems like the only way to switch between SQL Server and SQLite implementations of ADO.NET in that circumstance is to create adapters or do runtime checking for what method of async-wrapping has been used.

**Comment by bricelam** [comment]
We went back and forth on this in #51, but ultimately decided whatever we tried to do would be "wrong" in some cases, so we just stuck with ADO.NET's default implementation.

**Comment by gulbanana** [comment]
Fair enough :-(

**Comment by bricelam** [comment]
I wonder if you could inject a wrapping provider that used `Task.Run()` for these methods...

**Comment by gulbanana** [comment]
A DbCommand decorator is definitely a possible solution. However, the issue you linked includes a fairly convincing argument that the Read/Execute methods are too fine-grained a place to use the thread pool.. what I'll first look into doing in our application is having higher-level logic which is configured to either chain async calls (if it's using MSSQL) or create one longer-running Task which chains sync calls (if it's using Sqlite).

**Comment by divega** [comment]
We triaged this and had it in my TO-DO list to add some more details, but it was mostly what @bricelam and @gulbanana have already covered. 

I would just like to add that the default implementation in ADO.NET is what it is because we preferred the burden of dealing with different async capabilities to be on provider writers shoulders as opposed to consuming code. There are always going to be providers that aren't completely async. The challenge in this case, is a provider for which the underlying (native) implementation is completely sync. 

`Task.Run()` doesn't seem a good solution, but @AndriySvyryd has some new ideas we would like to have a chance to explore. Reopening.

**Comment by divega** [comment]
There is also some potential value in the discussion in #51 and the summary I made in https://github.com/aspnet/Microsoft.Data.Sqlite/issues/51#issuecomment-65883079, although last time we decided against attempting any of that. E.g. we could use `Task.Run()` for some but not all methods.

**Comment by gulbanana** [comment]
Sounds like that could be a useful mitigation for people who use the APIs without researching them. Ones which block for only a very short time aren't such a big deal.

In general the ADO.NET provider-chooses design made sense, but modern UI really throws a wrench in it with its requirement to implement responsiveness by calling async methods.

**Comment by StephenCleary** [comment]
I would really hesitate to do a partial-wrapping solution. The problem with I/O is not just a time issue, it's a reliability issue. You just never know when network connectivity or an over-eager antivirus will suddenly slow down the next I/O call.

IMO all the I/O should follow the same pattern (whether synchronous or fake-async). This might mean pushing very short-lived work onto the thread pool (which it _is_ designed for).

**Comment by gulbanana** [comment]
Maybe we should try to get a .IsAsynchronouslyAsync property added on the base classes in corefx...

**Comment by StephenCleary** [comment]
@gulbanana :)

In the older APM pattern, there actually was an `IAsyncResult.CompletedSynchronously` property, which was important for avoiding stack dives. `Task` implements it to always return `true`, though. :/

**Comment by gulbanana** [comment]
I see the issue is re-closed; could we please get some info on the outcome of investigations and what the direction of async in sqlite might be?

**Comment by AndriySvyryd** [comment]
@gulbanana I wasn't able to find a solution that would be fast to implement and didn't potentially create more issues than it solved. Unfortunately we have a lot of things on our plate and can't spend much time on this issue.

**Comment by gulbanana** [comment]
OK :(
