### ISSUE TITLE
Extended functions

### ISSUE THREAD

**Issue by ili** [aspnet/Microsoft.Data.Sqlite#297]
SQLite has set of extended functions like `Floor`, `Power`, `Log`, they are available while using `System.Data.SQLite` and not available with `Microsoft.Data.Sqlite`

**Comment by bricelam** [comment]
Ironically, `System.Data.SQLite` uses a custom build of SQLite. We use the [official builds](https://www.sqlite.org/download.html) of SQLite which presumably doesn't have these...

**Comment by bricelam** [comment]
#148 is about making it easier to use a different build of SQLite.
