### ISSUE TITLE
DataReader changes column type from row to row

### ISSUE THREAD

**Issue by ili** [aspnet/Microsoft.Data.Sqlite#300]
I do have a column with decimal values, when I'm reading column data type it changes from row to row:
```cs
	    [Test]
	    public void DecimalTest()
	    {
			using (var connection = new SqliteConnection(@"Data Source=Database\TestData.sqlite"))
			{
				connection.Open();
				var command = connection.CreateCommand();

				command.CommandText = "SELECT MoneyValue FROM LinqDataTypes";

				var r = command.ExecuteReader();
				while (r.Read())
				{
					var value = r.GetValue(0);
					Console.WriteLine($"{value.GetType().FullName} {value}, {r.GetFieldType(0)}");
					Assert.AreNotEqual(typeof(long), r.GetFieldType(0), $"{value.GetType().FullName} {value}");
				}
			}
		}
```

Output:
System.Double 1.11, System.Double
System.Double 2.49, System.Double
System.Double 3.99, System.Double
System.Double 4.5, System.Double
System.Double 5.5, System.Double
System.Double 6.55, System.Double
System.Int64 7, System.Int64 *(???? Why?)*

**Comment by ili** [comment]
Also if column type is `Int32` `GetFieldType` returns `Int64`

**Comment by natemcmaster** [comment]
If you need to ensure a particular .NET type, I recommend using `SqliteDataReader.GetFieldValue<T>`. 

SQLite does not enforce storage type restrictions. This means implementation of `SqliteDataReader.GetValue` has to rely on the SQLite engine to tell us the storage type of each value. From that the reader tries to determine the best .NET type to represent the data.

Try this, for example:
```sql
CREATE TABLE Data ( Col1 INTEGER );
INSERT INTO Data VALUES ( 1.4 ), (1), ("one"), (null), (X'0500');
SELECT typeof(Col1) FROM Data;
```

This will return:
```
typeof(Col1)
------------
real        
integer     
text        
null        
blob
```

See https://www.sqlite.org/datatype3.html for more details.

**Comment by abbfmst** [comment]
I know it's late, but this issue is still there. I have this exact issue with Dapper as linked above. @rowanmiller and @natemcmaster wouldn't it be possible to use PRAGMA TABLE_INFO(tablename) to get the correct type at least in cases where it was declared correctly?

**Comment by natemcmaster** [comment]
It wouldn't help. As mentioned in my previous comment, SQLite itself does not enforce type restrictions. `PRAGMA TABLE_INFO(tablename)` only provides a details about the default type affinity of a column, but "the datatype of a value is associated with the value itself, not with its container." cref https://www.sqlite.org/datatype3.html. I still recommend `SqliteDataReader.GetFieldValue<T>` if you need to ensure a particular type is returned.

**Comment by ericsink** [comment]
FWIW, some folks like to use SQLite triggers to make the column typing stricter.  For example, the following trigger will disallow insert of a non-integer value for column "bar" on table "foo":

    CREATE TRIGGER "foo_bar_type_INSERT" 
    BEFORE INSERT 
    ON "foo" 
    FOR EACH ROW 
    WHEN(NEW."bar" IS NOT NULL) 
    BEGIN     
      SELECT CASE     
        WHEN(typeof(NEW."bar") = 'integer') THEN 1    
        ELSE RAISE(ABORT, 'type mismatch foo.bar should be int')     
      END; 
    END;

The resulting behavior is closer to what a db like SQL Server would give, wherein the type mismatch error happens at insert time instead of during a query.
