### ISSUE TITLE
After installing VS2017 RC creation of sqlite db file is broken (HRESULT: 0x80073D54)

### ISSUE THREAD

**Issue by marcwittke** [aspnet/Microsoft.Data.Sqlite#303]
It's about an ASP.NET Core project, creating a Sqlite db file on first request. I did the following
- working like a boss on my project using VS2015 enterprise
- being happy about a completed feature, verified using Postman and also unit tests, pushed it to the repo, created pull request
- noticing that VS2017 RC is available
- well, I have to leave my PC alone for three hours, closing VS2015, starting the installation
- returning to the PC, installation succeeded
- phone call from coworker about pull request, opening project using VS2015 (!)
- being very sad about the follwing screen after pressing F5
![dailywtf](https://cloud.githubusercontent.com/assets/4075651/20445969/19c27274-adb6-11e6-9a6b-dcc905f4c348.PNG)
```The process does not contain the identity of the package (Exception from HRESULT: 0x80073D54)```
- Full exception stack trace: ```   at Windows.Storage.ApplicationData.get_Current() ```

So, I did not even restart the PC (sure, later, but problem persists) nor open VS 2017 a single time. So my guess is the VS2017 installation broke something. But what? BTW: the other path for production using "real" SQL Server is fine. So I assume a problem in the sqlite package.

Other observation: It's the first time to see a german exception message. So there was a change regarding the runtime maybe?

Uninstalling VS2017, reverting to restore point, all no help. 😢

**Comment by bricelam** [comment]
Hmm, could you search your machine for copies of sqlite3.dll? It looks like it's somehow loading the wrong one...

**Comment by bricelam** [comment]
Weird. It's finding Windows Storage APIs in an ASP.NET Core app...

**Comment by marcwittke** [comment]
For the record: ```git clean -xfd``` in combination with desparate (un)installations of diverse dotnetcore sdks fixed the issue. 
However, still weird.
