### ISSUE TITLE
Many dependencies added between 1.0.0 => 1.1.0

### ISSUE THREAD

**Issue by itsho** [aspnet/Microsoft.Data.Sqlite#305]
Hi.

It seems that many new dependencies was added to NuGet package version 1.1.0.
I'm not sure they all are needed.

Dependencies for version 1.0.0:
![1 0 0 dependencies](https://cloud.githubusercontent.com/assets/1774797/20523018/d60b0498-b0bb-11e6-8ab7-ac6f9a5bfc2f.png)

Dependencies for version 1.1.0:
![1 1 0 dependencies](https://cloud.githubusercontent.com/assets/1774797/20523019/d8f8ac96-b0bb-11e6-8193-fb60178c2cd8.png)

**Comment by bricelam** [comment]
Hmm.. System.Data.Common 4.3.0 appears to be lifting versions from NETStandard.Library 1.6.0.

**Comment by bricelam** [comment]
@pranavkm Did we depend on the right version of System.Data.Common?

**Comment by pranavkm** [comment]
It's the additional `NETStandard.Library` dependency we added to all our libraries. 1.0.0 did not depend on `NETStandard.Library` https://www.nuget.org/packages/Microsoft.Data.SQLite/1.0.0. For some past discussion on why we added this dependency see https://github.com/aspnet/WebListener/issues/268. 

@itsho is this causing issues in your application?

**Comment by itsho** [comment]
@pranavkm it seems like too many dependencies so I've avoided the upgrade currently.
I'll try to upgrade and test if there's any issues. 
thanks.

**Comment by rowanmiller** [comment]
Closing as this is not specific to this package/project. You could consider opening an issue on https://github.com/aspnet/Home if you want to push back on the general design.
