### ISSUE TITLE
Parametrized query equal comparison

### ISSUE THREAD

**Issue by draveckym** [aspnet/Microsoft.Data.Sqlite#308]
When running command like
`"SELECT CASE WHEN @param = 0 THEN 1 ELSE 0 END AS Result"`,
result is ALWAYS 0. Other comparisons are working just fine, but equality fails.
parameters are sent by
`_command.Parameters.AddWithValue(_param.Key, _param.Value);`
and specifying of DbType/SQLiteType to number have no effect at all.

Parameters are always treated as "string", which gives me correct evaluation in these comparison examples:
`@param + 0 = 0`
`@param = '0'`

lib versions tested are 1.0.0 & 1.1.0

**Comment by bricelam** [comment]
Can you confirm that `@param` is actually being set to a value, and not remaining `NULL`?

**Comment by draveckym** [comment]
Yes, I checked its value and when edited command to `= '0'` just as mentioned above, result was correct.
Real command is little more complex, but after checking other conditions, only this one is malfunctional.. Here the full command:
 `SELECT CASE WHEN @CalcMonth = 0 AND @PolInitAge >= 45 AND @RegPrem >= @CoefAbs THEN @MaxValAbs ELSE @MinValAbs END AS LoyaltyBonus`
Command.Parameters properties set to:
@CalcMonth == 0
@PolInitAge == 66
@RegPrem == 200
@CoefAbs == 150
... other two conditions are evaluated positively, but @CalcMonth gives negative response until explicit conversion is made...

**Comment by bricelam** [comment]
Ah, SQLite has no native representation of decimal values. The provider will always convert them to string. Would double values work for your scenario?

**Comment by bricelam** [comment]
See [this comment](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/296#issuecomment-255783552) for our general approach to types.

**Comment by draveckym** [comment]
Thanks. Converting to double has done the trick, but from conceptual point of view - is it buggy behavior? I mean >=, <= comparisons are working correctly, even if Decimal is converted into string and value 0 is handled as '0', SQLite3 should not care about datatype and try to compare values converting them to common type... at least united handling would be nice (accept all primitives OR throw exception every time unsupported type is used)...

btw - since GetDecimal(int Index) is implemented, I suppose original goal was to handle all primitive types O:) but OK. I am satisfied for now. Thanks again

**Comment by bricelam** [comment]
I don't think I'd consider it a bug. Just yet another quirk of SQLite's [dynamic type system](http://www.sqlite.org/datatype3.html) coupled with it's limited set of primitive types. SQLite is weird, but we do our best to map it to the ADO.NET programming model.

**Comment by buybackoff** [comment]
from https://www.sqlite.org/datatype3.html, section 3

> A column with TEXT affinity stores all data using storage classes NULL, TEXT or BLOB. If numerical data is inserted into a column with TEXT affinity it is converted into text form before being stored.

> A column with NUMERIC affinity may contain values using all five storage classes. When text data is inserted into a NUMERIC column, the storage class of the text is converted to INTEGER or REAL (in order of preference) if such conversion is lossless and reversible. For conversions between TEXT and REAL storage classes, SQLite considers the conversion to be lossless and reversible if the first 15 significant decimal digits of the number are preserved. If the lossless conversion of TEXT to INTEGER or REAL is not possible then the value is stored using the TEXT storage class. No attempt is made to convert NULL or BLOB values.

I believe .NET driver should convert decimals to doubles. Then, if the column affinity if NUMERIC/REAL, then the conversion decimal->double is correct. If the affinity is TEXT, double will be automatically converted to string by SQLite. When decimal is converted to string by the driver, SQLite has to do additional work to do `the lossless conversion of TEXT to INTEGER or REAL`, and at the same time issues with parameters like this one arise. All comparison operators just coerce the string value to numeric at SQLite side, which also adds the same additional work.

**Comment by bricelam** [comment]
@buybackoff Our goal is to losslessly store CLR values. `decimal` values are larger (or more precise) than `double` values. If we automatically converted them to `double`, data may be lost.

The affinities and conversions mentioned in that document primarily have to do with SQLite's storage format which is largely transparent to applications (and the ADO.NET provider).

Regarding additional work: If you want to use the database optimally, use one of the four primitive types supported by SQLite: `string`, `byte[]`, `long` & `double`. Avoid CLR types that necessarily have to be coerced when reading and writing (e.g. `DateTime`, `decimal`, etc.)

You can also perform the conversion before sending it to the database:

```C#
var param = 0m;

command.CommandText = "SELECT @param = 0;";
command.Parameters.AddWithValue("@param", (double)param);

Assert.Equal(1L, command.ExecuteScalar());
```

...or force a comparison affinity using `CAST`:

```C#
var param = 0m;

command.CommandText = "SELECT CAST(@param AS REAL) = 0;";
command.Parameters.AddWithValue("@param", param);

Assert.Equal(1L, command.ExecuteScalar());
```

I'm going to go ahead and close this issue because I haven't seen a proposal that wouldn't lead to additional issues elsewhere. Please let us know if you think of any additional ways to improve this scenario.
