### ISSUE TITLE
Full support of SqliteConnectionStringBuilder

### ISSUE THREAD

**Issue by NimaAra** [aspnet/Microsoft.Data.Sqlite#309]
Firstly great implementation and thank you for that :-)

I am planning on migrating an existing code-base currently using _System.Data.Sqlite_ over to _Microsoft.Data.Sqlite_ however I have the following method which allows me to build my connection string:

```csharp
private static string GetConnectionString(
            string dataSource, 
            bool binaryGuid, 
            DateTimeKind dateTimeKind,
            SQLiteDateFormats dateTimeFormat,
            SQLiteJournalModeEnum journalMode,
            SynchronizationModes syncMode,
            int pageSize,
            int cacheSize)
        {
            return new SqliteConnectionStringBuilder
            {
                DataSource = dataSource,
                Mode = 
                FailIfMissing = false,
                Pooling = false,
                BinaryGUID = binaryGuid,
                DateTimeKind = dateTimeKind,
                DateTimeFormat = dateTimeFormat,
                JournalMode = journalMode,
                SyncMode = syncMode,
                UseUTF16Encoding = false,
                LegacyFormat = false,
                PageSize = pageSize,
                CacheSize = cacheSize
            }.ToString();
        }
```

None of these flags or properties seem to be supported in _Microsoft.Data.Sqlite_. Is there a plan to support them?

**Comment by bricelam** [comment]
In general, we would consider them on a per-feature basis, and they may not necessarily be implemented as connection string parameters. Here are some specific comments.

Parameter | Comments
--- | ---
BinaryGUID | We always read and write `Guid` objects as `BLOB`. #273 & #191 are about using `TEXT`
CacheSize | You can send `PRAGMA cache_size = <pages>;`
DateTimeFormat | We read using `DateTime.Parse` and write using `yyyy-MM-dd HH:mm:ss.FFFFFFF`
DateTimeKind | We ignore `DateTime.DateTimeKind`
FailIfMissing | You can use `Mode = SqliteOpenMode.ReadWrite`
JournalMode | You can send `PRAGMA journal_mode = <mode>;`
LegacyFormat | You can send `PRAGMA legacy_file_format = <bool>;`
PageSize | You can send `PRAGMA page_size = <bytes>;`
Pooling | We don't pool connections
SyncMode | I'm not sure what this does
UseUTF16Encoding | You can send `PRAGMA encoding = 'UTF-16';`
