### ISSUE TITLE
Can't install anything other than Microsoft.Data.Sqlite 1.0.0

### ISSUE THREAD

**Issue by rhegner** [aspnet/Microsoft.Data.Sqlite#310]
I'm working on a .Net Core project. Currently the following versions are referenced:

- Microsoft.Data.Sqlite 1.0.0
- SQLite 3.12.2

I saw [here](https://www.nuget.org/packages/Microsoft.Data.SQLite/) and [here](https://www.nuget.org/packages/sqlite/) that newer versions should be available on NuGet. But I cannot see these packages in the NuGet manager.

If I include prereleases the only thing apart from version 1.0.0 are some preview versions of 1.2.0, but I cannot install them either because they are complaining that SQLite 3.12.3 is not found (I only have access to 3.12.2).

My NuGet is up to date (version 3.5.0).

Any idea why can't I see these NuGet packages? Are they not supported by .Net Core projects?

**Comment by rhegner** [comment]
I can reproduce this problem by creating a new Console Application (.NET Core) using Visual Studio 2015 (all updates applied) and then trying to add Microsoft.Data.Sqlite. The only version I can see in the NuGet Package manager is version 1.0.0.

**Comment by ErikEJ** [comment]
Are you having the correct Target framework? https://www.nuget.org/packages/Microsoft.Data.SQLite/

**Comment by rhegner** [comment]
It was a problem with my NuGet configuration. For some reason, the default feed (https://api.nuget.org/v3/index.json) was missing. I was now able to install verison 1.1.0
