### ISSUE TITLE
Revisit skipped winsqlite3 tests

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#315]
Follow up to https://github.com/aspnet/Microsoft.Data.Sqlite/pull/314

The 'UseWinSqlite3_throws_when_loaded' test fails when build.cmd is executed on command line. This may have been caused by changes in the lifecycle of the test framework.

**Comment by bricelam** [comment]
This will be superseded by the move the SQLitePCL.raw.
