### ISSUE TITLE
Windows App Certification Kit Supported API test failed

### ISSUE THREAD

**Issue by luvidev** [aspnet/Microsoft.Data.Sqlite#316]
I get these errors when running Windows App Certification Kit for UWP:

> Error Found: The supported APIs test detected the following errors:
API sqlite3_bind_blob in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_bind_double in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_bind_int64 in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_bind_null in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_bind_parameter_count in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_bind_parameter_index in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_bind_parameter_name in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_bind_text in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_busy_timeout in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_changes in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_close in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_close_v2 in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_column_blob in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_column_bytes in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_column_count in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_column_decltype in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_column_double in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_column_int64 in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_column_name in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_column_text in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_column_type in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_db_filename in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_enable_load_extension in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_errmsg in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_errstr in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_finalize in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_libversion in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_open_v2 in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_prepare_v2 in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_reset in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_step in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
API sqlite3_stmt_readonly in sqlite3.dll is not supported for this application type. Microsoft.Data.Sqlite.dll calls this API.
Impact if not fixed: Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements.
How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Windows Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information:

My project configuration is ".NET Native enabled" and on release configuration.

Hope you can help fix them. 
Kind regards,
Luca

**Comment by ajcvickers** [comment]
@luvidev The errors you are seeing are different, so this mat be a different issue, but you might want to look at https://github.com/aspnet/EntityFramework/issues/7040 anyway and try the workaround listed there to see if it helps.

**Comment by luvidev** [comment]
@ajcvickers Thanks for help! I have solved the problem. 
I have read your link and i have updated nuget Visual Studio plugin to v3.5 from [https://dist.nuget.org/index.html](https://dist.nuget.org/index.html) (i had installed v3.4.4) and i added again Microsoft.Data.Sqlite v1.1.0 and Microsoft.EntityFrameworkCore.Sqlite v1.1.0. 
After that, WACK don't report any issues.
Thanks again.

**Comment by AdaptiveTechnologies** [comment]
Adding the Microsoft.Data.Sqlite v1.1.0 nuget helped me get past a similar certification kit error.
