### ISSUE TITLE
Implement new .NET Standard 2.0 contracts

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#319]
With .NET Standard 2.0 comes a host of new functionality that we could consider implementing:

* System.Transactions (covered by #294)
* System.Data.SqlTypes
* DbCommandBuilder
* DbDataAdapter
* DbDataSourceEnumerator
* DbConnection.GetSchema()
* System.ComponentModel.Component

Also, should the NuGet package continue to include a `netstandard1.2` implementation (in addition to `netstandard2.0` for these features) to follow suit with the BCL packages?

**Comment by bricelam** [comment]
`IDbColumnSchemaGenerator` (#253) is another outstanding feature, but was available before 2.0.

**Comment by natemcmaster** [comment]
>  should the NuGet package continue to include a netstandard1.3 implementation in addition to netstandard2.0?

I think it would be okay to drop netstandard1.3. UWP, Xamarin, and .NET Core will receive updates to make them compatible with netstandard2.0.

**Comment by bricelam** [comment]
See also: dotnet/corefx#16165

**Comment by rowanmiller** [comment]
Discussed and decided to tackle this reactively. The package will still work with netstandard2.0. If we see folks wanting this package in a way where it needs to implement the netstandard2.0 contract then we can do the work.
