### ISSUE TITLE
Where is the DB file stored?

### ISSUE THREAD

**Issue by DerKnerd** [aspnet/Microsoft.Data.Sqlite#330]
I have a short question, I am using Sqlite for a work time tracking tool in a UWP. Now I want to know where the Sqlite DB is stored, my code is the following

```c#
private async Task<SqliteConnection> OpenConnectionAsync() {
    var connectionStringBuilder = new SqliteConnectionStringBuilder {
    DataSource = "workitems.db",
        Mode = SqliteOpenMode.ReadWriteCreate
    };
    var connection = new SqliteConnection(connectionStringBuilder.ToString());
    return connection;
}
```

**Comment by natemcmaster** [comment]
`Windows.Storage.ApplicationData.Current.LocalFolder.Path`.

See https://github.com/aspnet/Microsoft.Data.Sqlite/wiki/Connection-Strings for more details.
