### ISSUE TITLE
SQLite Error 1: 'no such function: xxx'.

### ISSUE THREAD

**Issue by jogibear9988** [aspnet/Microsoft.Data.Sqlite#331]
On Appveyor I got the following errors: (https://ci.appveyor.com/project/igor-tkachev/linq2db-8c54d/build/1.7.7.409/tests)

- Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'no such function: CharIndex'.
- Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'no such function: Ceiling'.
- Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'no such function: Cos'.
- Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'no such function: Replicate'.
- Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'no such function: Floor'.

these Tests work perfectly using System.Data.Sqlite

**Comment by ErikEJ** [comment]
These functions are not available in the base SQLite engine, and not implemented in this provider. 

See https://system.data.sqlite.org/index.html/artifact/cf472240cc05d3be

**Comment by jogibear9988** [comment]
will they be implemented?

**Comment by bricelam** [comment]
We don't plan to implement them, no. But we allow you to use your own custom build of the native SQLite database, so you could certainly use Microsoft.Data.Sqlite with a build that supports them.

**Comment by ili** [comment]
@bricelam can you please give a sample how to use custom SQLite engine?

**Comment by bricelam** [comment]
What type of project are you using?

For some project types, you can simply add the dll to your project and set **Copy to Output Directory** to **Copy if newer** in the item’s properties.

**Comment by bricelam** [comment]
If you're using MSBuild-based NuGet, you may need to specify the `ExcludeAssets` metadata.

```XML
<PackageReference Include="sqlite" Version="3.13.0">
  <ExcludeAssets>native</ExcludeAssets>
</PackageReference>
```

**Comment by bricelam** [comment]
User-defined function (see #14) could also be used to define these.

**Comment by ili** [comment]
We are using .net core projects (vs 2015)

**Comment by bricelam** [comment]
I filed dotnet/sdk#1088 to enable the ideal way of doing it, but until then, you should be able to do it like this.

1. Put your custom `sqlite3.dll` in the root of your project.
2. Add the following to your `*.csproj`.

```XML
<ItemGroup>
  <PackageReference Include="sqlite" Version="3.13.0">
    <ExcludeAssets>native</ExcludeAssets>
  </PackageReference>
  <None Update="sqlite3.dll">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>
```
