### ISSUE TITLE
Track recent breaking changes in `exceptions.net*.json` files

### ISSUE THREAD

**Issue by dougbu** [aspnet/Microsoft.Data.Sqlite#338]
This repo contains untracked breaking changes. To find and address them
1. Revert fe63a2a
2. Run `.\build.cmd /t:Pack` in projects fe63a2a touched or `.\build.cmd /t:Package` in the repo root
3. Update `exceptions.net45.json` and `exceptions.netcore.json` to track the changes
4. If not already announced, suggest filing issues at https://github.com/aspnet/Announcements

**Comment by dougbu** [comment]
In addition, the following project lacks baselines. The details below are reformatted from a recent Universe build on the CI.
```
[Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite\Microsoft.Data.Sqlite.csproj]
  No baseline file for net451 found in Microsoft.Data.Sqlite.
  No baseline file for netstandard1.2 found in Microsoft.Data.Sqlite.
```

**Comment by dougbu** [comment]
New baselines for `Microsoft.Data.Sqlite` should be generated in `rel/1.0.0` branch and checked into `dev` branch.

**Comment by bricelam** [comment]
@dougbu There doesn't appear to be any work to do here other than enabling the check on Microsoft.Data.Sqlite.Core and disabling it on Microsoft.Data.Sqlite (it's a meta-pacakge without assemblies). Am I missing something?

**Comment by dougbu** [comment]
@bricelam as long as API Check succeeds in Microsoft.Data.Sqlite.Core now, life is good 🥇

Surprised that worked since the checks failed in that project when I was testing API Check and the controlling JSON files haven't changed. Did recent commits undo breaking changes?

**Comment by bricelam** [comment]
No, like I said above, I tried hard to keep the exceptions up-to-date after we switched to csproj.
