### ISSUE TITLE
winsqlite3.dll should use CallingConvention.StdCall

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#342]
You'll only observe differences in a few corner cases. The two things that have been mentioned so far are:
* You could get a corrupt stack when SQLite invokes a managed callback
* Trying to debug the app crashes with a corrupt stack

SQLitePCL.raw has the same issue, so I've filed https://github.com/ericsink/SQLitePCL.raw/issues/149 to get this fixed for 2.0.0.

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.

**Comment by Eilon** [comment]
@bricelam - do you have a status update on this bug? Does it just need to be closed?

**Comment by Eilon** [comment]
Preview builds of this patch fix should be available on the following feeds:

* https://dotnet.myget.org/gallery/aspnet-1-0-5-may2017-patch-public (for fixes in the 1.0.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-0-5-may2017-patch-public/api/v3/index.json
* https://dotnet.myget.org/gallery/aspnet-1-1-2-may2017-patch-public (for fixes in the 1.1.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-1-2-may2017-patch-public/api/v3/index.json

If you have a chance, please try out these preview builds and let us know if you have any feedback!
