### ISSUE TITLE
Revert "Revert "Implement SqliteCommand.Prepare.""

### ISSUE THREAD

**Issue by smitpatel** [aspnet/Microsoft.Data.Sqlite#345]
Revert the PR #344 after investigating the downstream failures it caused. See https://github.com/aspnet/EntityFramework/issues/7982

**Comment by bricelam** [comment]
Note to self: we probably need to reset the statement immediately after we're done reading it.

**Comment by AlexanderTaeschner** [comment]
Unfortunately I am not able to reproduce the failures on my local machine, so that I cannot help here.

**Comment by bricelam** [comment]
Re-opening #235 and closing this as a dupe.
