### ISSUE TITLE
Compensate for SQLitePCL.raw's lack of SafeHandles

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#351]
Before, our native handles were implemented using `SafeHandle` to ensure they eventually got freed by the garbage collector thus preventing a native memory leak. I'm not sure if SQLitePCL.raw has the same guarantee. We need to investigate and compensate as necessary.

cc @ericsink in case he has a quick answer to this

**Comment by bricelam** [comment]
From testing, it looks like the connection will get collected and free itself along with everything associated with it. Unfortunately, if the connection remains open, any non-disposed handles associated with it will be leaked until the connection is closed.

As @AlexanderTaeschner found, we'll need to dispose sqlite3_stmt objects in the finalizers of any owning objects.

**Comment by ericsink** [comment]
Last time I looked at this issue, I remember thinking I would like to use SafeHandle but that it would be a breaking change.  Not sure if there were any other caveats also.

**Comment by bricelam** [comment]
@ericsink I'm totally fine compensating in our library--it just caught me a little off guard.

**Comment by ericsink** [comment]
Nonetheless, I'd like to keep an eye on this matter, just in case your efforts make me realize a change should be made to SQLitePCL.raw which would benefit all users.

That said, I think the code I've got now could be described as sensible if I said it like this:

Once you open a sqlite3 connection handle, you should close it.

It is an error (from SQLite itself) to close a sqlite3 connection handle if it still has statement handles open.  (Probably also true for blob handls.)  So, before you close a connection handle, you have to finalize any of its statement handles first.

Apps or libraries that follow these rules should not have problems.

And when you say "compensating in our library", I hear you saying that you want to use the GC as part of your plan to "follow these rules". But it is possible for apps/libraries to "follow these rules" without using the GC.

Does that make sense?

**Comment by bricelam** [comment]
Correct. Makes sense to me.
