### ISSUE TITLE
SqliteDataReader.GetXYZ could throw a more descriptive exception if value is null

### ISSUE THREAD

**Issue by Kittyfisto** [aspnet/Microsoft.Data.Sqlite#356]
Currently, methods such as SqliteDataReader.GetInt64 throw an InvalidCastException with no further explanation as to what the programmer did wrong (in this case, access a cell that is null). It'd be nice if the exception text were to tell me that the value is null and I should've called SqliteDataReader.IsDbNull.

**Comment by ajcvickers** [comment]
@Kittyfisto GetInt64 and related methods are very perf-critical. For this reason, we avoid adding additional checks here even when they would give a better error message because the value of that is less than the value of keeping the code fast for the case where the API is being used correctly.
