### ISSUE TITLE
e_sqlite3.dll still present in publish output after trimming

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Microsoft.Data.Sqlite#360]
Updating SQLitePCLRawVersion to 1.1.3 was supposed to fix this issue but the publish output still contains this dll. Will investigate further.

**Comment by bricelam** [comment]
cc @ericsink

**Comment by ericsink** [comment]
(grumble)

If we can figure out what's going wrong here, I'll look to get this re-fixed quickly.

**Comment by JunTaoLuo** [comment]
Filed issue https://github.com/ericsink/SQLitePCL.raw/issues/154. Keeping this issue open to track.

**Comment by ericsink** [comment]
When is your preview1?  I'm preparing to release the fix.

**Comment by ericsink** [comment]
Or to put this another way:

In the next hour or two, I could release a SQLitePCL.raw 1.1.4 which contains the fix (to move the targets files down into build/whatever so that .NET Core will not see them), but I will not have done any testing on .NET Core.

Or, on Monday, I could release 1.1.4 after I've done some testing with .NET Core.

Your choice.  At this point, my 1.1.4 release is just this fix.

**Comment by bricelam** [comment]
I'll let @Eilon answer, but I don't think there's any need to publish a release until you hear from him.

**Comment by JunTaoLuo** [comment]
@Eilon We should take the 1.1.4 version of this package with the fix if possible for preview1.

**Comment by Eilon** [comment]
Yeah if we can get this fixed, that would be great. If there was a new Sqlite package on Monday and we could try that out, and verify it all works, then we would likely take this for our Preview1 build.

**Comment by ericsink** [comment]
I have pushed my 1.1.4 release to nuget.  Basic testing indicates it still seems to work fine on .NET framework and Mono, and now also does (what I think is) the right thing on .NET Core.

**Comment by Eilon** [comment]
@ericsink thank you for the quick turnaround!

**Comment by JunTaoLuo** [comment]
Due to the Nuget bug https://github.com/NuGet/Home/issues/5149, we can consider trimming these assemblies on .NET Core in a post-publish target.

**Comment by JunTaoLuo** [comment]
We are working around this with https://github.com/aspnet/MetaPackages/pull/99. @Eilon @muratg we can probably triage this out of preview1 and track the external issue in https://github.com/dotnet/sdk/issues/1166

**Comment by Eilon** [comment]
Moving this for preview2 to clear up the preview1 milestone, and to make sure we remember to follow up and make sure all the actual bugs are fixed.

**Comment by JunTaoLuo** [comment]
Work around in https://github.com/aspnet/MetaPackages/pull/99 did not work. Filed https://github.com/NuGet/Home/issues/5233

**Comment by JunTaoLuo** [comment]
@muratg We have worked around this in preview2 with https://github.com/aspnet/MetaPackages/pull/119. We can re-triage this issue into the next milestone to track reverting the workaround once the underlying issue is fixed.

**Comment by muratg** [comment]
@JunTaoLuo sounds good, thanks. Removing from the milestone for now.

**Comment by ericsink** [comment]
My current understanding is that SQLitePCL.raw is not doing anything incorrectly.  Somebody let me know if that changes.  :-)

**Comment by JunTaoLuo** [comment]
@ericsink Correct, this is an issue with the dotnet/sdk which is where the fix will be made. No changes are required for SQLitePCL.raw. Thanks!

**Comment by JunTaoLuo** [comment]
FYI, this should be resovled by https://github.com/aspnet/External/issues/59.

**Comment by ericsink** [comment]
FWIW, @JunTaoLuo , the link in your previous comment goes to a 404 page.  At least for me it does.

**Comment by muratg** [comment]
@ericsink it's a private repo where we track external issues.

**Comment by Eilon** [comment]
@JunTaoLuo / @muratg / @natemcmaster - is this issue fixed now w/ the updated SQLite package?

**Comment by natemcmaster** [comment]
Fixed. I verified it manually with 2.0.0-preview3-26071.
