### ISSUE TITLE
Adding Microsoft.Data.SQLite (v1.1.0) through NuGet package manager in Xamarin Studio (macOS Sierra) fails

### ISSUE THREAD

**Issue by vmakwana** [aspnet/Microsoft.Data.Sqlite#361]
here's what happened:

Attempting to gather dependency information for package 'Microsoft.Data.SQLite.1.1.0' with respect to project 'SQLiteTesting', targeting '.NETFramework,Version=v4.5'
  GET https://api.nuget.org/v3/registration1-gz/microsoft.data.sqlite/index.json
  OK https://api.nuget.org/v3/registration1-gz/microsoft.data.sqlite/index.json 1269ms
Total number of results gathered : 1
Gathering dependency information took 1.86 sec
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json	-	1.86 sec
Attempting to resolve dependencies for package 'Microsoft.Data.SQLite.1.1.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.Data.SQLite.1.1.0'
Resolved actions to install package 'Microsoft.Data.SQLite.1.1.0'
Retrieving package 'Microsoft.Data.Sqlite 1.1.0' from 'nuget.org'.
For adding package 'Microsoft.Data.Sqlite.1.1.0' to project 'SQLiteTesting' that targets 'net45'.
Install failed. Rolling back...
Package 'Microsoft.Data.Sqlite.1.1.0' does not exist in project 'SQLiteTesting'
Package 'Microsoft.Data.Sqlite.1.1.0' does not exist in folder '/Users/xyz/Projects/SQLiteTesting/packages'
Executing nuget actions took 87.39 ms
Could not install package 'Microsoft.Data.Sqlite 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by bricelam** [comment]
> You are trying to install this package into a project that targets '.NETFramework,Version=v4.5'

Our minimum supported version is .NET Framework 4.5.1
