### ISSUE TITLE
Library documentation

### ISSUE THREAD

**Issue by AlexanderTaeschner** [aspnet/Microsoft.Data.Sqlite#362]
After the addition of the custom collations (#14) and the planned inclusion of user defined functions (#19) the library is growing from a simple "implementation of the System.Data.Common interfaces" to a sqlite wrapper which offers .NET programmers a friendly access point to the different features of the C interface of sqlite.
This growth makes it harder to find these additional features if no additional library documentation is provided. Therefore my wish would be, to have some more documentation of the library, at minimum a page with simple samples for the additional features linked from the project homepage (https://github.com/aspnet/Microsoft.Data.Sqlite).

**Comment by bricelam** [comment]
@divega Any way to get (at least) the API docs on https://docs.microsoft.com?

**Comment by divega** [comment]
We found how to do this. We need to decide what repo to use. Let's chat in triage.

**Comment by divega** [comment]
@Eilon can we  create a new repo `Microsoft.Data.Sqlite.Docs` to put the documentation for our SQLite provider there?

cc @dend

**Comment by bricelam** [comment]
aspnet/EntityFramework.Docs#354 can also be moved to the new repo.

**Comment by Eilon** [comment]
@divega - we can certainly create a new repo, but would it be fine to just go in some existing docs repo? Where will the docs for this end up going?

**Comment by divega** [comment]
@eilon in triage and agreed on having it in its own repo. That way we keep it independent and should be easier to move if ever needed. Is there any restriction on the number of repos? Also, I don't think any of us felt very strongly about this one, so if you have a good reason to push back let us know.

Re the question on what the destination is going to be inside docs.microsoft.com, I am not sure yet, but I imagine the API documentation could be like any other packages that are not part of core but are produced by Microsoft and goes in under dotnet. For any other content it certainly doesn't seem to belong into either EF or ASP.NET documentation. @dend can probably provide more details on this.

**Comment by dend** [comment]
@richlander @terrajobst - will this fit under the dotnet org? Otherwise, it should be in MicrosoftDocs.

**Comment by Eilon** [comment]
@divega no actual limits on creating public repos, but sometimes it seems a "waste" in terms of bloating the number of repos and having to manage/track items across multiple repos, especially for something so small.

But so long as you feel it's worth it, I have no problem creating another repo.

**Comment by divega** [comment]
@Eilon ok, please go ahead an create a repo for this.

**Comment by Eilon** [comment]
Here ya go: https://github.com/aspnet/Microsoft.Data.Sqlite.Docs

**Comment by bricelam** [comment]
@dend Where does this publish too? https://docs.microsoft.com/dotnet-aspnet-sqlite doesn't seem to exist...

**Comment by bricelam** [comment]
Found it: https://docs.microsoft.com/dotnet/api/microsoft.data.sqlite

@divega can we update the GitHub project to have this link?

**Comment by bricelam** [comment]
The repo link (next to the name)

**Comment by divega** [comment]
@bricelam done. I had not noticed one can put a link there :blush:
