### ISSUE TITLE
Failure to open Sqlite in-memory database

### ISSUE THREAD

**Issue by buckhorn-foxpert** [aspnet/Microsoft.Data.Sqlite#369]
I am attempting to create a test for a database using the example from the Microsoft docs [https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite](url)

When I attempt to run the code from the Test Explorer, I get an error on the second line of code
`	var connection = new SqliteConnection("Data Source=:memory:");   
	connection.Open();
`
I am getting this error when Visual Studio 2017 (version 15.1-26403.7) tries to run the 2nd line
[xUnit.net 00:00:01.0677640]       System.Exception : You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
[xUnit.net 00:00:01.0688613]       Stack Trace:
[xUnit.net 00:00:01.0699257]            at SQLitePCL.SQLite3Provider_bait.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
[xUnit.net 00:00:01.0700654]            at Microsoft.Data.Sqlite.SqliteConnection.Open()

Here are the packages installed from my csproj file
`  
<ItemGroup>
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170502-03" />  
    <PackageReference Include="Microsoft.DotNet.InternalAbstractions" Version="1.0.500-preview2-1-003177" />  
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Design" Version="2.0.0-preview1-final" />  
    <PackageReference Include="xunit" Version="2.3.0-beta2-build3683" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta2-build1317" />
  </ItemGroup>
`

**Comment by AlexanderTaeschner** [comment]
You need to add the ```SQLitePCLRaw.bundle_e_sqlite3``` (or ```SQLitePCLRaw.bundle_green``` which uses on iOS the system-provided SQLite lib) package.

**Comment by bricelam** [comment]
Installing `Microsoft.EntityFrameworkCore.Sqlite` will do this for you.

**Comment by bricelam** [comment]
What are you using `Microsoft.EntityFrameworkCore.Sqlite.Design` for in your tests?
