### ISSUE TITLE
Works on Mac w/ .NET Core 1.1?

### ISSUE THREAD

**Issue by erikporter** [aspnet/Microsoft.Data.Sqlite#376]
I'm trying to see if we can use SQLite in our .NET Core 1.1 app. We do development on Windows & Mac and run in production on Ubuntu 16.

To test it out I built a console app on VS for Mac. When I run it and it gets to opening the SqliteConnection, it throws this error...

`System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
   at SQLitePCL.SQLite3Provider_bait.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at SqliteTest.Program.Main(String[] args) in /Users/erik/Projects/SqliteTest/SqliteTest/Program.cs:line 18`

I...don't really know what that means. Am I doing something wrong? I'm just setting the connection string to `Data Source=test.db`. Is this a currently supported scenario or no?

If this isn't the right place for this, please direct me elsewhere. Thank you! :)

**Comment by bricelam** [comment]
What version of Microsoft.Data.Sqlite are you using?

**Comment by devna13** [comment]
The error says you need SQLitePCL.raw.SetProvider() so add https://github.com/ericsink/SQLitePCL.raw package, I'm using **SQLitePCLRaw.bundle_green**

and before opening the connection;

```
            SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_e_sqlite3());
or 
            SQLitePCL.Batteries.Init();
```

**Comment by erikporter** [comment]
@devna13 Ah, thank you. That did it. A case of me being unfamiliar with the details. Thanks again!
