### ISSUE TITLE
.net native compiler crashes with nuget 2.0.0-preview1-final 

### ISSUE THREAD

**Issue by DennisSc** [aspnet/Microsoft.Data.Sqlite#377]
Hello,

I've encountered build errors with the latest nuget package. While compiling UWP apps containing a reference to "MicrosoftData.SQLite (nuget package version 2.0.0-preview1-final)", the build fails when building in release mode (using "visual studio 15.2 build 26430.13 Release").

The error ist also reproducible across several other build systems (also visualstudio hosted build agents), happens only when compiling in release configuration, and only with 2.0.0-preview1-final. In debug configuration or with nuget package 1.1.1, all is fine.

CI build error output as follows:

> 
> C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets (691, 5)
> C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets(691,5): Error : Internal compiler error: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> Process 'msbuild.exe' exited with code '1'.
> Publish build artifacts failed with error: Not found PathtoPublish: c:\agent\_work\1\a\AppxPackages

Note - This might also affect current nuget packages of EntityFramework, see https://github.com/aspnet/EntityFramework/issues/8461#issuecomment-309896545

edit - will try the workaround provided by @MichalStrehovsky [here](https://github.com/aspnet/EntityFramework/issues/8461#issuecomment-311825073) and close if appropriate (as soon as i find some time)

**Comment by ajcvickers** [comment]
@DennisSc Can you let us know if the workaround works for you?

**Comment by DennisSc** [comment]
The workaround works. Build now succeeds in release mode (tested with 2.0.0-**preview1**-final - the preview2 currently doesn't find its assembly, but thats another chapter)

Here's my Default.rd.xml for reference:


```
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <!--
      Ein Assemblyelement mit Name="*Application*" gilt für alle Assemblys im
      Anwendungspaket. Die Sternchen sind keine Platzhalter.
    -->
    <Assembly Name="*Application*" Dynamic="Required All" />
    
    
    <!-- Fügen Sie hier Ihre anwendungsspezifischen Laufzeitdirektiven ein. -->
	<Type Name="Microsoft.Data.Sqlite.SqliteDataReader" Browse="Excluded" Dynamic="Excluded" Serialize="Excluded" Activate="Excluded" />

  </Application>
</Directives>
```

regards

**Comment by divega** [comment]
>  the preview2 currently doesn't find its assembly, but thats another chapter

This might be because UWP still does not support .NET Standard 2.0. See  https://github.com/aspnet/Announcements/issues/247.
