### ISSUE TITLE
PlatformTarget AnyCPU causes SQLite invocation to fail with cryptic error

### ISSUE THREAD

**Issue by divega** [aspnet/Microsoft.Data.Sqlite#393]
_From @Ketrex on July 29, 2017 18:1_

I have a .NET core console application which references a netstandard1.4 class library containing a dbContext. My console application creates a new ServiceCollection and adds the necessary references as detailed here:
```
var services = new ServiceCollection();
            services.AddOptions();
            services.AddSingleton(_configuration);
            services.AddLogging();
            services.AddEntityFramework();
            var connectionString =
                    new Microsoft.Data.Sqlite.SqliteConnectionStringBuilder { DataSource = "etoDataMgr.db" }.ToString();
                services.AddDbContext<LocalDataContext>(o => o.UseSqlite(connectionString));
```
As long as I specify x64 or x86 as the platform target, my application runs fine. If I set the target to AnyCPU, an exception is thrown during the call to 'Database.EnsureCreated()' of my DbContext. 

If the SQLite provider requires an explicit target for x86 and x64, then the error message for 'AnyCPU' is pretty cryptic, and not terribly helpful in tracking down the problem.

The exception is:
```
Exception message:
Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Stack Trace:
   at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Omni.EtoDataMgr.Data.LocalDataContext..ctor(DbContextOptions dbContextOptions)
```

### Steps to reproduce
Specify 'AnyCPU' as the platform target.

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.Sqlite 1.1.2
Operating system: Windows 10 Pro x64
IDE: Visual Studio 2017

_Copied from original issue: aspnet/EntityFramework#9299_

**Comment by divega** [comment]
_From @bricelam on July 31, 2017 15:58_

I've seen this too. At some point, I think the `SQLite` NuGet Package stopped working with AnyCPU projects. You could try downgrading that package to see if it works with an older one.

**Comment by divega** [comment]
_From @bricelam on July 31, 2017 16:0_

It's supposed to copy both versions of the dll to the output directory: `x86\sqlite3.dll` and `x64\sqlite3.dll`.

**Comment by bricelam** [comment]
Note, we're no longer using that package in version 2.0.0.

**Comment by divega** [comment]
@natemcmaster can you advise on how to best handle this?

**Comment by natemcmaster** [comment]
@Ketrex ideally, it would be good to have a complete minimal repro of this. Can you share your csproj file and you .sln file? "AnyCPU" doesn't have meaning in a .NET Core application. My guess is that something in MSBuild is misconfigured and is causing Microsoft.NET.Sdk to incorrectly generate a list of native assets.

**Comment by Ketrex** [comment]
@natemcmaster, @divega, that observation actually helps quite a bit. I just tested it with my current code (several iterations after I reported the bug), and it appears to be working fine now.  I will see if I can go back and reproduce again with an earlier version of my code base, and post here if it still appears to be a bug, rather than misconfiguration.
