### ISSUE TITLE
Broken reuse of SqliteCommand and SqliteParameter

### ISSUE THREAD

**Issue by zone117x** [aspnet/Microsoft.Data.Sqlite#394]
An initial SqliteCommand and SqliteParameters cannot be used through multiple query executions. 
Only the first value of the sqlite parameter(s) are used. The workaround is to reset the SqliteCommand.CommandText which causes the prepared statements to be cleared.

I've forked and added a unit test method that demonstrates the bug with the hacky workaround.

https://github.com/PingmanTools/Microsoft.Data.Sqlite/blob/prepared-stmt-bug/test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs#L129

TLDR: The following doesn't work as expected:

```cs
using (var command = connection.CreateCommand())
{
    command.CommandText = "INSERT INTO Data (Value) VALUES (@value);";
    var valueParam = new SqliteParameter { ParameterName = "@value" };
    command.Parameters.Add(valueParam);

    for (var i = 2; i < 5; i++)
    {
        command.CommandText = "INSERT INTO Data (Value) VALUES (@value);";
        valueParam.Value = i;
        command.ExecuteNonQuery();
    }
}
```
All inserted rows will have `Value` set to `2` (the first set value of the parameter).

**Comment by bricelam** [comment]
@zone117x What version are you using? The nightly builds?

**Comment by zone117x** [comment]
Latest dev branch. As shown by the fork with the added unit test

**Comment by bricelam** [comment]
My subconscious [was trying to tell me](https://github.com/aspnet/Microsoft.Data.Sqlite/pull/334#pullrequestreview-27627499) there might be bugs in this area. I just forgot to follow up. 😄

**Comment by bricelam** [comment]
Weird. The following works:
```csharp
using (var command = connection.CreateCommand())
{
    command.CommandText = "SELECT @value;";
    var parameter = new SqliteParameter { ParameterName = "@value" };
    command.Parameters.Add(parameter);

    for (var i = 2L; i < 5L; i++)
    {
        parameter.Value = i;

        var result = command.ExecuteScalar();

        Assert.Equal(i, result);
    }
}
```
