### ISSUE TITLE
Custom functions support

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Microsoft.Data.Sqlite#402]
Hi.
SQLite supports custom functions. And most broadly used sqlite provider on .net - [System.Data.SQLite](https://system.data.sqlite.org) supports them as well.

It'd be nice to have the same in Microsoft.Data.Sqlite.

Here's an example how it looks in System.Data.SQlite - :
```csharp
	[SQLiteFunction(FuncType = FunctionType.Collation, Name = "NOCASE")]
	public class OrdinalIgnoreCaseCollation : SQLiteFunction
	{
		public override int Compare(string param1, string param2)
		{
			return StringComparer.OrdinalIgnoreCase.Compare(param1, param2);
		}
	}
```
then it should be registered as `SQLiteFunction.RegisterFunction(typeof(OrdinalIgnoreCaseCollation));`

**Comment by AlexanderTaeschner** [comment]
You can already use SqliteConnection.CreateCollation to add custom collations (see #19 for the API). The addition of other functions is in the works (tracked by #14).

**Comment by evil-shrike** [comment]
@AlexanderTaeschner cool, thanks! can be closed. 
Let me ask here (as I'm afraid it'll be another dup) - is there any way for getting typed error codes?
Like in System.Data.SQLite we have 
```
SQLiteException originalEx = ..;
SQLiteErrorCode code = m_connection.ExtendedResultCode();			
if (originalEx.ResultCode == SQLiteErrorCode.Constraint) {
  if (code == SQLiteErrorCode.Constraint_ForeignKey) 
  {}
  else if (code == SQLiteErrorCode.Constraint_PrimaryKey) {}
}
```

**Comment by bricelam** [comment]
Duplicate of #19, duplicate of #14
