### ISSUE TITLE
Add extended error code to SqliteException

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Microsoft.Data.Sqlite#404]
Currently (2.0) we have only `int` field `SqliteException.SqliteErrorCode` with an error code.

For example for a constraint violation it'll be 19. And `SqliteException.Message` will be `SQLite Error 19: 'UNIQUE constraint failed: User.Login'`.

Constraint violation is a very broad case. It can be unique constrain, check, foreign key and so on. This information is absent in SqliteException. Also `Message` property value is a combination "`SQLite Error N:" and original text from SQLite - 'UNIQUE constraint failed: User.Login'. This is bad for parsing. 

What's needed:

* Original text from SQLite: ('UNIQUE constraint failed: User.Login')
* SqliteErrorCode should be a enumration
* there should be an additional error code with mor details.

Here's how it's implemented in System.Data.SQLite. Connection object provider `ExtendedResultCode` method which return more detailed error code (using the same enumration `SQLiteErrorCode` for general code and details code is bad I think).
 
```
SQLiteException originalEx = ..;
SQLiteErrorCode code = m_connection.ExtendedResultCode();			
if (originalEx.ResultCode == SQLiteErrorCode.Constraint) {
  if (code == SQLiteErrorCode.Constraint_ForeignKey) 
  {
    // foreign key violation
  }
  else if (code == SQLiteErrorCode.Constraint_PrimaryKey) 
  {
    // primary key violation
  }
}
```

**Comment by bricelam** [comment]
SQLite has a limited set of [error codes](https://www.sqlite.org/rescode.html).

You can turn on extended error codes by dropping down to SQLitePCL.raw:

```csharp
SQLitePCL.raw.sqlite3_extended_result_codes(connection.Handle, 1);
```

> Original text from SQLite

I don't think this is useful after turning on extended error codes.

> SqliteErrorCode should be a enumration

The application or custom builds of SQLite can define additional error codes, so the set is not finite. You can always use the constants defined in SQLitePCL.raw:

```csharp
ex.SqliteErrorCode == SQLitePCL.raw.SQLITE_CONSTRAINT_FOREIGNKEY
```

> there should be an additional error code with mor details

Agreed. We should expose the extended error code on `SqliteException` without explicitly having to turn them on. (We can do this using `sqlite3_extended_errcode()`.)

**Comment by evil-shrike** [comment]
>I don't think this is useful after turning on extended error codes. Also, exceptions are supposed to be localized so parsing them should be avoided.

I'd agree if SQLite provides enough info in errors, but it doesn't (if I'm not mistaken). For example, name of violated constraint can be known only by parsing error text. So does violated columns in check constraint. So I guess currently parsing is unavoidable. Unfortunately. 

> The application or custom builds of SQLite can define additional error codes, so the set is not finite. You can always use the constants defined in SQLitePCL.raw:

Ok. But strictly speaking an enum field can have a numeric value which isn't in enumeration. 
As for `SQLitePCL.raw` - it's hard to find this class/struct. Some documentation would help here..
