### ISSUE TITLE
Keyword not supported - version

### ISSUE THREAD

**Issue by mind0n** [aspnet/Microsoft.Data.Sqlite#406]
Refer to the screenshot below, an exception is thrown when creating the SqliteConnection object indicating that the keyword version is not supported.
This connection string was picked from the url below, the basic form.
https://www.connectionstrings.com/sqlite/
 
![image](https://user-images.githubusercontent.com/1991295/29671086-2de665e4-891b-11e7-9e69-3992cb4c239f.png)

Expected Result:
SqliteConnection can be created successfully with the basic form connection string.

Nuget Package:
![image](https://user-images.githubusercontent.com/1991295/29671275-ab2f7d24-891b-11e7-9fa9-2adb92c14ddf.png)

Project Type:
.net standard 2.0

**Comment by bricelam** [comment]
This provider is *Microsoft.Data.Sqlite*. Those connection strings are for *System.Data.Sqlite*.

We support the following keywords.

Keyword | Values
--- | ---
Cache | Default, Private, or Shared
Data Source | The database file. Can be a SQLite [URI filename](https://www.sqlite.org/c3ref/open.html#urifilenamesinsqlite3open)
Mode | ReadWriteCreate, ReadWrite, ReadOnly, Memory

**Comment by mind0n** [comment]
Thanks for the response, if I remove the version keyword, it comes up another error indicating that 'file encrypted or not a database'.
How to create a sqlite database that Microsoft,Data.Sqlite support?
I tried creating version 2  .sdb and version 3 .s3db with SqliteAdmin (http://sqliteadmin.orbmu2k.de/) but both cannot be recognized by Microsoft.Data.Sqlite.

**Comment by bricelam** [comment]
Were you using `Password` in your connection string? The database may in fact be encrypted...
