### ISSUE TITLE
CommandTimeout not honored during Prepare()

### ISSUE THREAD

**Issue by tidyui** [aspnet/Microsoft.Data.Sqlite#408]
Hi there! After upgrading from `1.1.0` to `2.0.0` integration tests with XUnit are failing all over the place. All integration tests accessing the Sqlite database file share the same `test collection` to make sure they do not run in parallel.

Has anything in particular changed in opening/closing the datafile between 1.1 and 2.0 that will cause a lock on the file?

The project is open source and the error can easily be reproduced.

1. Clone the following repo/branch:https://github.com/PiranhaCMS/piranha.core/tree/features/netstandard-2.0
2. Run the main tests in `tests/Piranha.Tests` (**this should work**)
3. Change the package reference from Sqlite `1.1.0` to `2.0.0`
4. Restore and build
5. Run the tests again (**this will produce a lot of errors**)

Regards

Håkan

**Comment by tidyui** [comment]
So sorry! After more tests & debugging I realized there was a bug in the Api implementation causing connections to not be closed & disposed when the Api itself was disposed. This caused a lot of open connections which locked the datafile.

**HOWEVER** the behavior is still completely different from version `1.1.0` where this wasn't an issue. Has a new limit on the number of simultaneous connections been introduced in the latest version?

You are free to close the issue after you've read the conclusion if the new behavior is as intended.

**Comment by bricelam** [comment]
Hmm... no idea what would cause this. 😄 #323 was about reducing locks; something in e_sqlite3.dll version 3.18.2 might be configured differently than sqlite3.dll version 3.13.0...

I wonder if it's worth investigating.

**Comment by ericsink** [comment]
I can't think of anything that has changed (in either SQLitePCL.raw or sqlite itself) which would cause this behavior.

**Comment by bricelam** [comment]
@tidyui Are you on OSX? I know they have a relatively low limit on the number of open readers...

**Comment by tidyui** [comment]
Yes I am @bricelam, and I don't object to the behavior, just the fact that it changed so much between the versions!

**Comment by dabide** [comment]
I had a similar problem after running FluentMigrator migrations, The database was locked, in spite of both the command objects and the connection being disposed (`using` statements).

Updating SQLitePCL.raw to version 1.1.8 solved it.

**Comment by dabide** [comment]
Might be related to this fix: https://github.com/ericsink/SQLitePCL.raw/issues/166

**Comment by ericsink** [comment]
@dabide Maaaaaaybe.  But I don't (immediately) see how.

**Comment by dabide** [comment]
I thought it could be the same problem that is described here: https://stackoverflow.com/a/8513453/352573. There are numerous similar questions on SO.

As far as I could see in the FluentMigrator code, _every_ connection and command is in a `using` clause. Still, when I run the migrator, the database can't be written to afterwards (locked). If I don't run the migration, everything is fine.

**Comment by bricelam** [comment]
I wonder if 3473bf03b80ca1a62f5508685b80acba4bda4a9b fixes it...

**Comment by dabide** [comment]
https://github.com/aspnet/Microsoft.Data.Sqlite/commit/3473bf03b80ca1a62f5508685b80acba4bda4a9b didn't fix it (we tried the MyGet dev package). We then tried downd Microsoft.Data.Sqlite to 1.0.1, still experiencing the same issue.

As a desperate measure, we tried downgrading SQLitePCLRaw.* to the version we used before upgrading to .NET Core 2.0, i.e. 1.0.1. That solved the problem. @ericsink

**Comment by bricelam** [comment]
@tidyui @dabide Is this still an issue? Could you provide a simple repro so I can investigate?

**Comment by dabide** [comment]
Sorry, I don't know if this is still an issue. As I no longer work for the company where we had this issue, I have no easy way of finding it out, either.

**Comment by bricelam** [comment]
We stumbled across a way of reproducing this today. We'll continue investigating...

**Comment by bricelam** [comment]
Interesting. In our case, we call `Prepare()` explicitly. This used to be a no-op, now we eagerly prepare the statement. However, we don't honor `CommandTimeout` in this path so `SQLITE_BUSY` isn't automatically retired resulting in more *database is locked* errors. I'm not sure if this is the same case as those encountered above, but we should probably honor `CommandTimeout` during `Prepare()`.

**Comment by bricelam** [comment]
The underlying SQLite behavior is questionable since this is a read-only database, but the documentation does call it out:

> The SQLITE_BUSY result code indicates that the database file could not be written (or in some cases read)
