### ISSUE TITLE
Add build documentation

### ISSUE THREAD

**Issue by AlexanderTaeschner** [aspnet/Microsoft.Data.Sqlite#413]
I am not able to build your library anymore after the lastest changes to the build system using the latest version of Visual Studio 2017 Community (15.3.3).
As indicated in the README I tried running the command `build.cmd /t:Restore` in the Developer Command Prompt for VS2017, but this errors out:

> C:\Users\taschna\.dotnet\buildtools\korebuild\2.1.0-preview1-15482\modules\KoreBuild.Tasks\module.targets(28,5): error : Failed to retrieve information about 'Internal.AspNetCore.Universe.Lineup' from remote source 'C:\Users\taschna\\.dotnet\NuGetFallbackFolder'. [C:\Users\taschna\.dotnet\buildtools\korebuild\2.1.0-preview1-15482\KoreBuild.proj]

I can understand your desire to use your newest build tools, but please provide all information necessary to get/install/use them, so that we externals are able to build and contribute.

**Comment by AlexanderTaeschner** [comment]
Okay after manual creation of the `NuGetFallbackFolder` the build command runs to completion, but in VS I still get only error messages (.NET Core SDK 2 is installed from https://www.microsoft.com/net/core#windowscmd):
> The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.

**Comment by bricelam** [comment]
I'm getting lots of errors in VS too. Any ideas @natemcmaster?

**Comment by bricelam** [comment]
@AlexanderTaeschner It looks like you're hitting [the PATH issue](https://github.com/aspnet/Home/wiki/Building-from-source#path).

**Comment by natemcmaster** [comment]
> C:\Users\taschna.dotnet\buildtools\korebuild\2.1.0-preview1-15482\modules\KoreBuild.Tasks\module.targets

Looks like a slash is missing: `C:\Users\taschna.dotnet` should be `C:\Users\taschna\.dotnet`. What's you environment?

`PS> Get-ChildItem env:`

**Comment by bricelam** [comment]
I'm not getting IntelliSense.
![image](https://user-images.githubusercontent.com/1226749/29941867-cc5af3de-8e48-11e7-8d55-5c875e00e9e7.png)

**Comment by natemcmaster** [comment]
@bricelam restore errors or warnings? I'm in VS 15.3.3 and it's working fine for me.

git clean -xfd
build.ps1 /t:Restore
start Microsoft.Data.Sqlite.sln

![image](https://user-images.githubusercontent.com/2696087/29942074-77afce80-8e49-11e7-8b27-63a48c285727.png)

**Comment by bricelam** [comment]
I think I found the problem:

    C:\WINDOWS\system32\config\systemprofile\.dotnet\x64

Might be a change in Windows (Inisder Fast Ring)

**Comment by AlexanderTaeschner** [comment]
Okay, for me it was the PATH: I replaced `C:\Program Files\dotnet` with `%USERPROFILE%\.dotnet\x64` for the System Environment and it works now (not really nice workaround, but acceptable for me). 
Could you please add this to the README?

**Comment by natemcmaster** [comment]
@bricelam `C:\WINDOWS\system32\config\systemprofile\.dotnet\x64`

I hit this too. It's a Windows bug that's been around for a long time. You can't use %USERPROFILE% in system variables because it hasn't been defined correctly yet. You have to edit your PATH in the "user variables" section.

![image](https://user-images.githubusercontent.com/2696087/29942401-93065662-8e4a-11e7-9571-8a3f8952c942.png)

**Comment by bricelam** [comment]
Weird, I swear it was working yesterday. 😉

My problems are resolved too.

**Comment by natemcmaster** [comment]
> Weird, I swear it was working yesterday.

It might be a result of the goofy env var evaluation behavior in Windows. If you do anything that touches your environment, it triggers Windows to re-evaluate everything....so %PATH% expands correctly with the new value of USERPROFILE.

**Comment by bricelam** [comment]
@AlexanderTaeschner There's a big yellow warning in `build.cmd` (that I also ignored the first 100 times I ran it):

> WARNING: dotnet found on the system PATH is 'C:\Program Files\dotnet\dotnet.exe' but KoreBuild will use
'C:\Users\bricelam\\.dotnet\x64\dotnet.exe'.
> WARNING: Adding 'C:\Users\bricelam\\.dotnet\x64' to system PATH permanently may be required for applications like Visual
 Studio or VS Code to work correctly.

**Comment by natemcmaster** [comment]
FYI https://github.com/aspnet/BuildTools/issues/386 - we should do this. VS is pretty terrible at telling you why dotnet.exe isn't working.

**Comment by bricelam** [comment]
> Failed to retrieve information about '(blah)' from remote source 'C:\Users\taschna\\.dotnet\NuGetFallbackFolder'

Is this a known issue? Didn't we all have to manually update our `NuGet.Config` at some point? Could NuGet migrate/ignore broken versions?

**Comment by natemcmaster** [comment]
> C:\Users\taschna\.dotnet\NuGetFallbackFolder

Check %APPDATA%\NuGet\NuGet.config. You probably have this:
```xml
<add key="CliFallbackFolder" value="C:\Users\taschna\.dotnet\NuGetFallbackFolder" />
```

.NET Core **2.0.0-preview1** had a terrible bug that corrupted most of our CI machines. They added this feed to the global machine config, but never removed it. They don't do that anymore, but you still have to manually cleanup.

**Comment by AlexanderTaeschner** [comment]
@natemcmaster Yes I have that entry in NuGet.config. If I understand you correct it would be wise to delete it?

Concerning the placement of the PATH entry for %USERPROFILE%\.dotnet\x64: it seems safer from your comments to put it in the user section (but the  C:\Program Files\dotnet  has to be removed from the system section - otherwise it will be placed before the user entry).

**Comment by natemcmaster** [comment]
> if I understand you correct it would be wise to delete it?

Yes, go ahead and remove it. The 2.0.0 CLI uses MSBuild properties instead of NuGet.config to locate the NuGetFallbackFolder 

>  it seems safer from your comments to put it in the user section 

Yes, this is what I recommend. Once you do that, VS 15.3 and VS code should continue to work well. If not, let us know.
