### ISSUE TITLE
Add a Connection.Create file method 

### ISSUE THREAD

**Issue by Grauenwolf** [aspnet/Microsoft.Data.Sqlite#424]
It's a minor thing, but really helpful.

From System.Data.SQLite

```
/// <summary>
/// Creates a database file.  This just creates a zero-byte file which SQLite
/// will turn into a database when the file is opened properly.
/// </summary>
/// <param name="databaseFileName">The file to create</param>
static public void CreateFile(string databaseFileName)
{
  FileStream fs = File.Create(databaseFileName);
  fs.Close();
}
```

**Comment by bricelam** [comment]
When using `Mode=ReadWriteCreate` (used by default), opening the connection will create the file.

Two questions:
1. When is it useful to create an empty database before connecting to it?
2. Shouldn't a simpler file creation API just be added directly to [dotnet/corefx](https://github.com/dotnet/corefx)?

**Comment by bricelam** [comment]
If item 1 is useful, I think this should create an actual SQLite database, not just a zero-byte file.

**Comment by bricelam** [comment]
Another thing to consider in the design:

SQL Server Compact does it like this:

``` csharp
new SqlCeEngine(connectionString).CreateDatabase();
```

**Comment by Grauenwolf** [comment]
> When using  Mode=ReadWriteCreate  (used by default), opening the connection will create the file.

At the very least that needs to be added to the documentation.

And actually, that's probably the correct answer. The problem isn't "We need a CreateFile method", but rather "We need to know how to create a file".

**Comment by bricelam** [comment]
+1 on documentation. We really need more than just [API docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlite).  In the mean time, we can add a sentence to `SqliteConnection.Open()`.

**Comment by Grauenwolf** [comment]
For me, the difference between a zero-length file that will be auto-initialized later and an empty, ready to use file is inconsequential.

An empty, ready to use file might be less confusing to some people, but honestly I never noticed that the file was zero-length because I always immediately started filling it with schema.

**Comment by Grauenwolf** [comment]
> In the mean time, we can add a sentence to  SqliteConnection.Open() .

Also mention it on the SqliteConnection class page please. Otherwise people won't necessarily think to look at .Open.

**Comment by bricelam** [comment]
We discussed this as a team, and I think we need to hear more feedback from users about when it's useful to create an empty database before connecting to it before we implement this.

Closing as *wont-fix* for now, but like I said, we're open to additional feedback.
