### ISSUE TITLE
[2.0.x] Upgrade to SQLitePCLRaw 1.1.8

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#428]
This update supports linux arm32 configurations. cref https://github.com/aspnet/Universe/issues/554

cc @bricelam

**Comment by bricelam** [comment]
Might be worth taking parts of 3473bf03b80ca1a62f5508685b80acba4bda4a9b & b360984d5bdf85f1bb6fd8b61ee5dd0730e374be with this.

**Comment by bricelam** [comment]
Never mind. The changes in those commits aren't need in patch. They would finalize `sqlite3_stmt`s sooner in error cases, but SQLitePCL.raw version 1.1.8 also made a change to finalize them sooner, so it probably wouldn't have significant impact.

**Comment by Eilon** [comment]
This change is not approved for the 2.0.x patch. Should we move this bug to 2.1.0? I can get the OSS approval for the updated SQLitePCL package.

**Comment by natemcmaster** [comment]
2.1.0 is already on 1.1.8

**Comment by ericsink** [comment]
Is there anything I should know, or be doing differently, to better cooperate with your process for dependencies on third party OSS projects like SQLitePCL.raw?

Mostly I just try to respond to specific needs and never break anything.  But feedback in the area of process would be welcomed.

**Comment by natemcmaster** [comment]
> Is there anything I should know, or be doing differently, to better cooperate with your process for dependencies on third party OSS projects like SQLitePCL.raw?

@ericsink Not that I can think of. You've been really responsive and helpful.

**Comment by Eilon** [comment]
@ericsink yeah as per @natemcmaster you're doing everything already 😄 Because of the friendly licenses involved, for us it's just a tiny bit of paperwork to use it.

**Comment by Eilon** [comment]
Closing this because because it's already fixed in 2.1, and there's an easy workaround for 2.0.x.
