### ISSUE TITLE
SqliteDataReader's GetFieldType is not right.

### ISSUE THREAD

**Issue by tiandian** [aspnet/Microsoft.Data.Sqlite#433]
below line in SqliteDataReader.cs is not right:
```
public override DataTable GetSchemaTable()
{
...
   schemaRow[DataType] = GetFieldType(i);
...
}
```

because GetFieldType(i) is will call _record.GetFieldType(), then will call  raw.sqlite3_column_type, but raw.sqlite3_column_type will return the type of the current record's value, not  a column type, e.g if a nvarchar column's first row is number or null, then the sqlite3_column_type will return SQLITE_INTEGER,  this is not right.

So schemaRow[DataType] better use sqlite3_column_decltype to get the column's declare type, not use sqlite3_column_type  to get the record's value type.
 
See here:
https://stackoverflow.com/questions/38113129/calling-sqlite3-column-type-returns-sqlite-integer-for-a-string-column-that-cont

because GetSchemaTable get wrong column type,  DataTable.Load() will error.

**Comment by bricelam** [comment]
In SQLite, column's don't have types; values do. See [Datatypes In SQLite Version 3](https://www.sqlite.org/datatype3.html).

The value returned by `sqlite3_column_type` has no semantics that Microsoft.Data.Sqlite can use to map to a CLR type. In SQLite, column types are just application-defined strings used to mimic a traditional RDBMS.

If your database stores fields of different types inside the same column, it is incompatible with ADO.NET for certain scenarios.

I agree we probably need to handle `SQLITE_NULL` better in `SqliteDataReader.GetFieldType()`. We should probably default to `string` whenever we can't determine the type (like we do in other places). We could also consider something like aspnet/EntityFrameworkCore#8824.

**Comment by tiandian** [comment]
can use raw.sqlite3_column_decltype to get the column's declare type? 
then change the value to the column's declare type.

```
public override Type GetFieldType(int ordinal)
{
	Type t;
	string typeName = raw.sqlite3_column_decltype(_stmt, ordinal);
	switch(typeName)
	{
		case "integer","int","byte":
			t = TypeOf(int);
			break;
		case "numeric", "real", "real", "float", "double":
			t = TypeOf(double);
			break;
		case "long":
			t = TypeOf(long);
			break
		case "decimal":
			t = TypeOf(decimal);
			break;
		case "blob":
			t = typeof(byte[]);
			break;
		case "text","varchar","nvarchar":
		defaut:
			t = TypeOf(string);
		
	}
	
	return t;
}
```

thanks!

**Comment by bricelam** [comment]
One guiding principle we've followed in Microsoft.Data.Sqlite is to never apply additional semantics on top of SQLite. In SQLite, a column's declared type is only used as a heuristic to store and coerce values more efficiently.

Applying additional, arbitrary semantics (e.g. that the declared type `INT` maps to the CLR type `Int32`) leads to a world of complexity. System.Data.SQLite has to parse every SQL statement before letting the database parse it because they had to add a special `TYPES` statement so that expressions and constants in queries can also have a declared column type. They also have to allow you to override the type mappings because whatever mapping you pick it won't be correct for every existing SQLite database.

By not doing anything to hide SQLite's weirdness, we force applications to make a conscious decision about how they want to handle it. We believe this approach is more helpful to users than if we hide it for the sake of convenience. We've found that too much magic tends to confuse people more than it helps them.

**Comment by tiandian** [comment]
but your way is completely wrong, it will lead Microsoft.Data.Sqlite is useless.

**Comment by bricelam** [comment]
If *123* is stored as `TEXT`, it will be a `string`. When using Microsoft.Data.Sqlite, an application should avoid storing both `INTEGER` and `TEXT` values in the same column.

**Comment by tiandian** [comment]
e.g
if a column has three row, the value is 123, null, "fdafda", then you will Calculate the column type is int, then you will assign "fdafda" to a int value, this is completely wrong.

**Comment by bricelam** [comment]
But if we updated `GetSchemaTable()` to use `SELECT typeof(column) FROM table` and *most* of the values were `TEXT`, it would be a `string`. This is still an option.

**Comment by tiandian** [comment]
but if you create a empty table, it has no rows,
then SELECT typeof(column) FROM table  you will get  empty,
how do you know the column type?

**Comment by bricelam** [comment]
Yes, we could then fallback to using the same heuristics SQLite does on the declared column type.

**Comment by tiandian** [comment]
how to using the same heuristics SQLite does on the declared column type? 
how do you map a column type for a empty table.

**Comment by bricelam** [comment]
All I'm saying is that we already decided not to map column types to CLR types.

There are definitely issues around `NULL` values and columns with mixed types that we need to think about.

`DataTable` is new to .NET Standard 2.0 and we haven't yet done anything to make Microsoft.Data.Sqlite more compatible with it. Implementing `SqliteDataReader.GetSchemaTable()` was only the first step.

**Comment by bricelam** [comment]
See the [Determination Of Column Affinity](https://www.sqlite.org/datatype3.html#determination_of_column_affinity) section of *Datatypes In SQLite Version 3*.

**Comment by bricelam** [comment]
P.S. Because of these affinity rules, I strongly recommend only using the column types `INTEGER`, `REAL`, `TEXT`, and `BLOB`. Otherwise you'll end up with `INTEGER` values in your `STRING` column just because it happened to be numeric.

**Comment by tiandian** [comment]
i still can't determine whether you way can work well,  
but i will be glad to test after you change,
thank very much!

**Comment by bricelam** [comment]
We decided to split this into two issues so they can be addressed individually:
* Improve SqliteDataReader.GetFieldType() when NULL (#435)
* Improve SqliteDataReader.GetSchemaTable() DataType (#436)
