### ISSUE TITLE
NuGet package is missing content

### ISSUE THREAD

**Issue by Adevill20** [aspnet/Microsoft.Data.Sqlite#439]
the complete "lib" folder including the DLL is missing.

**Comment by smitpatel** [comment]
@Adevill20 - Which version of the package?

**Comment by Adevill20** [comment]
2.0.0 https://www.nuget.org/packages/Microsoft.Data.SQLite/2.0.0

**Comment by bricelam** [comment]
That's a metapackage that brings in `Microsoft.Data.Sqlite.Core` (which contains the actual assemly)
