### ISSUE TITLE
SqliteConnection throws exception when creating new connection string

### ISSUE THREAD

**Issue by Muhomorik** [aspnet/Microsoft.Data.Sqlite#440]
Hello,

I am following this [guide](https://docs.microsoft.com/en-us/ef/core/get-started/full-dotnet/new-db), but for SQLite and Update-Database throws this exception:
I am using WPF and .Net 4.6.2. Note that I am not actually running the applicatin. The PM console throws exception.

> > PM> Update-Database
> System.TypeInitializationException: Typinitieraren för Microsoft.Data.Sqlite.SqliteConnection utlöste ett undantag. ---> System.Reflection.TargetInvocationException: Ett undantagsfel har inträffat i målet för en aktivering. ---> System.TypeLoadException: Metoden sqlite3__mprintf_q i typen SQLitePCL.SQLite3Provider_e_sqlite3 från sammansättningen SQLitePCLRaw.provider.e_sqlite3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9c301db686d0bd12 saknar implementering.
>    vid SQLitePCL.Batteries_V2.Init()
>    --- Slut på stackspårning för interna undantag ---
>    vid System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    vid System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    vid System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    vid Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
>    vid Microsoft.Data.Sqlite.SqliteConnection..cctor()
>    --- Slut på stackspårning för interna undantag ---
>    vid Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
>    vid Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
>    vid Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
>    vid Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.MigrateUsingConnection(IDiagnosticsLogger`1 diagnostics, IMigrator migrator, IRelationalConnection connection)
>    vid Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
>    vid Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
>    vid Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> Typinitieraren för Microsoft.Data.Sqlite.SqliteConnection utlöste ett undantag.

**Comment by bricelam** [comment]
Could you share your `*.csproj` files?

**Comment by Muhomorik** [comment]
The problem seems to be with SQLitePCL-prerelease bundle, 1.1.9+. Seems like smth is missing in the references.

[CsWpfEfCoreSqlite.zip](https://github.com/aspnet/Microsoft.Data.Sqlite/files/1370801/CsWpfEfCoreSqlite.zip)

**Comment by mlischka** [comment]
@ericsink Same issue here. When downgrading SQLitePCLRaw.core to v1.1.8 it works again.

**Comment by bricelam** [comment]
@Muhomorik it looks like your mixing 1.1.8 and 1.1.9 SQLitePCL.raw assemblies:

Package | Version
--- | ---
SQLitePCLRaw.bundle_green | 1.1.8
SQLitePCLRaw.core | 1.1.9-pre20170905093404
SQLitePCLRaw.lib.e_sqlite3.linux | 1.1.8
SQLitePCLRaw.lib.e_sqlite3.osx | 1.1.9-pre20170831090547
SQLitePCLRaw.lib.e_sqlite3.v110_xp | 1.1.8
SQLitePCLRaw.provider.e_sqlite3.net45 | 1.1.8

Try updating all of them to 1.1.9.
