### ISSUE TITLE
Not supporting MacOS client?

### ISSUE THREAD

**Issue by tomerdomshlak** [aspnet/Microsoft.Data.Sqlite#445]
Hi,

I'm having a shared .NET standard 2.0 project, which will be referenced by iOS, Android, Windows and MacOS platforms.

I've already managed to make iOS and Android work, but the MacOS client crashes.

System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.provider.sqlite3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=62684c7b4f184e3f' or one of its dependencies.

Any help with this please?

Thanks!

**Comment by ericsink** [comment]
If this is a Xamarin.Mac project, try adding this prerelease nuget package:

SQLitePCLRaw.lib.e_sqlite3.osx.1.1.9-pre20170831090547

Background on this bug:

ericsink/SQLitePCL.raw#170
