### ISSUE TITLE
Implement DbDataAdapter (and DbCommandBuilder)

### ISSUE THREAD

**Issue by ststeiger** [aspnet/Microsoft.Data.Sqlite#455]
The class SqliteFunction and SqliteFunctionAttribute are missing. 
SqliteDataAdapter is also missing. 
These are needed for projects that implement them, e.g. Lumisoft Mail Server. 
This used to work with mono.
That sucks. 

For reference: 
https://github.com/jstedfast/MimeKit/blob/master/Mono.Data.Sqlite/SQLiteFunction.cs
https://github.com/jstedfast/MimeKit/blob/master/Mono.Data.Sqlite/SQLiteFunctionAttribute.cs

Example usage:
```

#if NOT_DOTNET_CORE
using System.Data.SQLite;
#else
using SQLiteFunction = Microsof.Data.Sqlite.SqliteFunction;
using SQLiteFunctionAttribute = Microsof.Data.Sqlite.SqliteFunctionAttribute;
using FunctionType = Microsof.Data.Sqlite.FunctionType;
#endif 

using System.Text.RegularExpressions;


namespace System.Data.SQLite
{

    [SQLiteFunction(Name = "REGEXP", Arguments = 2, FuncType = FunctionType.Scalar)]
    class SqlLite_Regex : SQLiteFunction
    {
        public override object Invoke(object[] args)
        {
            return Regex.IsMatch(System.Convert.ToString(args[1]), System.Convert.ToString(args[0]), RegexOptions.IgnoreCase);
        }
    }

}

```

**Comment by bricelam** [comment]
We chose to implement user-defined functions differently than System.Data.SQLite. Please see the [scalar](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/17e4cd22d7c43c721eb51925ab0864187fa3ffd0/samples/ScalarFunctionSample/Program.cs) and [aggregate](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/17e4cd22d7c43c721eb51925ab0864187fa3ffd0/samples/AggregateFunctionSample/Program.cs) samples.

**Comment by bricelam** [comment]
Instead of using `DbDataAdapter`, have you considered using a technology that builds on top of Microsoft.Data.Sqlite like Entity Framework Core or Dapper?

**Comment by bricelam** [comment]
@divega, do we have an idea of how many new applications are using `DbDataAdapter`? I was under the it has been largely displaced by other technologies.

I think the cost of implementing (or even accepting and maintaining a PR for) this if fairly high, and we'd need a compelling reason to justify it.

**Comment by ststeiger** [comment]
Yea, it would be better to replace it, that's certainly correct. 
I considered doing that, but it's a bit problematic, because the API making use of it uses DataSets which it passes between MailServer-interfaces (configuration, data).
Since I'm also porting the entire Mail-Server to .NET-Core, I don't want to start experimenting with changes before I'm sure it runs as before.  

The data-adapter shouldn't be very difficult, I actually managed to do that in about 5 minutes. 
Just copied data-adapter from 
https://github.com/jstedfast/MimeKit/blob/master/Mono.Data.Sqlite/SQLiteDataAdapter.cs
into my dll and replaced occurences of Mono.Data.Sqlite with Microsoft.Data.Sqlite. 

The result of that is here 
https://github.com/ststeiger/Lumisoft.Net.Core/tree/master/xml_API_NetStandard/_garbage_MSFIX
(I didn't check if that would actually work as expected).
But I gave up on that strategy when having to implement SQL-Function.

Instead I just took Mono.Data.Sqlite from MimeKit and converted it to NetStandard 2.0 
https://github.com/ststeiger/Lumisoft.Net.Core/tree/master/Mono.Data.Sqlite

That worked. 

I didn't know Microsof.Data.Sqlite supported functions (and didn't look at the gihub repo), so looking at your links - I like the new variant of function-definition better. 

I might just want to change back to Microsoft.Data.Sqlite, once all other things are running. 
Is Microsof.Data.Sqlite actually based on the fully managed sqlite-code ? 
Or does it still rely on the x86/x64/elf/arm native dlls ? 

By the way, the mailserver is largely working right now ;)
Only being hold-back by missing System.Security.Cryptography.Pkcs.CmsSigner and System.Security.Cryptography.Pkcs.SignedCms

**Comment by bricelam** [comment]
> I like the new variant of function-definition better.

So did we. 😉 

> Is Microsof.Data.Sqlite actually based on the fully managed sqlite-code? Or does it still rely on the x86/x64/elf/arm native dlls?

We build on top of SQLitePCL.raw (also used by Azure Mobile Apps, SQLite-net & AWSSDK) which P/Invokes to a native SQLite implementation (e.g. SQLCipher, the machine-installed version of SQLite or a locally deployed version).

> How is deployment supposed to work?

SQLitePCL.raw should copy e_sqlite3.dll to the output directory (or another variant depending on how you installed it). How are you publishing? A few people have run into problems using `win-*` as the platform, You should specify at least `win7-*`.

**Comment by ststeiger** [comment]
Shame, a fully managed version would have been more interesting - albeit certainly slower. 
How I published ? 
I didn't, yet. I just compiled it with Visual Studio, debug mode. 
Just because there were no sqlite files and no Microsoft.Data.Sqlite.dll in the output. 

This seems to be a general problem. 
For example: 
I implemented a System.Drawing.Image-wrapper.
Here:
https://github.com/ststeiger/Lumisoft.Net.Core/blob/master/Luminet_NetStandard/___NetPort/NamespaceFix.cs

And ImageSharp requires these nuget libraries:
- System.Buffers
- System.Memory (pre-release)
- System.Runtime.CompilerServices.Unsafe
plus
SixLabors.Core
which requires System.Numerics.Vector 

Now I reference ImageSharp in Luminet_NetStandard, but 
- System.Buffers
- System.Memory (pre-release)
- System.Runtime.CompilerServices.Unsafe
- System.Numerics.Vector 
do not appear in the output (compile-debug).

Same thing for Microsoft.Data.Sqlite + PCL

The mail-server-port is now completely finished, btw. 
Implemented the missing System.Drawing.Image, SignedCms and CmsSigner  parts - testing still todo.

**Comment by bricelam** [comment]
Are you using a class library? If so, NuGet won't bin-place dependencies by default. You'll need to add:

``` xml
<PropertyGroup>
  <CopyNuGetImplementations>True</CopyNuGetImplementations>
</PropertyGroup>
```

**Comment by divega** [comment]
> @divega, do we have an idea of how many new applications are using DbDataAdapter?

@bricelam let's chat about how to think about this when we triage this issue. It is possible we may be able to find some data, not sure, but I am also not sure this is the right question :smile_cat:

**Comment by ajcvickers** [comment]
We discussed this in triage and decided that, for now, we don't want to support DbDataAdapter and related classes in this provider. These are older APIs/technologies, and we would like to keep this provider clean and simple. However, if enough people request this functionality specifically in this provider, then we will reconsider this decision, so please comment or thumbs up this issue if this is something you need.

**Comment by jogibear9988** [comment]
@ststeiger did you see that System.Data.Sqlite now also supports NetCore, so maybe you could use it

**Comment by ststeiger** [comment]
@jogibear9988: Have long since settled for Mono.Data.Sqlite. 
There I kow that it works and how it works. 
Does System.Data.Sqlite nuget also contain and deploy the x86/x64 binaries for Linux on the fly without installation in system-path ? 
I'm sceptical - have used System.Data.Sqlite in the past and because it didn't work on Linux, that's how I ended up with Mono.Data.Sqlite everywhere.

**Comment by jogibear9988** [comment]
I also used Mono, but it is not really well supported! Code seems to be a fork of System.Data.Sqlite but many patches are not included

**Comment by bricelam** [comment]
They share a common ancestor--created by Robert Simpson. But they have definitely diverged.

Are there any places where their behavior is different than Microsoft.Data.Sqlite which you would like to see us fix? (Or not-implemented features that aren't on our backlog?)

**Comment by bricelam** [comment]
P.S. We've reconsidered implementing DbDataAdapter. See #520

**Comment by jogibear9988** [comment]
Don't know if you are missing any in thsi lib.
I only saw that when we used Mono.Data.Sqlite, that there are many fixes in System.Data.Sqlite, wich haven't been ported to the Mono one. Also the Mono one does not seem to get many fixes, while System.Data.Sqlite is very active. So I suggest every to use System.Data.Sqlite instead of the Mino one (when you are using Mono).
When using Net Core, it depends. Maybe we need a Perf. comparison between System.Data.Sqlite and your Code, because for me that's what mostly matters. Most people use ORM Mappers, so they are not Interested if they use System.Data.Sqlite or yours. Only the Performance matters

**Comment by ststeiger** [comment]
Well, yea, there's one major divergence: 
Microsoft.Data.Sqlite considers implementing DbDataAdapter, while Mono.Data.Sqlite & System.Data.SQLite actually already implements it since a long time ;)

Now as to quality and what sense that makes, that's another story. 
I think the mono assembly mainly contains all the fixes to make it run on Linux, while System.Data.SQlite probably contains more engine/wrapper fixes. 
Don't know if you're actually testing your version of SQLite on Linux, or just on Azure. 
But if it runs (on Linux - bin-deploy with the app straight from nuget without major surgery) that's good enough. 

**If you implement DbDataAdapter, be sure to also implement DbCommandBuilder**, because that can really save ME from writing a lot of SQL or from having to use EntityFramwork for inserts/updates.
Which means you (respecively I) don't have a model to maintain in sync with the db - so I can do DB-FIRST and can actually care about the data-structures. 

DbAdapter with DataTables otherwise is largely a waste of RAM.
I actually much prefer to use datareader and output the data very directely to json, such as [here](https://github.com/ststeiger/AnySqlWebAdmin/blob/master/AnySqlWebAdmin/Code/SQL/SqlServiceJsonHelper.cs). 

My stumbling block was simply just that [Ivar Lumi](http://www.lumisoft.ee/lsWWW/ENG/Products/Mail_Server/mail_index_eng.aspx?type=info) used it extensively in his [C# mailserver](https://www.codeproject.com/Articles/16423/LumiSoft-MailServer) passing it all around multiple interfaces as DataTable/DataSet/DataGridView. 

The mail server is working now, by the way, here: 
https://github.com/ststeiger/Lumisoft.Net.Core

Maybe you can use that mail server to play around with the IMAP search functionality in your version of SQLite, for a performance test, because Ivar's reason for using SQLite (he used MS-SQL and PG-SQL before), was that MS/PG-SQL was too slow for IMAP search operations. 

I maintain that's because he should have done the searching with Lucene (or elasticsearch if at scale), and just didn't know Lucene .NET exists, or how it works (my opinion - not a fact, just a claim). 

It's probably not uncommon to use SQLite in fast-search scenarios.
An interesting idea would be to combine SQLite and Lucene in one interface for querying/inserting - to provide super fast search functionality that goes beyond the capabilities of SQL.
