### ISSUE TITLE
Custom Functions - Get AccessViolationException or NullReferenceException randomly

### ISSUE THREAD

**Issue by dahovey** [aspnet/Microsoft.Data.Sqlite#462]
Hello,

I am running into AccessViolationExceptions and NullReferenceExceptions that occur randomly while trying to use User Defined Functions with sqlite. The project this affects is using EntityFrameworkCore but I can also reproduce with just this library.

It appears to be an issue with a memory leak but I've tested this with a custom function that takes no parameters and always returns null value, so I'm not sure what could be causing the memory leak.

Please help.

**Package version**

Reproduced using `Microsoft.Data.Sqlite` version `1.1.4` and `2.0.0`.

**Steps to reproduce:**

1. Create and open SqliteConnection.
2. Call native `sqlite3_create_function` using Handle from open connection. Created function with no parameters and will always return null.
```
            var status = sqlite3_create_function(_handle, functionName,
                 0, 4, IntPtr.Zero, FunctionCallback, IntPtr.Zero, IntPtr.Zero);
```
3. Create SqliteCommand and ExecuteScalar sql command that selects return value from custom function. 
```
      using (var comm = conn.CreateCommand())
                        {
                            comm.CommandText = $"SELECT {CustomFunction1.Name}()";

                            var value = comm.ExecuteScalar();
                        }
```
4. Repeat steps 1-3.

**Issues**

Exception occurs on call to ExecuteScalar. When AccessViolationException occurs:

```
System.AccessViolationException occurred
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

When NullReferenceException occurs:

```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_step(IntPtr stmt)
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_step(IntPtr stm)
   at SQLitePCL.raw.sqlite3_step(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at SqliteCustomFunctionTest.Program.Main(String[] args) in \\mac\home\Documents\Visual Studio 2017\Projects\SqliteCustomFunctionTest\SqliteCustomFunctionTest\Program.cs:line 36
```

**Weird Fix**

If I call `GC.Collect();` after closing SqliteConnection then everything works fine.

**I created test Console application that shows problem I am facing, on GitHub:**
[https://github.com/dahovey/SqliteCustomFunctionTest](https://github.com/dahovey/SqliteCustomFunctionTest)

**Comment by bricelam** [comment]
(Cross-referencing [the question on StackOverflow](https://stackoverflow.com/questions/47595219/get-accessviolationexception-or-nullreferenceexception-when-using-udf-w-sqlite) in case it gets sorted out there first.)

**Comment by bricelam** [comment]
Are those P/Invokes correct? We wrote a [MarshalEx.StringToHGlobalUTF8](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/rel/1.1.1/src/Microsoft.Data.Sqlite/Interop/MarshalEx.cs#L33) method to pass `IntPtr`s instead of `byte[]`...

**Comment by bricelam** [comment]
In 2.0.0, you can leverage SQLitePCL.raw: `SQLitePCL.raw.sqlite3_create_function(connection.Handle, `...

**Comment by dahovey** [comment]
Thank you so much!

Using the `SQLitePCL.raw.sqlite3_create_function(connection.Handle,...` it worked fine. I was able to figure out issues using source of that function.

It boiled down to my not using GCHandle, and my not creating instance of delegate that is passed into `sqlite3_create_function`.

Thanks again.
