### ISSUE TITLE
SqliteParameterCollection.AddRange(Array) throws InvalidCastException

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#465]
Found and fixed by @mdisg in PR #464

**Comment by smitpatel** [comment]
+1 on patch

**Comment by ajcvickers** [comment]
@bricelam Risk looks low but impact also looks low. Justification?

**Comment by bricelam** [comment]
I'm fine waiting until we get more demand.

**Comment by bricelam** [comment]
The worst case I can see is that it breaks us with some generic ADO.NET technology. They could work around it externally by using code like this:

``` csharp
foreach (DbParameter parameter in parameters)
{
    dbCommand.Parameters.Add(parameter);
}
```

...but they may be reluctant to work around a bug that only occurs in one ADO.NET provider.

**Comment by mdisg** [comment]
That was my initial workaround to get the code up and running but it's a little bit messy not being able to use the existing `AddRange` method.

**Comment by ajcvickers** [comment]
Triage: holding off for now on patching, but may revisit with additional feedback or a change in the patch bar.
