### ISSUE TITLE
Override DbConnection.DbProviderFactory

### ISSUE THREAD

**Issue by divega** [aspnet/Microsoft.Data.Sqlite#467]
We should start returning the singleton provider factory for Sqlite so that `DbProviderFactories.GetFactory(DbConnection)` starts to work in 2.1. 

cc @roji @alexkeh @bgrainger since this is probably missing in many ADO.NET providers that target .NET Standard 2.0.

**Comment by bgrainger** [comment]
Thanks for the heads-up; already implemented in MySqlConnector here: https://github.com/mysql-net/MySqlConnector/blob/307679552f4c39d0f1bf565a58f8afd286f2d81a/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs#L219

**Comment by roji** [comment]
Same here for Npgsql: https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/NpgsqlConnection.cs#L1366, this was present when .NET Standard 2.0 was implemented.

**Comment by divega** [comment]
I stand corrected. I checked after I read @bgrainger's answer and it seems DbConnection.DbProviderFactory is in .NET Standard 2.0, so it shouldn't be a problem to override it.
