### ISSUE TITLE
Save Memory Db to file

### ISSUE THREAD

**Issue by glcjr** [aspnet/Microsoft.Data.Sqlite#469]
Is there a sample for saving a database that was started as an in memory one to a file? I looked elsewhere and found a command BackUpDatabase but it doesn't appear to be implemented in this library. Is there another way?

**Comment by bricelam** [comment]
Backup API is coming in 2.1. Until then, you can use the backup API in SQLitePCL.raw directly.

**Comment by glcjr** [comment]
Thanks bricelam!

**Comment by bricelam** [comment]
Duplicate of #17
