### ISSUE TITLE
Is there a signed version?

### ISSUE THREAD

**Issue by MariusSeattle** [aspnet/Microsoft.Data.Sqlite#481]
Is there any signed version of Microsoft.Data.Sqlite? I am trying to release a signed version of my sdk but it requires all my deps to be signed. Ideally I don't want to take MDS deps and sign each one of them.

**Comment by Eilon** [comment]
@MariusSeattle which file(s) are not signed in there? And are you referring to the Authenticode signature or the strong-name key? (The assembly should have both.)
