### ISSUE TITLE
Syntax used to create a 'Temporary' database

### ISSUE THREAD

**Issue by danielmoncada** [aspnet/Microsoft.Data.Sqlite#483]
Can't seem to get this working, as this is an invalid keyword for 'FileUri'.

```
System.ArgumentException: Keyword not supported: 'fulluri'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
```

Looking at previous connection strings, this is how a tempory database would have been created:

```cs
var connection = SQLiteConnection("FullUri=file:");
``` 
Has the syntax changed for .NET core?

**Comment by bricelam** [comment]
Also (since I'm curios), why not use an in-memory database instead? `Filename=:memory:`?

**Comment by danielmoncada** [comment]
> Using Filename=file: should work.

Thank you, this worked!

> Also (since I'm curios), why not use an in-memory database instead? Filename=:memory:?

From my understanding, using the SQLite temporary database allows the "best" of both worlds, where part of the data is still cached in memory (when needed), but is ultimately stored in a temporary file. My concern was that having the entire database in memory 'could' potentially cause issues if the database gets too big.

From docs:

> Even though a disk file is allocated for each temporary database, in practice the temporary database usually resides in the in-memory pager cache and hence is very little difference between a pure in-memory database created by ":memory:" and a temporary database created by an empty filename. The sole difference is that a ":memory:" database must remain in memory at all times whereas parts of a temporary database might be flushed to disk if database becomes large or if SQLite comes under memory pressure.

Is `Filename=:memory:` any different than `Data Source=InMemDb; Mode=Memory; Cache=Shared `?

**Comment by bricelam** [comment]
> Is Filename=:memory: any different than Data Source=InMemDb; Mode=Memory; Cache=Shared?

`:memory:` can't be shared between connections.
