### ISSUE TITLE
InvalidOperationException : Invalid attempt to call Read when reader is closed.

### ISSUE THREAD

**Issue by mdisg** [aspnet/Microsoft.Data.Sqlite#484]
Some days have past since i last worked with .NET Core and SQLite. The last time i used the latest stable release 2.0 in which #465 was an issue. Working around that was possible and our program worked as intended. Yesterday i switched to the latest 2.1 preview version which shows another issue.

We are using some kind of a wrapper which internally creates a command on a existing connection within a using clause. Within the using we create a data reader using the method `ExecuteReader()`. This reader is then returned to the caller. The command itself is disposed and the connection stays open for the next request. 

This is our code to retrieve a data reader:
```
using (var command = CreateCommand(connection, sqlCommandText))
{
    if (command != null)
    {
        if (parameters != null)
        {
            foreach (var parameter in parameters)
            {
                if (parameter != null)
                {
                    command.Parameters.Add(parameter);
                }
            }
        }

        methodResult.Result = command.ExecuteReader(commandBehavior);
    }
}
```

This works fine using the stable 2.0 version or the .NET Framework ADO.NET Provider [System.Data.SQLite](http://system.data.sqlite.org). This also works with System.Data.SqlClient to access a regular sql server. But it failes using the 2.1-preview of Microsoft.Data.SQLite. A exception `System.InvalidOperationException : Invalid attempt to call Read when reader is closed.` is thrown on calling the `Read` method after the command was disposed.

The problem is caused by calling the dispose method of the cached data reader in the dispose method of the command.
This was added by the commit [Update SqliteCommand.Prepare implementation](https://github.com/aspnet/Microsoft.Data.Sqlite/commit/8e4db9926bef3a9d2463907a36754fe8256cd9c8#diff-0561eef0368965f9acff5b0472c65fc6)
```
private void DisposePreparedStatements()
{
    if (DataReader != null)
    {
        DataReader.Dispose();
        DataReader = null;
    }

    foreach (var stmt in _preparedStatements)
    {
        stmt.Dispose();
    }

    _preparedStatements.Clear();
}
```

A question on that, why is the data reader cached within the command? Seems to be a specific thing to Microsoft.Data.SQLite i do not see that on other implementations.
If this is required for some reason, which i think it is, it would be cleaner to control that behavior by a parameter in a new constructor of the SqliteCommand class instead of changing the default behavior which differs to other ADO.NET implementations. By default the data reader should not be cached and not be disposed by  SqliteCommand. Using the DbDataReader object after disposal of the command object should be possible.

Please see this test method which reproduces the issue:

```
[Fact]
public void Use_reader_after_command_is_disposed()
{
    using (var connection = new SqliteConnection("Data Source=:memory:"))
    {
        var parameterValue1 = new SqliteParameter("@Value1", SqliteType.Text);
        parameterValue1.Value = "ABCDE";
        DbDataReader reader = null;
        using (var command = connection.CreateCommand())
        {
            command.CommandText = "SELECT @Value1;";
            command.Parameters.Add(parameterValue1);
            connection.Open();				
            reader = command.ExecuteReader();
        }
        
        Assert.True(reader.Read());
        Assert.Equal(parameterValue1.Value, reader.GetString(0));
    }
}
```

**Comment by ajcvickers** [comment]
@mdisg The command owns the resources being used and so must not be closed until the reader has finished using it, which cannot be guarenteed to be the case unless the reader has finished consuming all results and has itself been disposed.

**Comment by mdisg** [comment]
Alright, but then one question on that why does using the reader work with other implementations like `SqlCommand/SqlDataReader`? If releasing the resources must be guaranteed then all other implementations should have the same problem. Do they ignore it or do they simply use a different approach? In the previous release it worked well without disposing the reader and the change does not seem to be a bugfix.

So if we want to use the reader we have to do consider that Microsoft.Data.Sqlite does it own thing. 

Please rework this so that it works like in other ADO.NET providers.

**Comment by ajcvickers** [comment]
@mdisg Some ADO.NET providers may allow this usage, either accidentally or by design, but it is not universal. So when targeting certain ADO.NET providers you could choose to write code based on the specific behavior of a given ADO.NET provider, even if that behavior falls outside the contracts offered by the ADO.NET API. However, when doing so, there is a risk that this will break in the future, especially when the behavior has been designed explicitly that way, but just works that way anyway. Also, if you then switch to another provider it may not work. For example, I have seen cases where you can do certain things with a DbCommand after it has been disposed with certain providers, while in other cases the provider will throw. So it's not safe to assume that because something works with provider A, then it means that it is safe to use that everywhere.

**Comment by mehmetgoren** [comment]
You have broken backward-compatibility by doing this.

**Comment by jogibear9988** [comment]
This also breaks migrator.net

**Comment by bgrainger** [comment]
> Some ADO.NET providers may allow this usage, either accidentally or by design, but it is not universal. 

It's fairly universal. 

See my [SO answer](https://stackoverflow.com/questions/47779128/datareader-mysql-connector-dispose/47806069#47806069) where I added a test to my [AdoNet.Specification.Tests](https://github.com/mysql-net/AdoNetApiTest) project and all ADO.NET providers except MySql.Data >= 6.10 passed (I was testing Microsoft.Data.Sqlite 2.0.0 at the time).
