### ISSUE TITLE
BundleInitializer not working

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#490]
I'm getting the following when using the nightly builds.
```
Unhandled Exception: System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
   at SQLitePCL.SQLite3Provider_bait.SQLitePCL.ISQLite3Provider.sqlite3_libversion()
   at SQLitePCL.raw.sqlite3_libversion()
   at Microsoft.Data.Sqlite.SqliteConnection.get_ServerVersion()
```

**Comment by bricelam** [comment]
It looks like the assembly identity has changed:
``` diff
- SQLitePCLRaw.batteries_v2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8226ea5df37bcae9
+ SQLitePCLRaw.batteries_v2, Version=1.1.10.53, Culture=neutral, PublicKeyToken=8226ea5df37bcae9
```

@ericsink Was this by design or should it remain `1.0.0.0`?

**Comment by ericsink** [comment]
By design.  See discussion of "proper assembly versioning" in ericsink/SQLitePCL.raw#181.

That said, I'm willing to keep discussing this.  I made the change, hesitantly, in response to feedback, because I got convinced it was the right thing to do.  I just want to do the right thing.  :-)

**Comment by bricelam** [comment]
I think it's the right thing to do in general, but this assembly might be special. It's more of a contract/abstraction and sometimes it makes sense never to evolve them nor change their identity. (like the xunit.abstractions which is used for forward-compatible cross-domain communication)

I'm good either way; I just wanted to double check it was by design for this assembly.

**Comment by ericsink** [comment]
And when you say "this assembly", are you referring specifically to SQLitePCLRaw.batteries_v2, and not to any other assemblies in SQLitePCL.raw?

**Comment by bricelam** [comment]
Correct

**Comment by ericsink** [comment]
I am currently stamping the same version number on all assemblies.

If I leave it this way for the batteries_v2 assembly, what change will you need to make?  A binding redirect?

Is this the only assembly that caused a problem for you?  If so, I wonder why that is...

**Comment by bricelam** [comment]
Yes, this is the only assembly and it's because we don't actually compile against it--we explicitly load it by its identity (which changed). If we compiled against it the binding redirects would be automatically added by MSBuild.

The reason we can't compile against it is because the consumer might not actually be using a bundle and we don't want to break AOT compilers.

The fix (if you choose to keep the new version) is just to load the assembly without an explicit version.

**Comment by ericsink** [comment]
Ah, that makes sense.

I am inclined to leave things as they are, stamping the same version on every assembly.  The hassle of special-casing this one assembly doesn't (currently) seem worth the trouble.

**Comment by bricelam** [comment]
Sounds good to me. We'll update our code.
