### ISSUE TITLE
Wrong data type used by efcore on databases generated by migrations

### ISSUE THREAD

**Issue by Dinokin** [aspnet/Microsoft.Data.Sqlite#498]
i don't know if this is the right place to be posting this issue but i couldn't find a better place so....

basically the database generated by efcore migrations determines decimal values as TEXT instead of REAL
that breaks linq functions like Max(), since it wont return the actual maximum value

**Comment by bricelam** [comment]
By design. REAL would be lossy. Calculations involving `decimal` need to be performed on the client. We have a few EF bugs in this area, so you may need to add an explicit `ToList()` inside your queries at times.
