### ISSUE TITLE
Database file keep locked even after the connection is closed

### ISSUE THREAD

**Issue by fvoronin** [aspnet/Microsoft.Data.Sqlite#506]
I'm using Microsoft.Data.Sqlite (2.1.0-preview2-final) in netcoreapp2.0 application.
My code is pretty straightforward, I open the connection to new db-file , create some tables, insert some data (not much) and then close the connection and dispose everything just to be on the safe side. But still, I get the error "The process cannot access the file 'test.db' because it is being used by another process."  when I try to delete the file after it's being populated with the data.

A workaround was found: call `GC.Collect();` with `GC.WaitForPendingFinalizers();` before delete db-file.

Sorry, I could not reproduce this error on a simple example. 😞 
And, on previous version Microsoft.Data.Sqlite (2.0.0) this error was not noticed.

**Comment by evil-shrike** [comment]
also #271 
a generally recommended workaround that works is to call GC.Collect - https://stackoverflow.com/questions/2779599/sqlite-locking-file-even-though-connection-is-closed

**Comment by bricelam** [comment]
I dug into this. The only way I was able to hit it was by not disposing `SqliteCommand` objects. This causes some `sqlite3_stmt` objects to be finalized after the call to `SqliteConnection.Dispose()`.

We *could* update `SqliteCommand` call `sqlite3_stmt.Dispose()` during finalization so everything is freed in the same generation.
