### ISSUE TITLE
SQLite exception is not thrown due to unique key index violation

### ISSUE THREAD

**Issue by jaimestuardo** [aspnet/Microsoft.Data.Sqlite#507]
Hello,

When I run context.SaveChangesAsync in EF 6, I get this in Output windows of Visual Studio:

```
SQLite error (2067): abort at 26 in [INSERT INTO [Transaccion]([FuncionarioId], [FechaHora], [TicketEnviado], [TicketImpreso], [Checksum], [Crypted], [EntradaSalida], [Equipo])
 VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7);]:
```

I know that error is due to unique key index violation, but, why SQLite does not send an Exception?

I am using last SQLite that NuGet installs (1.0.108.0)

Regards
Jaime

**Comment by smitpatel** [comment]
@jaimestuardo - This repo is Microsoft.Data.Sqlite. You are using System.Data.Sqlite in EF6. You are on wrong repo. The repo you are looking for is at https://system.data.sqlite.org/
