### ISSUE TITLE
DllNotFoundException in 2.1.0-rc1-final with net47 app / netstandard library

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Microsoft.Data.Sqlite#521]
I've created a gist with the reproduction: https://gist.github.com/Tragetaschen/e4d3370d56792a267c8d4fbaf7947096

There's a `netstandard2.0` library that references `Microsoft.Data.Sqlite` version `2.1.0-rc1-final`, and a net47 application referencing that library. When I run the app, I'm getting a `DllNotFoundException` for `e_sqlite3`.

There are a couple of ways to fix it:
- Use versions `2.0.0` or `2.0.1` in the library
- Add the `Microsoft.Data.Sqlite` package reference to the application in addition to the library
- Make the library (multi-)target `net47`

**Comment by Tragetaschen** [comment]
Related: https://github.com/aspnet/EntityFrameworkCore/issues/12105

Instead of `Microsof.Data.Sqlite` it's enough to reference `SQLitePCLRaw.bundle_green` directly in the app. Adding that reference to the library doesn't help, though.

**Comment by Tragetaschen** [comment]
Is there a NuGet issue that I can follow?

**Comment by bricelam** [comment]
NuGet/Home#6091
