### ISSUE TITLE
Hope to support SQLite 3.24.0

### ISSUE THREAD

**Issue by guodf** [aspnet/Microsoft.Data.Sqlite#526]
See [SQLite3.24.0](https://www.sqlite.org/changes.html)
In addition, we hope that this is a fully functional SQLite class library

**Comment by guodf** [comment]
Microsoft. SQLite ConnectionString does not support Synchronizationmodes, CacheSize) and other keywords, I need to bulk insert data, now is 40000tps/s, I feel too slow.

See [System.Data.Sqlite](https://github.com/Faithlife/System.Data.SQLite/blob/master/src/System.Data.SQLite/SQLiteConnectionStringBuilder.cs)

**Comment by bricelam** [comment]
See #309

And [Bulk Insert in Microsoft.Data.Sqlite](https://www.bricelam.net/2017/07/20/sqlite-bulk-insert.html)
