### ISSUE TITLE
Deleting tables with specific foreign key references throws error

### ISSUE THREAD

**Issue by milan-iconics** [aspnet/Microsoft.Data.Sqlite#527]
Running the following SQL commands will throw the error `SQLite Error 1: 'no such table: main.A'.`:

    CREATE TABLE "A" (
        "ID"                            INTEGER PRIMARY KEY
    );

    CREATE TABLE "B" (
        "ID"                            INTEGER PRIMARY KEY
    );

    CREATE TABLE "C" (
        "ID"                            INTEGER PRIMARY KEY,
        "AID",
        "BID",
        CONSTRAINT "FK_C_A" FOREIGN KEY("AID") REFERENCES "A",
        CONSTRAINT "FK_C_B" FOREIGN KEY("BID") REFERENCES "B" ON DELETE CASCADE
    );

    PRAGMA foreign_keys = OFF;
    DROP TABLE "A";
    DROP TABLE "B";
    DROP TABLE "C";
    PRAGMA foreign_keys = ON;

This is as far as I could minimize my original script; the `ON DELETE CASCADE` is mandatory.

**Comment by bricelam** [comment]
Are you executing inside a transaction? If so, `PRAGMA foreign_keys = OFF` has no effect.

**Comment by milan-iconics** [comment]
My bad, I was running this in a transaction. Although I struggle to understand why this fails since the tables are empty, it behaves consistently with System.Data.SQLite.
