### ISSUE TITLE
Sqlite locks itself out when dropping table after selecting from it

### ISSUE THREAD

**Issue by milan-iconics** [aspnet/Microsoft.Data.Sqlite#528]
Sqlite throws `SQLite Error 6: 'database table is locked'.` when dropping table after selecting from it. Run this script to see:

	CREATE TABLE "A" (
	    "ID"                            INTEGER PRIMARY KEY,
	    "Col"
	);

	INSERT INTO A (Col) VALUES ('abc');

	CREATE TEMP TABLE temp.tmp AS SELECT ID FROM A;
	SELECT * FROM temp.tmp;
	DROP TABLE temp.tmp;

**Comment by bricelam** [comment]
Possibly related to #422. Try executing `DROP TABLE` in a separate command after reading all the results.

**Comment by milan-iconics** [comment]
Will do that for now.
