### ISSUE TITLE
Transactions don't handle RAISE(ROLLBACK) in triggers

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#532]
The following code throws *cannot rollback - no transaction is active*.

``` csharp
var connection = new SqliteConnection("Filename=:memory:");
connection.Open();

var command = connection.CreateCommand();
command.CommandText =
@"
    CREATE TABLE test(value);

    CREATE TRIGGER test_trigger
    BEFORE INSERT ON test
    BEGIN
        SELECT RAISE(ROLLBACK, 'error');
    END;
";
command.ExecuteNonQuery();

var transaction = connection.BeginTransaction();
try
{
    command.Transaction = transaction;
    command.CommandText = "INSERT INTO test VALUES ('data')";
    command.ExecuteNonQuery();
}
catch (SqliteException ex)
    when (ex.SqliteErrorCode == SQLitePCL.raw.SQLITE_CONSTRAINT)
{
}
finally
{
    transaction.Rollback(); // cannot rollback - no transaction is active
}
```

We should leverage `sqlite3_rollback_hook` to detect this and similar situations and try to handle them more gracefully.

**Comment by bricelam** [comment]
Similar situations:
* Trying to commit the transaction despite the error: Throws *cannot commit - no transaction is active*
* Executing another command on the connection: Executes outside of a transaction; should throw.

**Comment by ajcvickers** [comment]
@bricelam What happens to the dangling transaction? That is, what is the behavioral or end-state difference between this and a rollback?

**Comment by bricelam** [comment]
It's rolled back. So if we should just no-op if they call Rollback, but throw if they execute another command or call Commit.
