### ISSUE TITLE
.NET 4.0 compatability

### ISSUE THREAD

**Issue by lstratman** [aspnet/Microsoft.Data.Sqlite#552]
I wanted to be able to use this in a project targeting both .NET Standard and .NET Framework, and discovered that the code changes required for compatibility with net40 are actually quite minimal.  I have branches with everything working at https://github.com/medicomp/Microsoft.Data.Sqlite/tree/2.1-net40-compat and https://github.com/medicomp/Microsoft.Data.Sqlite/tree/2.2-net40-compat and would be happy to submit a PR if this is something you'd like to bring into the mainline.

**Comment by bricelam** [comment]
Compatibility with .NET Framework 4.0 is not a goal of this project. We're quite happy to let [System.Data.SQLite](https://system.data.sqlite.org/) fill that need. They maintain supported versions .NET Framework 2.0+, Mono 4.2+, and even .NET Compact Framework.

But it's great to see you were able to get it working so easily! The [PingmanTools:backport](https://github.com/PingmanTools/Microsoft.Data.Sqlite/tree/backport) fork may be interested in your changes.

**Comment by lstratman** [comment]
Totally understand, thanks for replying.  I imagine I'm in the minority, but this functionality may be useful for some other projects, any objections to me distributing a NuGet package with my fork?  The plan is to just keep pace with your releases and include only the changes necessary for .NET 4.0 compatibility.

**Comment by bricelam** [comment]
> any objections to me distributing a NuGet package with my fork?

Not at all, but I'd reach out to @zone117x (the fork owner) since he publishes the [Microsoft.Data.Sqlite.Core.Backport](https://www.nuget.org/packages/Microsoft.Data.Sqlite.Core.Backport/) package which has the same goal but for .NET Standard 1.3.

**Comment by bricelam** [comment]
In my spare time, I too [target .NET Framework 4.0](https://github.com/bricelam/ImageResizer/blob/develop/src/ImageResizer/ImageResizer.csproj#L12). 😉
