### ISSUE TITLE
Enable foreign key enforcement by default

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#62]
Regardless of SQLite's default, we should consider issuing `PRAGMA foreign_keys = ON;` by default when we open a connection.

**Comment by natemcmaster** [comment]
I think it would be better to keep the SQlite default. But because this is a common setting, we could provide a simpler API for executing PRAGMA statements.

**Comment by ErikEJ** [comment]
@natemcmaster keep the default in both this and the ef provider. I vote for enforcing foreign keys in the EF provider

**Comment by bricelam** [comment]
Yes, in triage, we decided to keep the ADO.NET "vanilla" and turn this on (by default) in the EF layer. Closing this since aspnet/EntityFramework#2380 better reflects the decision we made.
