### ISSUE TITLE
in memory shared cache connection string not working

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Microsoft.Data.Sqlite#94]
This connection string
"FullUri=file::memory:?cache=shared;"
produce Keyword not supported: 'fulluri'

Please support in memory sqlite shared cache

**Comment by natemcmaster** [comment]
Try using "Data Source= :memory: ; Cache = Shared" instead.

**Comment by andrew-vandenbrink** [comment]
While the connection string doesn't throw exception, the shared cache is not working.

**Comment by natemcmaster** [comment]
Can you provide more details? Build version, platform, evidence/error messages, etc.

**Comment by andrew-vandenbrink** [comment]
When you use in memory shared cache with SQLite,

Opening and closing in memory connection should be able to connect to the same in memory database,

https://www.sqlite.org/inmemorydb.html

So when you use in memort database without cache
Open in memory database
CreateTable test
Close
//Table test gone

but when you use in memory database with shared cache
Open in memory database with shared cache
CreateTable test
Close
//Next connection can still see table test

**Comment by bricelam** [comment]
> Opening and closing in memory connection should be able to connect to the same in memory database

I believe you have to keep at least one connection to the database open for the lifetime of the database. As soon as all connections are closed, the database is deleted.

**Comment by bricelam** [comment]
Confirmed.

> The database is automatically deleted and memory is reclaimed when the last connection to the database closes.

**Comment by andrew-vandenbrink** [comment]
Yes you are correct, thanks!
