### ISSUE TITLE
Please use the latest System.Data.Common

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Microsoft.Data.Sqlite#95]
The latest version is 4 beta which already implement async method, at this moment this repo use version 1

**Comment by natemcmaster** [comment]
I am not sure what change you are requesting as `project.json` uses System.Data.Common version 4.0.0-*. Can you make PR for the change you want?

**Comment by andrew-vandenbrink** [comment]
![capture](https://cloud.githubusercontent.com/assets/12871379/8177220/cfcc90e4-1402-11e5-9215-9ef27b16faa7.JPG)

It can be due the nuget package is not updated yet?

**Comment by ErikEJ** [comment]
@andrew-vandenbrink  Are you looking at the packages in the myget site https://www.myget.org/gallery/aspnetvnext ? Or NuGet.org (those packages are very old)

**Comment by andrew-vandenbrink** [comment]
Hi Erik, I used one from NuGet.org
Thanks I will close this issue...
