### ISSUE TITLE
Handle SQLITE_BUSY and SQLITE_LOCKED

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#97]
We do not currently handle the error code SQLITE_LOCKED (https://www.sqlite.org/rescode.html#locked). We could use the sqlite3_unlock_notify API to create blocking calls to sqlite3_step and sqlite3_prepare_v2. This should prevent the error from occurring. https://www.sqlite.org/unlock_notify.html

**Comment by rowanmiller** [comment]
We should investigate how this manifests in web scenarios. If it's broken this is P0, if not it's P1.

**Comment by rowanmiller** [comment]
@natemcmaster can you dig into the web scenarios (talk to @bricelam)

**Comment by natemcmaster** [comment]
Unfortunately, the Windows library we are using does not support sqlite3_unlock_notify. SQlite has to be compiled with SQLITE_ENABLE_UNLOCK_NOTIFY compiler flag. The Windows 32-bit redistributable is not compiled with this flag.

**Comment by natemcmaster** [comment]
@rowanmiller Yes, this is going to be a huge issue for web scenarios. I created a simple mvc app with 2 methods, one to read and one to write. I simulated 2 concurrent users, and ~50% of requests error out due to SQLITE_LOCKED.

**Comment by bricelam** [comment]
Implementation note: Only do this `if (sqlite3_compileoption_used("ENABLE_UNLOCK_NOTIFY"))`

**Comment by bricelam** [comment]
It looks like System.Data.Sqlite waits up to 150ms and tries again until the command timeout is reached.

**Comment by bricelam** [comment]
Looking more into this, we should see if executing `PRAGMA busy_timeout = 30000;` after opening the connection helps. If so, we should look into a way of making `DbCommand.CommandTimeout` set this value. The tricky part is that `PRAGMA busy_timeout;` is for the connection, not the command.

**Comment by bricelam** [comment]
Putting this up for re-triage. Given that `System.Data.SQLite` handled this, we probably should too.

**Comment by rowanmiller** [comment]
@natemcmaster we want to try and do this for v1 provided it doesn't end up being super complex. Talk to @bricelam

**Comment by natemcmaster** [comment]
Initial progress here: https://github.com/aspnet/Microsoft.Data.Sqlite/tree/blocking

Remaining work:
Figure out how to ensure we have a native library that was compiled with the SQLITE_ENABLE_UNLOCK_NOTIFY flag.

**Comment by bricelam** [comment]
We shouldn't use unlock-notify; that's a low-priority optimization in my opinion. Did you try any of the alternatives I proposed?

**Comment by natemcmaster** [comment]
I've added first support for unlock, but I can add a workaround that just retries after 150ms for when unlock_notify is unavailable.

**Comment by bricelam** [comment]
I don't think we can rely on `SQLITE_ENABLE_UNLOCK_NOTIFY`; it's not enabled by default on any of our target platforms. We could "light it up" if it's enable, but, like I said, it's low priority in my opinion.

**Comment by bricelam** [comment]
I would first try `PRAGMA busy_timeout` (or `sqlite3_busy_timeout()`) and if that doesn't work, resort to a retry loop.

**Comment by natemcmaster** [comment]
Here is retry for SQLITE_LOCKED instead. It retries every 150ms when it encounters this error. I can add SQLITE_BUSY next, but it's implementation is different. 

*Perf impliciations*
In my test setup, I have a simple mvc app handling 5 concurrent threads.
method | throughput
---|---
unlock_notify  | 135.1 req/s
retry (150ms) | 96.07 req/s

For those interested in perf, it would would be good to utilize unlock_notify when available.
