### ISSUE TITLE
sqlite3.dll not found in some DNX projects

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#99]
`System.DllNotFoundExceptionUnable to load DLL 'sqlite3': The specified module could not be found. `

This error occurs in EntityFramework.Sqlite.Tests when using this assembly. It could be because the project.json does not directly include this package directly as a dependency. 

Occurs with TestDriven.NET and Resharper XUnit test driver.

**Comment by bricelam** [comment]
We [copy it](https://github.com/aspnet/EntityFramework/blob/dev/makefile.shade#L52-L56) to the SQLite functional tests and the cross store tests. Copying it to the SQLite unit tests should make the csproj files work.

**Comment by Jerome2606** [comment]
Hello,

I have the same issue and the link of @bricelam is dead.
Where should I copy the sqlite dll ? Actually I have it in x86 and x64 folder in bin/debug ?
What changes to do in csproj ?
